const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
        HeadingLevel, AlignmentType, BorderStyle, WidthType, ShadingType,
        PageNumber, Header, Footer, PageBreak, LevelFormat } = require('docx');
const fs = require('fs');

const CONTENT_WIDTH = 9360;
const ORANGE = "E8630A";
const BLUE = "1B4F8A";
const LIGHT_BLUE = "D6E4F0";
const LIGHT_ORANGE = "FEF0E6";
const LIGHT_GREEN = "E8F8E8";
const LIGHT_RED = "FDECEA";
const LIGHT_GRAY = "F5F5F5";
const DARK_GRAY = "333333";

const border = { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" };
const borders = { top: border, bottom: border, left: border, right: border };
const noBorders = { top: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" }, bottom: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" }, left: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" }, right: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" } };

function h1(t) { return new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: t, bold: true, color: BLUE })] }); }
function h2(t) { return new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text: t, bold: true, color: BLUE })] }); }
function h3(t) { return new Paragraph({ heading: HeadingLevel.HEADING_3, children: [new TextRun({ text: t, bold: true })] }); }
function p(t, opts = {}) { return new Paragraph({ spacing: { after: 160 }, children: [new TextRun({ text: t, ...opts })] }); }
function pageBreak() { return new Paragraph({ children: [new PageBreak()] }); }
function spacer() { return new Paragraph({ spacing: { after: 200 }, children: [new TextRun("")] }); }
function bullet(t, bold = false) { return new Paragraph({ numbering: { reference: "bullets", level: 0 }, spacing: { after: 80 }, children: [new TextRun({ text: t, bold })] }); }
function numbered(t) { return new Paragraph({ numbering: { reference: "numbers", level: 0 }, spacing: { after: 80 }, children: [new TextRun({ text: t })] }); }
function codeBlock(lines) {
  return new Table({ width: { size: CONTENT_WIDTH - 240, type: WidthType.DXA }, columnWidths: [CONTENT_WIDTH - 240], borders: { top: { style: BorderStyle.SINGLE, size: 2, color: "555555" }, bottom: { style: BorderStyle.SINGLE, size: 2, color: "555555" }, left: { style: BorderStyle.SINGLE, size: 2, color: "555555" }, right: { style: BorderStyle.SINGLE, size: 2, color: "555555" } }, rows: lines.map(line => new TableRow({ children: [new TableCell({ borders: noBorders, width: { size: CONTENT_WIDTH - 240, type: WidthType.DXA }, shading: { fill: "1E1E1E", type: ShadingType.CLEAR }, margins: { top: 0, bottom: 0, left: 200, right: 200 }, children: [new Paragraph({ spacing: { after: 0, before: 0, line: 276 }, children: [new TextRun({ text: line || " ", font: "Courier New", size: 18, color: "D4D4D4" })] })] })] })) });
}
function infoBox(title, text, fill = LIGHT_BLUE, titleColor = BLUE) {
  return new Table({ width: { size: CONTENT_WIDTH, type: WidthType.DXA }, columnWidths: [CONTENT_WIDTH], rows: [new TableRow({ children: [new TableCell({ borders, width: { size: CONTENT_WIDTH, type: WidthType.DXA }, shading: { fill, type: ShadingType.CLEAR }, margins: { top: 120, bottom: 120, left: 200, right: 200 }, children: [new Paragraph({ spacing: { after: 60 }, children: [new TextRun({ text: title, bold: true, color: titleColor, size: 22 })] }), new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text, size: 20 })] })] })] })] });
}
function twoColTable(headers, rows) {
  const w0 = 3000, w1 = CONTENT_WIDTH - 3000;
  return new Table({ width: { size: CONTENT_WIDTH, type: WidthType.DXA }, columnWidths: [w0, w1], rows: [new TableRow({ children: headers.map((h, i) => new TableCell({ borders, width: { size: i === 0 ? w0 : w1, type: WidthType.DXA }, shading: { fill: BLUE, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text: h, bold: true, color: "FFFFFF", size: 20 })] })] })) }), ...rows.map((row, ri) => new TableRow({ children: row.map((cell, ci) => new TableCell({ borders, width: { size: ci === 0 ? w0 : w1, type: WidthType.DXA }, shading: { fill: ri % 2 === 0 ? "FFFFFF" : LIGHT_GRAY, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text: cell, size: 20 })] })] })) }))] });
}
function multiColTable(headers, colWidths, rows) {
  return new Table({ width: { size: colWidths.reduce((a, b) => a + b, 0), type: WidthType.DXA }, columnWidths: colWidths, rows: [new TableRow({ children: headers.map((h, i) => new TableCell({ borders, width: { size: colWidths[i], type: WidthType.DXA }, shading: { fill: BLUE, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text: h, bold: true, color: "FFFFFF", size: 20 })] })] })) }), ...rows.map((row, ri) => new TableRow({ children: row.map((cell, ci) => new TableCell({ borders, width: { size: colWidths[ci], type: WidthType.DXA }, shading: { fill: ri % 2 === 0 ? "FFFFFF" : LIGHT_GRAY, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text: cell, size: 20 })] })] })) }))] });
}

// MODULE 5: Operations S3 avancees
function module5() {
  return [
    pageBreak(),
    h1("MODULE 5 : Traitement des Operations de Stockage S3"),
    spacer(),
    p("Ce module approfondit les operations S3 avancees : upload multipart pour les gros fichiers, hosting de site statique, generation d'URLs pre-signees pour un acces temporaire securise, et la replication cross-region.", { size: 22 }),
    spacer(),

    h2("5.1 Objectifs d'Apprentissage"),
    bullet("Implementer l'upload multipart pour les fichiers volumineux (> 100 MB)"),
    bullet("Configurer S3 pour heberger un site web statique"),
    bullet("Generer des URLs pre-signees pour un acces temporaire securise"),
    bullet("Configurer la replication cross-region et cross-account"),
    bullet("Implementer S3 Transfer Acceleration pour les uploads mondiaux"),
    spacer(),

    h2("5.2 Multipart Upload - Objets Volumineux"),
    p("Pour les objets de plus de 100 MB, AWS recommande le Multipart Upload. Cela permet de diviser l'upload en parties paralleles, d'ameliorer les performances et de reprendre en cas d'erreur."),
    spacer(),
    multiColTable(
      ["Caracteristique", "Detail"],
      [3000, 6360],
      [
        ["Taille minimum par partie", "5 MB (sauf la derniere partie)"],
        ["Taille maximum par partie", "5 GB"],
        ["Nombre maximum de parties", "10 000"],
        ["Taille maximum d'objet", "5 TB (necessaire au-dela de 5 GB pour un seul upload)"],
        ["Avantage principal", "Upload parallele = meilleures performances, reprise en cas d'erreur"],
        ["Obligation", "Obligatoire pour les objets > 5 GB. Recommande pour > 100 MB"],
      ]
    ),
    spacer(),
    codeBlock([
      "package com.monapp.s3;",
      "",
      "import software.amazon.awssdk.core.sync.RequestBody;",
      "import software.amazon.awssdk.services.s3.S3Client;",
      "import software.amazon.awssdk.services.s3.model.*;",
      "import java.io.*;",
      "import java.nio.file.*;",
      "import java.util.*;",
      "",
      "public class S3MultipartUpload {",
      "",
      "    private static final int PART_SIZE = 10 * 1024 * 1024; // 10 MB par partie",
      "",
      "    public void uploadLargeFile(S3Client s3, String bucket, String key, Path filePath)",
      "            throws IOException {",
      "",
      "        // ETAPE 1 : Initier le multipart upload",
      "        CreateMultipartUploadResponse initResponse = s3.createMultipartUpload(",
      "            CreateMultipartUploadRequest.builder()",
      "                .bucket(bucket)",
      "                .key(key)",
      "                .contentType('application/octet-stream')",
      "                .serverSideEncryption(ServerSideEncryption.AES256)",
      "                .build()",
      "        );",
      "        String uploadId = initResponse.uploadId();",
      "        System.out.println('Multipart Upload initie. ID: ' + uploadId);",
      "",
      "        List<CompletedPart> completedParts = new ArrayList<>();",
      "        long fileSize = Files.size(filePath);",
      "        int partNumber = 1;",
      "",
      "        try (InputStream inputStream = Files.newInputStream(filePath)) {",
      "            byte[] buffer = new byte[PART_SIZE];",
      "            int bytesRead;",
      "",
      "            // ETAPE 2 : Uploader chaque partie",
      "            while ((bytesRead = inputStream.readNBytes(buffer, 0, PART_SIZE)) > 0) {",
      "                byte[] partData = Arrays.copyOf(buffer, bytesRead);",
      "",
      "                UploadPartResponse partResponse = s3.uploadPart(",
      "                    UploadPartRequest.builder()",
      "                        .bucket(bucket)",
      "                        .key(key)",
      "                        .uploadId(uploadId)",
      "                        .partNumber(partNumber)",
      "                        .contentLength((long) bytesRead)",
      "                        .build(),",
      "                    RequestBody.fromBytes(partData)",
      "                );",
      "",
      "                completedParts.add(CompletedPart.builder()",
      "                    .partNumber(partNumber)",
      "                    .eTag(partResponse.eTag()) // L'ETag identifie la partie",
      "                    .build());",
      "",
      "                System.out.printf('Partie %d uploadee (%.1f MB)%n',",
      "                    partNumber, bytesRead / 1_048_576.0);",
      "                partNumber++;",
      "            }",
      "        } catch (Exception e) {",
      "            // IMPORTANT : Annuler le multipart upload en cas d'erreur",
      "            // Sinon vous payez pour les parties stockees partiellement !",
      "            s3.abortMultipartUpload(AbortMultipartUploadRequest.builder()",
      "                .bucket(bucket)",
      "                .key(key)",
      "                .uploadId(uploadId)",
      "                .build());",
      "            throw new IOException('Upload echoue, upload multipart annule', e);",
      "        }",
      "",
      "        // ETAPE 3 : Completer le multipart upload",
      "        CompleteMultipartUploadResponse completeResponse = s3.completeMultipartUpload(",
      "            CompleteMultipartUploadRequest.builder()",
      "                .bucket(bucket)",
      "                .key(key)",
      "                .uploadId(uploadId)",
      "                .multipartUpload(CompletedMultipartUpload.builder()",
      "                    .parts(completedParts)",
      "                    .build())",
      "                .build()",
      "        );",
      "",
      "        System.out.println('Upload complete ! ETag final: ' + completeResponse.eTag());",
      "    }",
      "}",
    ]),
    spacer(),
    infoBox("Bonne Pratique",
      "Configurez toujours une regle de cycle de vie pour nettoyer automatiquement les uploads multipart incomplets. Chaque partie stockee dans un upload multipart non complete vous est facturee. Utilisez la propriete 'AbortIncompleteMultipartUpload' dans la regle de cycle de vie avec un delai de 7 jours.",
      LIGHT_GREEN, "2E7D32"),
    spacer(),

    h2("5.3 Hebergement de Site Web Statique sur S3"),
    p("S3 peut heberger des sites web statiques (HTML, CSS, JavaScript) sans serveur. C'est une solution economique et hautement disponible pour les SPAs (Single Page Applications)."),
    spacer(),
    codeBlock([
      "// Configurer un bucket S3 pour heberger un site web statique",
      "import software.amazon.awssdk.services.s3.model.*;",
      "",
      "public class S3StaticWebsite {",
      "",
      "    public void configureWebsite(S3Client s3, String bucket) {",
      "        // 1. Configurer le hosting de site web",
      "        s3.putBucketWebsite(PutBucketWebsiteRequest.builder()",
      "            .bucket(bucket)",
      "            .websiteConfiguration(WebsiteConfiguration.builder()",
      "                .indexDocument(IndexDocument.builder()",
      "                    .suffix('index.html')  // Page d'accueil",
      "                    .build())",
      "                .errorDocument(ErrorDocument.builder()",
      "                    .key('error.html')  // Page d'erreur 404",
      "                    .build())",
      "                // Regles de routage optionnelles (redirections)",
      "                .routingRules(",
      "                    RoutingRule.builder()",
      "                        .condition(Condition.builder()",
      "                            .keyPrefixEquals('docs/')",
      "                            .build())",
      "                        .redirect(Redirect.builder()",
      "                            .replaceKeyPrefixWith('documentation/')",
      "                            .build())",
      "                        .build()",
      "                )",
      "                .build())",
      "            .build());",
      "",
      "        // 2. Rendre le bucket accessible publiquement",
      "        // D'abord, desactiver le blocage de l'acces public",
      "        s3.putPublicAccessBlock(PutPublicAccessBlockRequest.builder()",
      "            .bucket(bucket)",
      "            .publicAccessBlockConfiguration(PublicAccessBlockConfiguration.builder()",
      "                .blockPublicAcls(false)",
      "                .ignorePublicAcls(false)",
      "                .blockPublicPolicy(false)",
      "                .restrictPublicBuckets(false)",
      "                .build())",
      "            .build());",
      "",
      "        // 3. Ajouter une politique de bucket permettant la lecture publique",
      "        String publicReadPolicy = String.format(",
      "            '{\"Version\":\"2012-10-17\",\"Statement\":[{' +",
      "            '\"Sid\":\"PublicRead\",' +",
      "            '\"Effect\":\"Allow\",' +",
      "            '\"Principal\":\"*\",' +",
      "            '\"Action\":\"s3:GetObject\",' +",
      "            '\"Resource\":\"arn:aws:s3:::%s/*\"' +",
      "            '}]}', bucket);",
      "",
      "        s3.putBucketPolicy(PutBucketPolicyRequest.builder()",
      "            .bucket(bucket)",
      "            .policy(publicReadPolicy)",
      "            .build());",
      "",
      "        // URL du site web:",
      "        // http://[bucket].s3-website-eu-west-1.amazonaws.com",
      "        System.out.println('Site web configure: http://' + bucket +",
      "            '.s3-website-eu-west-1.amazonaws.com');",
      "    }",
      "",
      "    // Deployer les fichiers du site web",
      "    public void deployWebsite(S3Client s3, String bucket, Path siteDirectory)",
      "            throws IOException {",
      "        Files.walk(siteDirectory)",
      "            .filter(Files::isRegularFile)",
      "            .forEach(file -> {",
      "                String key = siteDirectory.relativize(file).toString()",
      "                    .replace(File.separator, '/');",
      "                String contentType = detectContentType(file.toString());",
      "",
      "                try {",
      "                    s3.putObject(",
      "                        PutObjectRequest.builder()",
      "                            .bucket(bucket)",
      "                            .key(key)",
      "                            .contentType(contentType)",
      "                            .cacheControl(getCacheControl(key))",
      "                            .build(),",
      "                        RequestBody.fromFile(file)",
      "                    );",
      "                    System.out.println('Deploye: ' + key);",
      "                } catch (Exception e) {",
      "                    System.err.println('Erreur: ' + key + ' - ' + e.getMessage());",
      "                }",
      "            });",
      "    }",
      "",
      "    private String detectContentType(String filename) {",
      "        if (filename.endsWith('.html')) return 'text/html; charset=utf-8';",
      "        if (filename.endsWith('.css')) return 'text/css';",
      "        if (filename.endsWith('.js')) return 'application/javascript';",
      "        if (filename.endsWith('.json')) return 'application/json';",
      "        if (filename.endsWith('.png')) return 'image/png';",
      "        if (filename.endsWith('.jpg')) return 'image/jpeg';",
      "        if (filename.endsWith('.svg')) return 'image/svg+xml';",
      "        return 'application/octet-stream';",
      "    }",
      "",
      "    private String getCacheControl(String key) {",
      "        // Cache longue duree pour les assets avec hash (bundle.abc123.js)",
      "        if (key.matches('.*\\\\.[a-f0-9]{8,}\\\\.(js|css)')) {",
      "            return 'max-age=31536000, immutable'; // 1 an",
      "        }",
      "        // Pas de cache pour HTML (SPA routing)",
      "        if (key.endsWith('.html') || key.equals('index.html')) {",
      "            return 'no-cache, no-store, must-revalidate';",
      "        }",
      "        return 'max-age=86400'; // 24h pour le reste",
      "    }",
      "}",
    ]),
    spacer(),

    h2("5.4 URLs Pre-signees - Acces Temporaire Securise"),
    p("Les URLs pre-signees permettent d'accorder un acces temporaire a un objet S3 specifique sans exposer les credentials AWS. Elles sont ideales pour le partage de fichiers ou le telechargement direct depuis le navigateur."),
    spacer(),
    codeBlock([
      "package com.monapp.s3;",
      "",
      "import software.amazon.awssdk.services.s3.presigner.S3Presigner;",
      "import software.amazon.awssdk.services.s3.presigner.model.*;",
      "import software.amazon.awssdk.services.s3.model.*;",
      "import software.amazon.awssdk.regions.Region;",
      "import java.time.Duration;",
      "import java.net.URL;",
      "",
      "public class S3PresignedUrls {",
      "",
      "    private final S3Presigner presigner;",
      "",
      "    public S3PresignedUrls() {",
      "        // Creer le presigner (separe du client S3)",
      "        this.presigner = S3Presigner.builder()",
      "            .region(Region.EU_WEST_1)",
      "            .build();",
      "    }",
      "",
      "    // Generer une URL de TELECHARGEMENT (GET) pre-signee",
      "    public String generateDownloadUrl(String bucket, String key, Duration duration) {",
      "        GetObjectPresignRequest presignRequest = GetObjectPresignRequest.builder()",
      "            .signatureDuration(duration) // Validite de l'URL",
      "            .getObjectRequest(GetObjectRequest.builder()",
      "                .bucket(bucket)",
      "                .key(key)",
      "                .responseContentDisposition('attachment; filename=\"' + key + '\"')",
      "                .build())",
      "            .build();",
      "",
      "        PresignedGetObjectRequest presignedRequest = presigner.presignGetObject(presignRequest);",
      "        String url = presignedRequest.url().toString();",
      "",
      "        System.out.println('URL telechargement valide pendant: ' + duration);",
      "        System.out.println('URL: ' + url.substring(0, 100) + '...');",
      "        return url;",
      "    }",
      "",
      "    // Generer une URL d'UPLOAD (PUT) pre-signee",
      "    // Permet a un client de uploader directement vers S3 sans passer par votre serveur",
      "    public String generateUploadUrl(String bucket, String key, String contentType) {",
      "        PutObjectPresignRequest presignRequest = PutObjectPresignRequest.builder()",
      "            .signatureDuration(Duration.ofMinutes(15))",
      "            .putObjectRequest(PutObjectRequest.builder()",
      "                .bucket(bucket)",
      "                .key(key)",
      "                .contentType(contentType)",
      "                .serverSideEncryption(ServerSideEncryption.AES256)",
      "                .build())",
      "            .build();",
      "",
      "        return presigner.presignPutObject(presignRequest).url().toString();",
      "    }",
      "",
      "    // Cas d'usage: upload direct depuis le navigateur vers S3",
      "    // 1. Le client demande une URL pre-signee a votre API",
      "    // 2. Votre API genere l'URL avec generateUploadUrl()",
      "    // 3. Le client uploade directement vers S3 avec cette URL (PUT HTTP)",
      "    // 4. S3 stocke le fichier sans passer par votre serveur",
      "    // Avantage: economise la bande passante de votre serveur !",
      "",
      "    public void close() {",
      "        presigner.close();",
      "    }",
      "}",
    ]),
    spacer(),
    infoBox("Astuce Certification DVA-C02",
      "Les URLs pre-signees utilisent les credentials de l'entite qui les a generees. Si vous generez une URL pre-signee avec un role IAM temporaire (STS), l'URL expirera soit a la duree specififiee soit a l'expiration du token STS (la valeur la plus courte). Cela peut causer des problemes si les tokens STS expirent avant l'URL.",
      LIGHT_ORANGE, ORANGE),
    spacer(),

    h2("5.5 CORS Configuration S3"),
    p("Pour permettre aux applications web de faire des requetes directes vers S3 depuis le navigateur, vous devez configurer CORS (Cross-Origin Resource Sharing)."),
    spacer(),
    codeBlock([
      "// Configurer CORS sur un bucket S3",
      "import com.fasterxml.jackson.databind.ObjectMapper;",
      "import software.amazon.awssdk.services.s3.model.*;",
      "import java.util.List;",
      "",
      "public class S3CorsConfig {",
      "",
      "    public void configureCors(S3Client s3, String bucket) {",
      "        CORSRule corsRule = CORSRule.builder()",
      "            .allowedOrigins(",
      "                'https://monapp.com',",
      "                'https://www.monapp.com',",
      "                'http://localhost:3000'  // Dev local",
      "            )",
      "            .allowedMethods(\"GET\", \"PUT\", \"POST\", \"DELETE\", \"HEAD\")",
      "            .allowedHeaders(\"*\")",
      "            .exposedHeaders(",
      "                'ETag',",
      "                'x-amz-request-id',",
      "                'Content-Length'",
      "            )",
      "            .maxAgeSeconds(3600)",
      "            .build();",
      "",
      "        s3.putBucketCors(PutBucketCorsRequest.builder()",
      "            .bucket(bucket)",
      "            .corsConfiguration(CORSConfiguration.builder()",
      "                .corsRules(corsRule)",
      "                .build())",
      "            .build());",
      "",
      "        System.out.println('Configuration CORS appliquee sur: ' + bucket);",
      "    }",
      "}",
    ]),
    spacer(),

    h2("5.6 S3 Transfer Acceleration"),
    p("S3 Transfer Acceleration utilise le reseau CloudFront pour accelerer les uploads vers S3 depuis des clients eloignes de la region du bucket."),
    spacer(),
    codeBlock([
      "// Activer Transfer Acceleration via CLI",
      "aws s3api put-bucket-accelerate-configuration \\",
      "  --bucket mon-bucket \\",
      "  --accelerate-configuration Status=Enabled",
      "",
      "// Utiliser l'endpoint accelere dans le SDK Java",
      "S3Client acceleratedS3 = S3Client.builder()",
      "    .region(Region.EU_WEST_1)",
      "    .accelerate(true) // Active l'endpoint accelere",
      "    .build();",
      "",
      "// L'endpoint utilise devient :",
      "// mon-bucket.s3-accelerate.amazonaws.com",
      "// au lieu de :",
      "// mon-bucket.s3.eu-west-1.amazonaws.com",
    ]),
    spacer(),

    h2("5.7 Questions de Revision - Module 5"),
    infoBox("Question 1",
      "Un utilisateur tente d'uploader un fichier de 6 GB dans un bucket S3 en utilisant un simple PUT. Quelle sera la reponse d'AWS ?\nA) Le fichier sera uploade avec succes\nB) AWS retourne une erreur car la limite d'un seul PUT est 5 GB\nC) AWS divise automatiquement le fichier en parties\nD) Le fichier est tronque a 5 GB\nReponse correcte : B - La limite d'un seul PUT vers S3 est de 5 GB. Au-dela, vous devez utiliser le Multipart Upload. La limite totale d'un objet avec Multipart Upload est 5 TB.",
      LIGHT_ORANGE, ORANGE),
    spacer(),

    h2("5.8 Resume du Module"),
    bullet("Multipart Upload pour les objets > 100 MB : parallele, reprise sur erreur"),
    bullet("S3 peut heberger des sites web statiques avec index.html et gestion des erreurs"),
    bullet("Les URLs pre-signees accordent un acces temporaire sans exposer les credentials"),
    bullet("CORS doit etre configure pour les uploads directs depuis le navigateur"),
    bullet("Transfer Acceleration ameliore les performances pour les clients globaux"),
    spacer(),
  ];
}

// MODULE 6 & 7: DynamoDB
function module6and7() {
  return [
    pageBreak(),
    h1("MODULE 6 : Premiers Pas avec Amazon DynamoDB"),
    spacer(),
    p("Amazon DynamoDB est une base de donnees NoSQL entierement geree par AWS offrant des performances previsibles en millisecondes a n'importe quelle echelle. C'est le service de base de donnees serverless d'AWS, sans serveur a gerer, avec un scaling automatique.", { size: 22 }),
    spacer(),

    h2("6.1 Objectifs d'Apprentissage"),
    bullet("Comprendre le modele de donnees DynamoDB : tables, items, attributs, cles"),
    bullet("Distinguer les strategies de cles de partition et de tri"),
    bullet("Configurer les modes de facturation : On-Demand et Provisionned"),
    bullet("Implementer les operations CRUD avec le SDK Java v2"),
    bullet("Utiliser les index secondaires (GSI et LSI) pour les requetes flexibles"),
    spacer(),

    h2("6.2 Modele de Donnees DynamoDB"),
    p("DynamoDB est une base de donnees NoSQL cle-valeur et de documents. Comprendre son modele de donnees est fondamental."),
    spacer(),
    multiColTable(
      ["Concept DynamoDB", "Equivalent SQL", "Description"],
      [2200, 2000, 5160],
      [
        ["Table", "Table", "Conteneur de donnees. Pas de schema fixe sauf la cle primaire."],
        ["Item", "Ligne/Row", "Enregistrement individuel dans la table. Max 400 KB."],
        ["Attribut", "Colonne/Column", "Champ d'un item. Type: String, Number, Binary, Boolean, Null, List, Map, Set."],
        ["Cle de Partition", "Primary Key", "Attribut unique qui determine la partition de stockage (hash). Obligatoire."],
        ["Cle de Tri", "Sort Key", "Attribut optionnel pour trier les items dans une partition. Permet la requete par plage."],
        ["GSI", "Index secondaire", "Global Secondary Index: index avec une nouvelle cle de partition. Requetes flexibles."],
        ["LSI", "Index compose", "Local Secondary Index: meme cle de partition, cle de tri differente. Cree a la creation."],
      ]
    ),
    spacer(),
    infoBox("Concept Cle DynamoDB",
      "DynamoDB n'a pas de schema fixe ! Chaque item peut avoir des attributs differents. Seule la cle primaire (Partition Key + Sort Key optionnelle) est obligatoire et commune a tous les items. Cette flexibilite permet de stocker des structures de donnees heterogenes dans la meme table.",
      LIGHT_BLUE, BLUE),
    spacer(),

    h2("6.3 Strategie de Cle de Partition"),
    p("Choisir la bonne cle de partition est la decision la plus importante dans DynamoDB. Elle determine comment vos donnees sont distribuees physiquement."),
    spacer(),
    codeBlock([
      "// MAUVAISE strategie : trop peu de valeurs distinctes",
      "// Cle de partition: 'status' (valeurs: 'active', 'inactive', 'pending')",
      "// Probleme: seulement 3 partitions possibles -> hot partitions !",
      "",
      "// MAUVAISE strategie : donnees non uniformement distribuees",
      "// Cle de partition: 'country' (USA = 80% des items, autres = 20%)",
      "// Probleme: la partition 'USA' est beaucoup plus sollicitee",
      "",
      "// BONNE strategie : haute cardinalite et distribution uniforme",
      "// Cle de partition: userId (UUID - millions de valeurs distinctes)",
      "// Chaque utilisateur a sa propre partition -> distribution uniforme",
      "",
      "// EXCELLENTE strategie pour les donnees time-series :",
      "// Cle de partition: deviceId  (identifiant de l'appareil)",
      "// Cle de tri:       timestamp (horodatage de l'evenement)",
      "// Avantage: requetes par appareil ET par plage de temps",
      "",
      "// Exemple de schema pour une application de reservations :",
      "// Table: Reservations",
      "//   PK (Partition Key): reservationId (UUID v4)",
      "//   SK (Sort Key):      createdAt (ISO 8601 timestamp)",
      "",
      "// Table: UserReservations",
      "//   PK: userId",
      "//   SK: reservationId",
      "// Permet: 'Toutes les reservations de l'utilisateur X' en une seule Query",
    ]),
    spacer(),

    h2("6.4 Modes de Capacite DynamoDB"),
    p("DynamoDB propose deux modes de facturation avec des caracteristiques tres differentes :"),
    spacer(),
    twoColTable(
      ["Mode", "Description"],
      [
        ["On-Demand (a la demande)", "Facturation par requete. Pas de planning de capacite. Scaling automatique instantane. Ideal pour les charges impredictibles ou les nouvelles applications."],
        ["Provisionned (provisionne)", "Vous definissez les Read Capacity Units (RCU) et Write Capacity Units (WCU). Moins cher si la charge est previsible. Peut utiliser Auto Scaling pour ajuster automatiquement."],
      ]
    ),
    spacer(),
    codeBlock([
      "// Comprendre les RCU et WCU :",
      "//",
      "// 1 RCU (Read Capacity Unit) =",
      "//   - 1 lecture fortement coherente par seconde pour items <= 4 KB",
      "//   - 2 lectures eventuellement coherentes par seconde pour items <= 4 KB",
      "//   - 0.5 RCU pour la lecture transactionnelle",
      "//",
      "// 1 WCU (Write Capacity Unit) =",
      "//   - 1 ecriture par seconde pour items <= 1 KB",
      "//   - 2 WCU pour l'ecriture transactionnelle",
      "//",
      "// Exemples de calcul :",
      "// Item de 10 KB, 100 lectures/sec avec coherence forte :",
      "//   10 KB / 4 KB = 2.5 -> arrondi a 3 RCU par lecture",
      "//   3 RCU x 100 lectures = 300 RCU necessaires",
      "//",
      "// Item de 3 KB, 50 ecritures/sec :",
      "//   3 KB / 1 KB = 3 WCU par ecriture",
      "//   3 WCU x 50 ecritures = 150 WCU necessaires",
    ]),
    spacer(),

    h2("6.5 Creer une Table DynamoDB en Java"),
    codeBlock([
      "package com.monapp.dynamodb;",
      "",
      "import software.amazon.awssdk.services.dynamodb.DynamoDbClient;",
      "import software.amazon.awssdk.services.dynamodb.model.*;",
      "import software.amazon.awssdk.regions.Region;",
      "",
      "public class DynamoDBTableManager {",
      "",
      "    private final DynamoDbClient dynamoDB;",
      "",
      "    public DynamoDBTableManager() {",
      "        this.dynamoDB = DynamoDbClient.builder()",
      "            .region(Region.EU_WEST_1)",
      "            .build();",
      "    }",
      "",
      "    // Creer une table avec Partition Key + Sort Key",
      "    public void createReservationsTable() {",
      "        CreateTableRequest request = CreateTableRequest.builder()",
      "            .tableName('Reservations')",
      "",
      "            // Definition des attributs utilises comme cles",
      "            .attributeDefinitions(",
      "                AttributeDefinition.builder()",
      "                    .attributeName('userId')",
      "                    .attributeType(ScalarAttributeType.S) // S=String",
      "                    .build(),",
      "                AttributeDefinition.builder()",
      "                    .attributeName('reservationId')",
      "                    .attributeType(ScalarAttributeType.S)",
      "                    .build(),",
      "                AttributeDefinition.builder()",
      "                    .attributeName('createdAt')",
      "                    .attributeType(ScalarAttributeType.S) // ISO 8601 string",
      "                    .build()",
      "            )",
      "",
      "            // Schema de la cle primaire",
      "            .keySchema(",
      "                KeySchemaElement.builder()",
      "                    .attributeName('userId')",
      "                    .keyType(KeyType.HASH)   // Partition Key",
      "                    .build(),",
      "                KeySchemaElement.builder()",
      "                    .attributeName('createdAt')",
      "                    .keyType(KeyType.RANGE)  // Sort Key",
      "                    .build()",
      "            )",
      "",
      "            // Index Secondaire Global (GSI) - chercher par reservationId",
      "            .globalSecondaryIndexes(",
      "                GlobalSecondaryIndex.builder()",
      "                    .indexName('ReservationId-Index')",
      "                    .keySchema(",
      "                        KeySchemaElement.builder()",
      "                            .attributeName('reservationId')",
      "                            .keyType(KeyType.HASH)",
      "                            .build()",
      "                    )",
      "                    .projection(Projection.builder()",
      "                        .projectionType(ProjectionType.ALL)",
      "                        .build())",
      "                    .build()",
      "            )",
      "",
      "            // Mode de facturation On-Demand",
      "            .billingMode(BillingMode.PAY_PER_REQUEST)",
      "",
      "            // Chiffrement avec cle KMS geree par AWS",
      "            .sseSpecification(SSESpecification.builder()",
      "                .enabled(true)",
      "                .sseType(SSEType.AES256)",
      "                .build())",
      "",
      "            .build();",
      "",
      "        CreateTableResponse response = dynamoDB.createTable(request);",
      "        System.out.println('Table creee: ' + response.tableDescription().tableArn());",
      "",
      "        // Attendre que la table soit ACTIVE avant utilisation",
      "        dynamoDB.waiter().waitUntilTableExists(",
      "            DescribeTableRequest.builder().tableName('Reservations').build()",
      "        );",
      "        System.out.println('Table prete !');",
      "    }",
      "}",
    ]),
    spacer(),

    h2("6.6 Operations CRUD DynamoDB"),
    h3("6.6.1 Ecriture - PutItem"),
    codeBlock([
      "package com.monapp.dynamodb;",
      "",
      "import software.amazon.awssdk.services.dynamodb.model.*;",
      "import java.util.*;",
      "import java.time.Instant;",
      "",
      "public class DynamoDBCrud {",
      "",
      "    private final DynamoDbClient dynamoDB;",
      "    private static final String TABLE = 'Reservations';",
      "",
      "    // CREER un item (PutItem)",
      "    public void createReservation(String userId, String reservationId,",
      "                                   String destination, double price) {",
      "        Map<String, AttributeValue> item = new HashMap<>();",
      "",
      "        // Cles primaires (obligatoires)",
      "        item.put('userId', AttributeValue.fromS(userId));",
      "        item.put('createdAt', AttributeValue.fromS(Instant.now().toString()));",
      "",
      "        // Autres attributs",
      "        item.put('reservationId', AttributeValue.fromS(reservationId));",
      "        item.put('destination', AttributeValue.fromS(destination));",
      "        item.put('price', AttributeValue.fromN(String.valueOf(price)));",
      "        item.put('status', AttributeValue.fromS('CONFIRMED'));",
      "        item.put('passengers', AttributeValue.fromN('2'));",
      "",
      "        // Attribut de type List (DynamoDB supporte les types complexes)",
      "        item.put('amenities', AttributeValue.fromL(",
      "            AttributeValue.fromS('WIFI'),",
      "            AttributeValue.fromS('MEAL'),",
      "            AttributeValue.fromS('EXTRA_BAGGAGE')",
      "        ));",
      "",
      "        // Attribut de type Map (objet imbriqué)",
      "        item.put('contact', AttributeValue.fromM(Map.of(",
      "            'email', AttributeValue.fromS('user@example.com'),",
      "            'phone', AttributeValue.fromS('+33612345678')",
      "        )));",
      "",
      "        // Condition: n'ecraser que si l'item n'existe pas deja",
      "        PutItemRequest request = PutItemRequest.builder()",
      "            .tableName(TABLE)",
      "            .item(item)",
      "            .conditionExpression('attribute_not_exists(userId)')",
      "            .build();",
      "",
      "        try {",
      "            dynamoDB.putItem(request);",
      "            System.out.println('Reservation creee: ' + reservationId);",
      "        } catch (ConditionalCheckFailedException e) {",
      "            System.err.println('Item deja existant !');",
      "        }",
      "    }",
      "",
      "    // LIRE un item (GetItem)",
      "    public Optional<Map<String, AttributeValue>> getReservation(",
      "            String userId, String createdAt) {",
      "        GetItemResponse response = dynamoDB.getItem(GetItemRequest.builder()",
      "            .tableName(TABLE)",
      "            .key(Map.of(",
      "                'userId', AttributeValue.fromS(userId),",
      "                'createdAt', AttributeValue.fromS(createdAt)",
      "            ))",
      "            .consistentRead(true) // Lecture fortement coherente",
      "            .build());",
      "",
      "        if (!response.hasItem()) {",
      "            return Optional.empty();",
      "        }",
      "",
      "        Map<String, AttributeValue> item = response.item();",
      "        // Extraire les valeurs",
      "        String destination = item.get('destination').s();",
      "        double price = Double.parseDouble(item.get('price').n());",
      "        System.out.println('Destination: ' + destination + ', Prix: ' + price);",
      "",
      "        return Optional.of(item);",
      "    }",
      "",
      "    // METTRE A JOUR un item (UpdateItem)",
      "    public void updateReservationStatus(String userId, String createdAt,",
      "                                          String newStatus) {",
      "        dynamoDB.updateItem(UpdateItemRequest.builder()",
      "            .tableName(TABLE)",
      "            .key(Map.of(",
      "                'userId', AttributeValue.fromS(userId),",
      "                'createdAt', AttributeValue.fromS(createdAt)",
      "            ))",
      "            // Expression de mise a jour",
      "            .updateExpression(",
      "                'SET #st = :newStatus, updatedAt = :now, version = if_not_exists(version, :zero) + :one'",
      "            )",
      "            // Noms d'attributs reserves (status est un mot reserve en DynamoDB !)",
      "            .expressionAttributeNames(Map.of(",
      "                '#st', 'status'",
      "            ))",
      "            .expressionAttributeValues(Map.of(",
      "                ':newStatus', AttributeValue.fromS(newStatus),",
      "                ':now', AttributeValue.fromS(Instant.now().toString()),",
      "                ':zero', AttributeValue.fromN('0'),",
      "                ':one', AttributeValue.fromN('1')",
      "            ))",
      "            // Condition : mise a jour uniquement si l'item existe",
      "            .conditionExpression('attribute_exists(userId)')",
      "            .returnValues(ReturnValue.ALL_NEW) // Retourne l'item apres mise a jour",
      "            .build());",
      "    }",
      "",
      "    // SUPPRIMER un item (DeleteItem)",
      "    public void deleteReservation(String userId, String createdAt) {",
      "        dynamoDB.deleteItem(DeleteItemRequest.builder()",
      "            .tableName(TABLE)",
      "            .key(Map.of(",
      "                'userId', AttributeValue.fromS(userId),",
      "                'createdAt', AttributeValue.fromS(createdAt)",
      "            ))",
      "            .conditionExpression('attribute_exists(userId)')",
      "            .returnValues(ReturnValue.ALL_OLD) // Retourne l'item avant suppression",
      "            .build());",
      "    }",
      "}",
    ]),
    spacer(),

    h2("6.7 Query vs Scan - Operations de Lecture"),
    p("DynamoDB propose deux operations de lecture : Query et Scan. Comprendre leur difference est crucial pour les performances."),
    spacer(),
    twoColTable(
      ["Operation", "Comportement et Performance"],
      [
        ["Query", "Lit UNIQUEMENT les items d'une seule partition (Partition Key obligatoire). Peut filtrer par Sort Key. Tres efficace : lit seulement les donnees necessaires. TOUJOURS preferer Query quand possible."],
        ["Scan", "Lit TOUTE la table ou l'index. Tres couteux en RCU et lent sur les grandes tables. Utiliser seulement en dernier recours ou pour les petites tables. Peut etre parallelize (--parallel-scan)."],
      ]
    ),
    spacer(),
    codeBlock([
      "// QUERY - Efficace : utilise la Partition Key",
      "// 'Toutes les reservations de l'utilisateur alice apres 2024-01-01'",
      "QueryResponse queryResponse = dynamoDB.query(QueryRequest.builder()",
      "    .tableName('Reservations')",
      "",
      "    // Condition sur la Partition Key (OBLIGATOIRE pour Query)",
      "    .keyConditionExpression('userId = :uid AND createdAt >= :date')",
      "",
      "    // Filtre supplementaire (applique APRES la lecture - ne reduit pas les RCU)",
      "    .filterExpression('#st = :status')",
      "",
      "    .expressionAttributeNames(Map.of('#st', 'status'))",
      "    .expressionAttributeValues(Map.of(",
      "        ':uid', AttributeValue.fromS('alice'),",
      "        ':date', AttributeValue.fromS('2024-01-01'),",
      "        ':status', AttributeValue.fromS('CONFIRMED')",
      "    ))",
      "",
      "    .scanIndexForward(false) // false = tri DESC (plus recent en premier)",
      "    .limit(20) // Retourne au maximum 20 items",
      "    .build());",
      "",
      "queryResponse.items().forEach(item -> ",
      "    System.out.println(item.get('reservationId').s()));",
      "",
      "// SCAN - Couteux : lit toute la table",
      "// A eviter sur les grandes tables !",
      "ScanResponse scanResponse = dynamoDB.scan(ScanRequest.builder()",
      "    .tableName('Reservations')",
      "    .filterExpression('price > :minPrice')",
      "    .expressionAttributeValues(Map.of(",
      "        ':minPrice', AttributeValue.fromN('1000')",
      "    ))",
      "    .limit(100)",
      "    .build());",
      "",
      "System.out.println('Items trouves: ' + scanResponse.count());",
      "System.out.println('Items scannes: ' + scanResponse.scannedCount()); // Tous les items lus",
    ]),
    spacer(),

    h2("6.8 Index Secondaires - GSI et LSI"),
    p("Les index secondaires permettent de faire des Query sur des attributs autres que la cle primaire."),
    spacer(),
    twoColTable(
      ["Type d'Index", "Caracteristiques"],
      [
        ["GSI (Global Secondary Index)", "Cle de partition differente de la table principale. Cree et supprime a tout moment. Possede sa propre capacite de lecture/ecriture. Coherence eventuelle uniquement. Max 20 GSI par table."],
        ["LSI (Local Secondary Index)", "Meme cle de partition que la table, Sort Key differente. DOIT etre cree a la creation de la table (impossible apres). Partage la capacite de la table. Lecture fortement coherente possible. Max 5 LSI par table."],
      ]
    ),
    spacer(),
    codeBlock([
      "// Requete sur un GSI (Global Secondary Index)",
      "// 'Toutes les reservations vers Paris peu importe l'utilisateur'",
      "QueryResponse gsiResponse = dynamoDB.query(QueryRequest.builder()",
      "    .tableName('Reservations')",
      "    .indexName('Destination-Status-Index') // Nom du GSI",
      "    .keyConditionExpression('destination = :dest AND #st = :status')",
      "    .expressionAttributeNames(Map.of('#st', 'status'))",
      "    .expressionAttributeValues(Map.of(",
      "        ':dest', AttributeValue.fromS('PARIS'),",
      "        ':status', AttributeValue.fromS('CONFIRMED')",
      "    ))",
      "    .build());",
      "",
      "System.out.println('Reservations Paris CONFIRMED: ' + gsiResponse.count());",
    ]),
    spacer(),

    h2("6.9 Transactions DynamoDB"),
    p("DynamoDB supporte les transactions ACID pour les operations critiques qui doivent reussir ou echouer ensemble."),
    spacer(),
    codeBlock([
      "// Transaction : Creer une reservation ET debiter le compte utilisateur",
      "// Les deux operations doivent reussir ou les deux echouent (atomicite)",
      "TransactWriteItemsResponse response = dynamoDB.transactWriteItems(",
      "    TransactWriteItemsRequest.builder()",
      "        .transactItems(",
      "            // Operation 1 : Creer la reservation",
      "            TransactWriteItem.builder()",
      "                .put(Put.builder()",
      "                    .tableName('Reservations')",
      "                    .item(Map.of(",
      "                        'userId', AttributeValue.fromS('alice'),",
      "                        'createdAt', AttributeValue.fromS(Instant.now().toString()),",
      "                        'reservationId', AttributeValue.fromS('RES-001'),",
      "                        'status', AttributeValue.fromS('CONFIRMED'),",
      "                        'price', AttributeValue.fromN('500.00')",
      "                    ))",
      "                    .conditionExpression('attribute_not_exists(userId)')",
      "                    .build())",
      "                .build(),",
      "",
      "            // Operation 2 : Decrementer le solde du compte",
      "            TransactWriteItem.builder()",
      "                .update(Update.builder()",
      "                    .tableName('UserAccounts')",
      "                    .key(Map.of('userId', AttributeValue.fromS('alice')))",
      "                    .updateExpression('SET balance = balance - :amount')",
      "                    .conditionExpression('balance >= :amount')", // Assez de fonds ?",
      "                    .expressionAttributeValues(Map.of(",
      "                        ':amount', AttributeValue.fromN('500.00')",
      "                    ))",
      "                    .build())",
      "                .build()",
      "        )",
      "        .build()",
      ");",
      "",
      "// Limite: max 100 items dans une transaction, pas de cross-region",
    ]),
    spacer(),

    h2("6.10 DynamoDB avec le DocumentClient (Haut Niveau)"),
    p("Le DynamoDB Enhanced Client permet de mapper des classes Java vers des items DynamoDB automatiquement."),
    spacer(),
    codeBlock([
      "package com.monapp.dynamodb;",
      "",
      "import software.amazon.awssdk.enhanced.dynamodb.*;",
      "import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.*;",
      "import software.amazon.awssdk.services.dynamodb.DynamoDbClient;",
      "",
      "// 1. Definir la classe de modele avec annotations",
      "@DynamoDbBean",
      "public class Reservation {",
      "",
      "    private String userId;",
      "    private String createdAt;",
      "    private String reservationId;",
      "    private String destination;",
      "    private Double price;",
      "    private String status;",
      "",
      "    @DynamoDbPartitionKey",
      "    public String getUserId() { return userId; }",
      "    public void setUserId(String userId) { this.userId = userId; }",
      "",
      "    @DynamoDbSortKey",
      "    public String getCreatedAt() { return createdAt; }",
      "    public void setCreatedAt(String createdAt) { this.createdAt = createdAt; }",
      "",
      "    // Autres getters/setters...",
      "    public String getReservationId() { return reservationId; }",
      "    public void setReservationId(String id) { this.reservationId = id; }",
      "    public String getDestination() { return destination; }",
      "    public void setDestination(String dest) { this.destination = dest; }",
      "    public Double getPrice() { return price; }",
      "    public void setPrice(Double price) { this.price = price; }",
      "    public String getStatus() { return status; }",
      "    public void setStatus(String status) { this.status = status; }",
      "}",
      "",
      "// 2. Utiliser le Enhanced Client",
      "public class ReservationRepository {",
      "",
      "    private final DynamoDbTable<Reservation> table;",
      "",
      "    public ReservationRepository(DynamoDbClient dynamoDB) {",
      "        DynamoDbEnhancedClient enhancedClient = DynamoDbEnhancedClient.builder()",
      "            .dynamoDbClient(dynamoDB)",
      "            .build();",
      "",
      "        this.table = enhancedClient.table('Reservations',",
      "            TableSchema.fromBean(Reservation.class));",
      "    }",
      "",
      "    // Sauvegarder une reservation",
      "    public void save(Reservation reservation) {",
      "        table.putItem(reservation);",
      "    }",
      "",
      "    // Recuperer une reservation",
      "    public Reservation findById(String userId, String createdAt) {",
      "        Key key = Key.builder()",
      "            .partitionValue(userId)",
      "            .sortValue(createdAt)",
      "            .build();",
      "        return table.getItem(key);",
      "    }",
      "",
      "    // Requete par utilisateur",
      "    public java.util.List<Reservation> findByUser(String userId) {",
      "        QueryConditional queryConditional = QueryConditional",
      "            .keyEqualTo(Key.builder().partitionValue(userId).build());",
      "",
      "        return table.query(queryConditional)",
      "            .items()",
      "            .stream()",
      "            .collect(java.util.stream.Collectors.toList());",
      "    }",
      "}",
    ]),
    spacer(),

    h2("6.11 Mise en Cache avec DynamoDB Accelerator (DAX)"),
    p("DAX (DynamoDB Accelerator) est un cache en memoire entierement compatible avec DynamoDB, reduisant les latences de millisecondes a microsecondes."),
    spacer(),
    twoColTable(
      ["Caracteristique", "DynamoDB Standard vs DAX"],
      [
        ["Latence de lecture", "Single-digit milliseconds -> DAX: microseconds (jusqu'a 10x plus rapide)"],
        ["Coherence", "DynamoDB: fortement ou eventuellement coherent. DAX: eventuelle (cache peut etre desuet)"],
        ["Cout", "DAX ajoute un cout supplementaire (cluster de noeuds EC2 managé)"],
        ["Cas d'usage ideal DAX", "Applications avec beaucoup de lectures repetitives du meme item (tableau de bord, resultats populaires)"],
        ["Cas ou DAX ne convient pas", "Ecritures intensives, applications necessitant coherence forte, operations transactionnelles"],
        ["Compatibilite", "DAX est compatible avec l'API DynamoDB - changement de client uniquement"],
      ]
    ),
    spacer(),

    h2("6.12 Questions de Revision - Modules 6 & 7"),
    infoBox("Question 1",
      "Votre application DynamoDB effectue des Query sur une table par userId (Partition Key). Vous avez besoin de rechercher aussi par email qui est un attribut non-cle. Quelle solution choisissez-vous ?\nA) Effectuer un Scan avec filterExpression sur email\nB) Creer un Global Secondary Index (GSI) avec email comme Partition Key\nC) Changer la Partition Key de la table pour email\nD) Creer un Local Secondary Index (LSI) avec email comme Sort Key\nReponse correcte : B - Un GSI avec email comme Partition Key permet des Query efficaces par email. Le Scan est couteux. LSI necessiterait la meme Partition Key que la table (userId). Changer la cle principale n'est pas possible sans recreer la table.",
      LIGHT_ORANGE, ORANGE),
    spacer(),
    infoBox("Question 2",
      "Une table DynamoDB a 500 items de 8 KB chacun. Vous effectuez un Scan de toute la table. Combien de RCU sont consommes (coherence eventuelle) ?\nA) 500 RCU\nB) 250 RCU\nC) 1000 RCU\nD) 125 RCU\nReponse correcte : B - Item 8 KB: 8/4 = 2 RCU par item en coherence forte. Coherence eventuelle = 0.5 RCU par item. 500 items x 2 RCU x 0.5 = 500 RCU. Correction: 500 * (8KB/4KB) * 0.5 = 500 * 2 * 0.5 = 500 RCU. Non: 8KB/4KB = 2, pour coherence eventuelle = 2/2 = 1 RCU par item. 500 items x 1 RCU = 500 RCU.",
      LIGHT_ORANGE, ORANGE),
    spacer(),

    h2("6.13 Resume des Modules 6 & 7"),
    bullet("DynamoDB : NoSQL sans serveur avec performances previsibles en millisecondes"),
    bullet("Cle primaire : Partition Key seule ou Partition Key + Sort Key"),
    bullet("Deux modes : On-Demand (a la requete) et Provisionned (RCU/WCU configures)"),
    bullet("Query (efficace, par partition) vs Scan (couteux, toute la table)"),
    bullet("GSI : nouvelle partition key, cree a tout moment. LSI : meme partition, a creer avec la table"),
    bullet("Transactions ACID supportees sur jusqu'a 100 items"),
    bullet("DAX pour le cache en memoire (microseconds au lieu de milliseconds)"),
    spacer(),
  ];
}

// MODULE 8: AWS Lambda
function module8() {
  return [
    pageBreak(),
    h1("MODULE 8 : Traitement de la Logique avec AWS Lambda"),
    spacer(),
    p("AWS Lambda est le service de calcul serverless d'AWS. Vous ecrivez du code (fonctions), AWS s'occupe de tout le reste : serveurs, scaling, disponibilite, patching OS. Vous payez uniquement pour le temps d'execution de votre code.", { size: 22 }),
    spacer(),

    h2("8.1 Objectifs d'Apprentissage"),
    bullet("Comprendre le modele d'execution Lambda et son cycle de vie"),
    bullet("Ecrire et deployer des fonctions Lambda en Java"),
    bullet("Configurer les declencheurs (triggers) et les permissions Lambda"),
    bullet("Implanter les strategies d'optimisation des performances Java sur Lambda"),
    bullet("Tester, surveiller et debugger les fonctions Lambda"),
    spacer(),

    h2("8.2 Modele d'Execution Lambda"),
    p("Comprendre comment Lambda execute votre code est essentiel pour ecrire des fonctions efficaces."),
    spacer(),
    codeBlock([
      "Cycle de vie d'une invocation Lambda :",
      "",
      "COLD START (premiere invocation ou apres inactivite)",
      "  1. Telecharger le code depuis S3 ou ECR",
      "  2. Demarrer le runtime Java (JVM)",
      "  3. Executer le code d'initialisation (static blocks, constructeurs)",
      "  4. Executer la methode handler",
      "",
      "WARM INVOCATION (invocations suivantes pendant la meme instance)",
      "  1. Reutiliser le runtime existant (JVM deja demarree)",
      "  2. Executer uniquement la methode handler",
      "  -> Beaucoup plus rapide !",
      "",
      "Duree du Cold Start Java :",
      "  JVM : ~500ms a 2s (selon la taille du package)",
      "  GraalVM (native image) : ~10-50ms",
      "  Solution Lambda SnapStart : captures de snapshot JVM (1-2s -> quelques ms)",
    ]),
    spacer(),
    infoBox("Bonne Pratique - Optimisation Cold Start Java",
      "1. Utilisez Lambda SnapStart pour Java 11+ (capture l'etat JVM apres init, restaure le snapshot au lieu de redemarrer la JVM)\n2. Reduisez la taille du package JAR (shading, exclusion des dependances inutiles)\n3. Initialisez les clients AWS en dehors du handler (code statique) pour reutiliser entre invocations\n4. Considerez GraalVM native image pour les cold starts critiques (<100ms)",
      LIGHT_GREEN, "2E7D32"),
    spacer(),

    h2("8.3 Ecrire une Fonction Lambda en Java"),
    h3("8.3.1 Dependances Maven pour Lambda"),
    codeBlock([
      "<!-- pom.xml pour une fonction Lambda Java -->",
      "<dependencies>",
      "  <!-- Interface Lambda Java -->",
      "  <dependency>",
      "    <groupId>com.amazonaws</groupId>",
      "    <artifactId>aws-lambda-java-core</artifactId>",
      "    <version>1.2.3</version>",
      "  </dependency>",
      "",
      "  <!-- Pour les events specifiques (API Gateway, S3, DynamoDB Streams...) -->",
      "  <dependency>",
      "    <groupId>com.amazonaws</groupId>",
      "    <artifactId>aws-lambda-java-events</artifactId>",
      "    <version>3.11.4</version>",
      "  </dependency>",
      "",
      "  <!-- SDK AWS pour interagir avec d'autres services -->",
      "  <dependency>",
      "    <groupId>software.amazon.awssdk</groupId>",
      "    <artifactId>dynamodb</artifactId>",
      "  </dependency>",
      "",
      "  <!-- Serialisation JSON -->",
      "  <dependency>",
      "    <groupId>com.fasterxml.jackson.core</groupId>",
      "    <artifactId>jackson-databind</artifactId>",
      "    <version>2.16.1</version>",
      "  </dependency>",
      "</dependencies>",
      "",
      "<build>",
      "  <plugins>",
      "    <!-- Plugin pour creer un Fat JAR (uber-jar) avec toutes les dependances -->",
      "    <plugin>",
      "      <groupId>org.apache.maven.plugins</groupId>",
      "      <artifactId>maven-shade-plugin</artifactId>",
      "      <version>3.5.1</version>",
      "      <executions>",
      "        <execution>",
      "          <phase>package</phase>",
      "          <goals><goal>shade</goal></goals>",
      "        </execution>",
      "      </executions>",
      "    </plugin>",
      "  </plugins>",
      "</build>",
    ]),
    spacer(),
    h3("8.3.2 Fonction Lambda avec API Gateway"),
    codeBlock([
      "package com.monapp.lambda;",
      "",
      "import com.amazonaws.services.lambda.runtime.Context;",
      "import com.amazonaws.services.lambda.runtime.RequestHandler;",
      "import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent;",
      "import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent;",
      "import com.fasterxml.jackson.databind.ObjectMapper;",
      "import software.amazon.awssdk.services.dynamodb.DynamoDbClient;",
      "import java.util.*;",
      "",
      "// Handler principal - integre avec API Gateway",
      "public class ReservationHandler",
      "        implements RequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> {",
      "",
      "    // Initialisation en dehors du handler : reutilisee entre invocations !",
      "    private static final DynamoDbClient dynamoDB = DynamoDbClient.create();",
      "    private static final ObjectMapper objectMapper = new ObjectMapper();",
      "    private static final String TABLE_NAME = System.getenv('RESERVATIONS_TABLE');",
      "",
      "    @Override",
      "    public APIGatewayProxyResponseEvent handleRequest(",
      "            APIGatewayProxyRequestEvent request, Context context) {",
      "",
      "        // Logger Lambda (envoie vers CloudWatch Logs)",
      "        context.getLogger().log('Methode: ' + request.getHttpMethod());",
      "        context.getLogger().log('Path: ' + request.getPath());",
      "        context.getLogger().log('Memory remaining: ' +",
      "            context.getRemainingTimeInMillis() + 'ms');",
      "",
      "        try {",
      "            // Router selon la methode HTTP",
      "            return switch (request.getHttpMethod()) {",
      "                case 'GET' -> handleGet(request);",
      "                case 'POST' -> handlePost(request);",
      "                case 'DELETE' -> handleDelete(request);",
      "                default -> response(405, '{\"error\":\"Method Not Allowed\"}');",
      "            };",
      "        } catch (Exception e) {",
      "            context.getLogger().log('ERREUR: ' + e.getMessage());",
      "            return response(500, '{\"error\":\"Internal Server Error\"}');",
      "        }",
      "    }",
      "",
      "    private APIGatewayProxyResponseEvent handleGet(APIGatewayProxyRequestEvent req) {",
      "        String userId = req.getPathParameters().get('userId');",
      "",
      "        // Requete DynamoDB",
      "        QueryResponse queryRes = dynamoDB.query(QueryRequest.builder()",
      "            .tableName(TABLE_NAME)",
      "            .keyConditionExpression('userId = :uid')",
      "            .expressionAttributeValues(Map.of(",
      "                ':uid', AttributeValue.fromS(userId)))",
      "            .build());",
      "",
      "        try {",
      "            String json = objectMapper.writeValueAsString(queryRes.items());",
      "            return response(200, json);",
      "        } catch (Exception e) {",
      "            return response(500, '{\"error\":\"Serialization error\"}');",
      "        }",
      "    }",
      "",
      "    private APIGatewayProxyResponseEvent handlePost(APIGatewayProxyRequestEvent req) {",
      "        // Deserialiser le corps de la requete",
      "        String body = req.getBody();",
      "        // ... logique de creation de reservation ...",
      "        return response(201, '{\"message\":\"Reservation creee\"}');",
      "    }",
      "",
      "    private APIGatewayProxyResponseEvent handleDelete(APIGatewayProxyRequestEvent req) {",
      "        // ... logique de suppression ...",
      "        return response(204, '');",
      "    }",
      "",
      "    private APIGatewayProxyResponseEvent response(int statusCode, String body) {",
      "        return new APIGatewayProxyResponseEvent()",
      "            .withStatusCode(statusCode)",
      "            .withBody(body)",
      "            .withHeaders(Map.of(",
      "                'Content-Type', 'application/json',",
      "                'Access-Control-Allow-Origin', '*'",
      "            ));",
      "    }",
      "}",
    ]),
    spacer(),

    h2("8.4 Configuration Lambda"),
    h3("8.4.1 Parametres Importants"),
    multiColTable(
      ["Parametre", "Valeur / Description", "Impact"],
      [2200, 3800, 3360],
      [
        ["Memory (RAM)", "128 MB a 10 240 MB (10 GB)", "Plus de RAM = plus de CPU alloue proportionnellement"],
        ["Timeout", "1s a 900s (15 minutes)", "Max 15 min. Votre fonction doit se terminer avant ce delai."],
        ["Concurrence", "1000 par region par defaut", "Nombre d'invocations paralleles. Augmentable via Service Quotas."],
        ["Reserved Concurrency", "Valeur max dediee", "Garantit X executions paralleles et limite le scaling"],
        ["Provisioned Concurrency", "Instances pre-chargees", "Elimine les cold starts pour les fonctions critiques"],
        ["SnapStart", "Java 11+ seulement", "Capture l'etat JVM apres init. Reduit cold start de 90%"],
        ["Ephemeral Storage (/tmp)", "512 MB a 10 GB", "Stockage temporaire dans /tmp. Efface entre instances."],
      ]
    ),
    spacer(),

    h2("8.5 Declencheurs Lambda (Triggers)"),
    p("Lambda peut etre declenche par de nombreux services AWS. Voici les plus courants :"),
    spacer(),
    twoColTable(
      ["Source d'evenement", "Description et Pattern"],
      [
        ["API Gateway", "Requete HTTP/REST. Synchrone. Retourne une reponse HTTP. Cas d'usage: APIs web et mobiles."],
        ["S3", "Upload/suppression d'objet. Asynchrone. Cas d'usage: traitement d'images, ETL de fichiers."],
        ["DynamoDB Streams", "Changements dans une table DynamoDB. Traitement en lots. Cas d'usage: replication, audit."],
        ["SQS", "Messages dans une queue. Lambda poll la queue. Cas d'usage: traitement asynchrone de jobs."],
        ["SNS", "Notifications. Asynchrone. Cas d'usage: traitement d'alertes, notifications push."],
        ["EventBridge", "Evenements planifies ou custom. Cas d'usage: taches cron, automatisation."],
        ["CloudWatch Logs", "Filtres sur les logs. Cas d'usage: alertes en temps reel sur les erreurs."],
        ["Cognito", "Triggers authentification (pre-signup, post-confirm). Cas d'usage: personnalisation auth."],
      ]
    ),
    spacer(),

    h2("8.6 Lambda avec Declencheur S3"),
    codeBlock([
      "package com.monapp.lambda;",
      "",
      "import com.amazonaws.services.lambda.runtime.Context;",
      "import com.amazonaws.services.lambda.runtime.RequestHandler;",
      "import com.amazonaws.services.lambda.runtime.events.S3Event;",
      "import com.amazonaws.services.lambda.runtime.events.models.s3.S3EventNotification;",
      "import software.amazon.awssdk.core.ResponseBytes;",
      "import software.amazon.awssdk.services.s3.S3Client;",
      "import software.amazon.awssdk.services.s3.model.*;",
      "import java.net.URLDecoder;",
      "import java.nio.charset.StandardCharsets;",
      "",
      "// Fonction Lambda declenchee par un upload S3",
      "// Use case : traitement d'images uploadees par les utilisateurs",
      "public class ImageProcessorLambda implements RequestHandler<S3Event, String> {",
      "",
      "    private static final S3Client s3 = S3Client.create();",
      "",
      "    @Override",
      "    public String handleRequest(S3Event event, Context context) {",
      "        // Un evenement S3 peut contenir plusieurs fichiers",
      "        for (S3EventNotification.S3EventNotificationRecord record : event.getRecords()) {",
      "            String bucket = record.getS3().getBucket().getName();",
      "            // La cle S3 peut contenir des caracteres URL-encodes",
      "            String key = URLDecoder.decode(",
      "                record.getS3().getObject().getUrlDecodedKey(),",
      "                StandardCharsets.UTF_8",
      "            );",
      "",
      "            context.getLogger().log('Traitement de: ' + bucket + '/' + key);",
      "",
      "            // Verifier que c'est bien une image",
      "            if (!key.matches('.*\\\\.(jpg|jpeg|png|gif)$')) {",
      "                context.getLogger().log('Fichier ignore (pas une image): ' + key);",
      "                continue;",
      "            }",
      "",
      "            try {",
      "                // Telecharger l'image originale",
      "                byte[] imageData = s3.getObjectAsBytes(",
      "                    GetObjectRequest.builder()",
      "                        .bucket(bucket)",
      "                        .key(key)",
      "                        .build()",
      "                ).asByteArray();",
      "",
      "                // Traiter l'image (redimensionnement, compression, etc.)",
      "                byte[] processedImage = processImage(imageData);",
      "",
      "                // Sauvegarder l'image traitee dans un bucket de sortie",
      "                String outputKey = 'processed/' + key;",
      "                s3.putObject(",
      "                    PutObjectRequest.builder()",
      "                        .bucket(bucket + '-output')",
      "                        .key(outputKey)",
      "                        .contentType('image/jpeg')",
      "                        .build(),",
      "                    RequestBody.fromBytes(processedImage)",
      "                );",
      "",
      "                context.getLogger().log('Image traitee et sauvegardee: ' + outputKey);",
      "            } catch (Exception e) {",
      "                context.getLogger().log('ERREUR traitement ' + key + ': ' + e.getMessage());",
      "                throw new RuntimeException(e); // Lambda retentera",
      "            }",
      "        }",
      "        return 'Traitement termine';",
      "    }",
      "",
      "    private byte[] processImage(byte[] original) {",
      "        // Implementation du traitement d'image",
      "        // (utiliser une librairie comme TwelveMonkeys ImageIO ou Thumbnailator)",
      "        return original; // Placeholder",
      "    }",
      "}",
    ]),
    spacer(),

    h2("8.7 Deploiement d'une Fonction Lambda"),
    codeBlock([
      "# 1. Compiler et packager le projet Maven",
      "mvn clean package -DskipTests",
      "",
      "# Le JAR est cree dans target/mon-projet-1.0-shaded.jar",
      "",
      "# 2. Creer la fonction Lambda",
      "aws lambda create-function \\",
      "  --function-name ReservationService \\",
      "  --runtime java17 \\",
      "  --role arn:aws:iam::123456789012:role/lambda-execution-role \\",
      "  --handler com.monapp.lambda.ReservationHandler::handleRequest \\",
      "  --zip-file fileb://target/mon-projet-1.0-shaded.jar \\",
      "  --memory-size 512 \\",
      "  --timeout 30 \\",
      "  --environment Variables='{RESERVATIONS_TABLE=prod-reservations}' \\",
      "  --region eu-west-1",
      "",
      "# 3. Activer Lambda SnapStart (Java 11+)",
      "aws lambda put-function-code-signing-config \\",
      "  --function-name ReservationService",
      "",
      "aws lambda update-function-configuration \\",
      "  --function-name ReservationService \\",
      "  --snap-start ApplyOn=PublishedVersions",
      "",
      "# 4. Publier une version (requis pour SnapStart et Provisioned Concurrency)",
      "aws lambda publish-version \\",
      "  --function-name ReservationService",
      "",
      "# 5. Mettre a jour le code d'une fonction existante",
      "aws lambda update-function-code \\",
      "  --function-name ReservationService \\",
      "  --zip-file fileb://target/mon-projet-1.0-shaded.jar",
      "",
      "# 6. Tester la fonction",
      "aws lambda invoke \\",
      "  --function-name ReservationService \\",
      "  --payload '{\"httpMethod\":\"GET\",\"path\":\"/reservations/alice\",\"pathParameters\":{\"userId\":\"alice\"}}' \\",
      "  --cli-binary-format raw-in-base64-out \\",
      "  response.json",
      "",
      "cat response.json",
    ]),
    spacer(),

    h2("8.8 Variables d'Environnement et Secrets Manager"),
    codeBlock([
      "package com.monapp.lambda;",
      "",
      "import software.amazon.awssdk.services.secretsmanager.SecretsManagerClient;",
      "import software.amazon.awssdk.services.secretsmanager.model.*;",
      "import com.fasterxml.jackson.databind.ObjectMapper;",
      "",
      "public class SecretsHelper {",
      "",
      "    private static final SecretsManagerClient secretsClient = SecretsManagerClient.create();",
      "    private static final ObjectMapper mapper = new ObjectMapper();",
      "",
      "    // Recuperer un secret depuis Secrets Manager",
      "    // Cache le secret en variable statique pour eviter les appels repetes",
      "    private static volatile String cachedSecret = null;",
      "",
      "    public static String getDatabasePassword() {",
      "        if (cachedSecret == null) {",
      "            GetSecretValueResponse response = secretsClient.getSecretValue(",
      "                GetSecretValueRequest.builder()",
      "                    .secretId('prod/monapp/database')",
      "                    .build()",
      "            );",
      "            cachedSecret = response.secretString();",
      "        }",
      "        return cachedSecret;",
      "    }",
      "",
      "    // Configuration via variables d'environnement (pour les valeurs non sensibles)",
      "    public static String getTableName() {",
      "        return System.getenv('RESERVATIONS_TABLE');",
      "    }",
      "",
      "    public static String getRegion() {",
      "        return System.getenv().getOrDefault('AWS_REGION', 'eu-west-1');",
      "    }",
      "}",
    ]),
    spacer(),

    h2("8.9 Questions de Revision - Module 8"),
    infoBox("Question 1",
      "Une fonction Lambda Java traite des requetes API Gateway. Les utilisateurs signalent des latences elevees sur la premiere requete apres une periode d'inactivite (cold start). La fonction utilise 512 MB de RAM et Java 17. Quelle est la meilleure solution ?\nA) Augmenter le timeout de la fonction\nB) Activer Lambda SnapStart sur la version publiee\nC) Passer a Python (cold start plus rapide)\nD) Augmenter la memoire a 10 GB\nReponse correcte : B - Lambda SnapStart pour Java 11+ capture l'etat de la JVM apres l'initialisation et restaure ce snapshot au lieu de redemarrer la JVM. Cela reduit les cold starts Java de 90%+. SnapStart est disponible pour Java 11, 17 et 21.",
      LIGHT_ORANGE, ORANGE),
    spacer(),
    infoBox("Question 2",
      "Dans une fonction Lambda Java, ou devez-vous initialiser le client DynamoDB pour de meilleures performances ?\nA) A l'interieur de la methode handleRequest() a chaque invocation\nB) En tant que variable d'instance cree dans le constructeur\nC) En tant que variable statique au niveau de la classe\nD) Dans un bloc try-with-resources a l'interieur du handler\nReponse correcte : C - Les variables statiques sont initialisees une seule fois lors du demarrage de la JVM (cold start) et reutilisees pour toutes les invocations suivantes de la meme instance Lambda. Cela evite la creation couteuse du client (avec pool de connexions) a chaque invocation.",
      LIGHT_ORANGE, ORANGE),
    spacer(),

    h2("8.10 Resume du Module 8"),
    bullet("Lambda execute du code sans serveur : vous payez uniquement le temps d'execution"),
    bullet("Le cold start Java est une latence initiale - mitiguee avec SnapStart, GraalVM ou Provisioned Concurrency"),
    bullet("Initialisez toujours les clients AWS en variables statiques (hors handler) pour la reutilisation"),
    bullet("Multiples sources de declenchement : API Gateway, S3, DynamoDB Streams, SQS, etc."),
    bullet("Variables d'environnement pour la configuration, Secrets Manager pour les secrets"),
    bullet("Le handler Java doit implenter RequestHandler<Input, Output>"),
    spacer(),
  ];
}

// GENERER PART 3
async function generatePart3() {
  console.log('Generation Part 3 (Modules 5-8)...');
  const content = [
    ...module5(),
    ...module6and7(),
    ...module8(),
  ];

  const doc = new Document({
    numbering: {
      config: [
        { reference: "bullets", levels: [{ level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } }, run: { font: "Symbol" } } }] },
        { reference: "numbers", levels: [{ level: 0, format: LevelFormat.DECIMAL, text: "%1.", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },
      ]
    },
    styles: {
      default: { document: { run: { font: "Arial", size: 22 } } },
      paragraphStyles: [
        { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 40, bold: true, font: "Arial", color: BLUE }, paragraph: { spacing: { before: 480, after: 240 }, outlineLevel: 0, border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: ORANGE } } } },
        { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 32, bold: true, font: "Arial", color: BLUE }, paragraph: { spacing: { before: 320, after: 160 }, outlineLevel: 1 } },
        { id: "Heading3", name: "Heading 3", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 26, bold: true, font: "Arial", color: DARK_GRAY }, paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 2 } },
      ]
    },
    sections: [{
      properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
      headers: { default: new Header({ children: [new Paragraph({ border: { bottom: { style: BorderStyle.SINGLE, size: 2, color: BLUE } }, children: [new TextRun({ text: "Cours AWS pour Developpeurs Java - S3 | DynamoDB | Lambda", font: "Arial", size: 18, color: BLUE })] })] }) },
      footers: { default: new Footer({ children: [new Paragraph({ border: { top: { style: BorderStyle.SINGLE, size: 2, color: BLUE } }, children: [new TextRun({ text: "AWS SDK for Java v2 - 2025  Page ", font: "Arial", size: 18, color: "888888" }), new TextRun({ children: [PageNumber.CURRENT], font: "Arial", size: 18, color: BLUE })] })] }) },
      children: content
    }]
  });

  const buffer = await Packer.toBuffer(doc);
  const outputPath = '/Users/user/Desktop/travel-agency/backend/.claude/worktrees/naughty-jepsen-0d5f95/cours_aws_java_part3.docx';
  fs.writeFileSync(outputPath, buffer);
  console.log('Part 3 generee: ' + outputPath + ' - ' + Math.round(buffer.length/1024) + ' KB');
}

generatePart3().catch(console.error);
