const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
        HeadingLevel, AlignmentType, BorderStyle, WidthType, ShadingType,
        PageNumber, Header, Footer, PageBreak, LevelFormat } = require('docx');
const fs = require('fs');

const CONTENT_WIDTH = 9360;
const ORANGE = "E8630A";
const BLUE = "1B4F8A";
const LIGHT_BLUE = "D6E4F0";
const LIGHT_ORANGE = "FEF0E6";
const LIGHT_GREEN = "E8F8E8";
const LIGHT_RED = "FDECEA";
const LIGHT_GRAY = "F5F5F5";
const DARK_GRAY = "333333";

const border = { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" };
const borders = { top: border, bottom: border, left: border, right: border };
const noBorders = { top: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" }, bottom: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" }, left: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" }, right: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" } };

function h1(t) { return new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: t, bold: true, color: BLUE })] }); }
function h2(t) { return new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text: t, bold: true, color: BLUE })] }); }
function h3(t) { return new Paragraph({ heading: HeadingLevel.HEADING_3, children: [new TextRun({ text: t, bold: true })] }); }
function p(t, opts = {}) { return new Paragraph({ spacing: { after: 160 }, children: [new TextRun({ text: t, ...opts })] }); }
function pageBreak() { return new Paragraph({ children: [new PageBreak()] }); }
function spacer() { return new Paragraph({ spacing: { after: 200 }, children: [new TextRun("")] }); }
function bullet(t, bold = false) { return new Paragraph({ numbering: { reference: "bullets", level: 0 }, spacing: { after: 80 }, children: [new TextRun({ text: t, bold })] }); }
function numbered(t) { return new Paragraph({ numbering: { reference: "numbers", level: 0 }, spacing: { after: 80 }, children: [new TextRun({ text: t })] }); }
function codeBlock(lines) {
  return new Table({ width: { size: CONTENT_WIDTH - 240, type: WidthType.DXA }, columnWidths: [CONTENT_WIDTH - 240], borders: { top: { style: BorderStyle.SINGLE, size: 2, color: "555555" }, bottom: { style: BorderStyle.SINGLE, size: 2, color: "555555" }, left: { style: BorderStyle.SINGLE, size: 2, color: "555555" }, right: { style: BorderStyle.SINGLE, size: 2, color: "555555" } }, rows: lines.map(line => new TableRow({ children: [new TableCell({ borders: noBorders, width: { size: CONTENT_WIDTH - 240, type: WidthType.DXA }, shading: { fill: "1E1E1E", type: ShadingType.CLEAR }, margins: { top: 0, bottom: 0, left: 200, right: 200 }, children: [new Paragraph({ spacing: { after: 0, before: 0, line: 276 }, children: [new TextRun({ text: line || " ", font: "Courier New", size: 18, color: "D4D4D4" })] })] })] })) });
}
function infoBox(title, text, fill = LIGHT_BLUE, titleColor = BLUE) {
  return new Table({ width: { size: CONTENT_WIDTH, type: WidthType.DXA }, columnWidths: [CONTENT_WIDTH], rows: [new TableRow({ children: [new TableCell({ borders, width: { size: CONTENT_WIDTH, type: WidthType.DXA }, shading: { fill, type: ShadingType.CLEAR }, margins: { top: 120, bottom: 120, left: 200, right: 200 }, children: [new Paragraph({ spacing: { after: 60 }, children: [new TextRun({ text: title, bold: true, color: titleColor, size: 22 })] }), new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text, size: 20 })] })] })] })] });
}
function twoColTable(headers, rows) {
  const w0 = 3000, w1 = CONTENT_WIDTH - 3000;
  return new Table({ width: { size: CONTENT_WIDTH, type: WidthType.DXA }, columnWidths: [w0, w1], rows: [new TableRow({ children: headers.map((h, i) => new TableCell({ borders, width: { size: i === 0 ? w0 : w1, type: WidthType.DXA }, shading: { fill: BLUE, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text: h, bold: true, color: "FFFFFF", size: 20 })] })] })) }), ...rows.map((row, ri) => new TableRow({ children: row.map((cell, ci) => new TableCell({ borders, width: { size: ci === 0 ? w0 : w1, type: WidthType.DXA }, shading: { fill: ri % 2 === 0 ? "FFFFFF" : LIGHT_GRAY, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text: cell, size: 20 })] })] })) }))] });
}
function multiColTable(headers, colWidths, rows) {
  return new Table({ width: { size: colWidths.reduce((a, b) => a + b, 0), type: WidthType.DXA }, columnWidths: colWidths, rows: [new TableRow({ children: headers.map((h, i) => new TableCell({ borders, width: { size: colWidths[i], type: WidthType.DXA }, shading: { fill: BLUE, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text: h, bold: true, color: "FFFFFF", size: 20 })] })] })) }), ...rows.map((row, ri) => new TableRow({ children: row.map((cell, ci) => new TableCell({ borders, width: { size: colWidths[ci], type: WidthType.DXA }, shading: { fill: ri % 2 === 0 ? "FFFFFF" : LIGHT_GRAY, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text: cell, size: 20 })] })] })) }))] });
}

// MODULE 9: API Gateway
function module9() {
  return [
    pageBreak(),
    h1("MODULE 9 : Gerer les APIs avec Amazon API Gateway"),
    spacer(),
    p("Amazon API Gateway est un service entierement gere permettant de creer, publier, maintenir, surveiller et securiser des APIs REST, HTTP et WebSocket. Il agit comme la porte d'entree de vos applications vers les services backend.", { size: 22 }),
    spacer(),

    h2("9.1 Objectifs d'Apprentissage"),
    bullet("Comprendre les trois types d'API Gateway : REST, HTTP et WebSocket"),
    bullet("Configurer les ressources, methodes et integrations Lambda"),
    bullet("Implementer CORS, l'authentification et le rate limiting"),
    bullet("Utiliser les stages, variables de stage et le deploiement"),
    bullet("Optimiser avec le cache API Gateway"),
    spacer(),

    h2("9.2 Types d'API Gateway"),
    multiColTable(
      ["Type", "Protocole", "Cas d'Usage", "Avantage"],
      [1500, 1500, 3600, 2760],
      [
        ["REST API", "HTTP/1.1", "APIs avec fonctionnalites avancees : gestion ressources, validations, transformations", "Fonctionnalites les plus completes, cache integre, modeles de requete/reponse"],
        ["HTTP API", "HTTP/1.1", "APIs simples et rapides integrees a Lambda ou services HTTP", "70% moins cher que REST API, latence reduite, plus simple a configurer"],
        ["WebSocket API", "WebSocket", "Applications temps reel : chat, jeux, tableaux de bord live", "Connexions persistantes bidirectionnelles"],
      ]
    ),
    spacer(),
    infoBox("Choisir entre REST API et HTTP API",
      "HTTP API : Si vous avez besoin de simplicite et de couts reduits (70% moins cher). Supporte Lambda, URLs HTTP, JWT authorizers.\nREST API : Si vous avez besoin de fonctionnalites avancees : cache, validation des requetes, transformation des donnees (mapping templates), AWS WAF, API Keys, Usage Plans, resource policies.\nPour l'examen DVA-C02, les deux types sont testes. Connaissez les differences!",
      LIGHT_ORANGE, ORANGE),
    spacer(),

    h2("9.3 Architecture API Gateway + Lambda"),
    codeBlock([
      "Architecture typique d'une API serverless :",
      "",
      "Client (Web/Mobile)",
      "    |",
      "    | HTTPS Request",
      "    v",
      "Amazon Route 53 (DNS)",
      "    |",
      "    v",
      "Amazon CloudFront (CDN) -----> S3 (fichiers statiques: HTML/JS/CSS)",
      "    |",
      "    | /api/* requetes",
      "    v",
      "API Gateway (REST API)",
      "    |",
      "    | Authorizer JWT/Cognito",
      "    |",
      "    |-----> GET /reservations/{userId}",
      "    |           |",
      "    |           v",
      "    |       Lambda: GetReservationsFunction",
      "    |           |",
      "    |           v",
      "    |       DynamoDB: Reservations Table",
      "    |",
      "    |-----> POST /reservations",
      "    |           |",
      "    |           v",
      "    |       Lambda: CreateReservationFunction",
      "    |           |",
      "    |           |--> DynamoDB (ecriture)",
      "    |           |--> SES (email confirmation)",
      "    |           |--> SQS (queue de traitement)",
      "    |",
      "    |-----> DELETE /reservations/{id}",
      "                |",
      "                v",
      "            Lambda: DeleteReservationFunction",
    ]),
    spacer(),

    h2("9.4 Configurer API Gateway via AWS CLI"),
    codeBlock([
      "# 1. Creer une API REST",
      "aws apigateway create-rest-api \\",
      "  --name 'ReservationAPI' \\",
      "  --description 'API de gestion des reservations' \\",
      "  --endpoint-configuration types=REGIONAL \\",
      "  --region eu-west-1",
      "",
      "# Recuperer l'ID de l'API et le root resource ID",
      "API_ID='xxxxxxxxx'",
      "ROOT_ID=$(aws apigateway get-resources --rest-api-id $API_ID \\",
      "  --query 'items[?path==`/`].id' --output text)",
      "",
      "# 2. Creer une ressource /reservations",
      "aws apigateway create-resource \\",
      "  --rest-api-id $API_ID \\",
      "  --parent-id $ROOT_ID \\",
      "  --path-part reservations",
      "",
      "RESERVATIONS_ID='yyyyyyyyy'",
      "",
      "# 3. Creer une ressource /reservations/{userId} (path parameter)",
      "aws apigateway create-resource \\",
      "  --rest-api-id $API_ID \\",
      "  --parent-id $RESERVATIONS_ID \\",
      "  --path-part '{userId}'",
      "",
      "USER_RESOURCE_ID='zzzzzzzzz'",
      "",
      "# 4. Ajouter la methode GET",
      "aws apigateway put-method \\",
      "  --rest-api-id $API_ID \\",
      "  --resource-id $USER_RESOURCE_ID \\",
      "  --http-method GET \\",
      "  --authorization-type COGNITO_USER_POOLS \\",
      "  --authorizer-id $AUTHORIZER_ID \\",
      "  --request-parameters method.request.path.userId=true",
      "",
      "# 5. Integrer avec Lambda",
      "LAMBDA_ARN='arn:aws:lambda:eu-west-1:123456789012:function:GetReservations'",
      "aws apigateway put-integration \\",
      "  --rest-api-id $API_ID \\",
      "  --resource-id $USER_RESOURCE_ID \\",
      "  --http-method GET \\",
      "  --type AWS_PROXY \\",
      "  --integration-http-method POST \\",
      "  --uri 'arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/'$LAMBDA_ARN'/invocations'",
      "",
      "# 6. Donner la permission a API Gateway d'invoquer Lambda",
      "aws lambda add-permission \\",
      "  --function-name GetReservations \\",
      "  --statement-id apigw-invoke \\",
      "  --action lambda:InvokeFunction \\",
      "  --principal apigateway.amazonaws.com \\",
      "  --source-arn 'arn:aws:execute-api:eu-west-1:123456789012:'$API_ID'/*/*'",
      "",
      "# 7. Deployer l'API sur un stage",
      "aws apigateway create-deployment \\",
      "  --rest-api-id $API_ID \\",
      "  --stage-name prod \\",
      "  --stage-description 'Production'",
      "",
      "echo 'API disponible: https://'$API_ID'.execute-api.eu-west-1.amazonaws.com/prod'",
    ]),
    spacer(),

    h2("9.5 Configuration CORS dans API Gateway"),
    p("CORS (Cross-Origin Resource Sharing) permet aux applications web d'acceder a l'API depuis un domaine different. La configuration CORS dans API Gateway est critique pour les applications SPA."),
    spacer(),
    codeBlock([
      "// Configuration CORS pour une methode API Gateway via SDK Java",
      "import software.amazon.awssdk.services.apigateway.ApiGatewayClient;",
      "import software.amazon.awssdk.services.apigateway.model.*;",
      "",
      "public class ApiGatewayCorsConfig {",
      "",
      "    public void configureCors(ApiGatewayClient apiGw, String apiId, String resourceId) {",
      "",
      "        // 1. Ajouter la methode OPTIONS (preflight CORS)",
      "        apiGw.putMethod(PutMethodRequest.builder()",
      "            .restApiId(apiId)",
      "            .resourceId(resourceId)",
      "            .httpMethod('OPTIONS')",
      "            .authorizationType('NONE')",
      "            .build());",
      "",
      "        // 2. Integration MOCK pour OPTIONS (pas besoin de Lambda)",
      "        apiGw.putIntegration(PutIntegrationRequest.builder()",
      "            .restApiId(apiId)",
      "            .resourceId(resourceId)",
      "            .httpMethod('OPTIONS')",
      "            .type(IntegrationType.MOCK)",
      "            .requestTemplates(java.util.Map.of(",
      "                'application/json', '{\"statusCode\": 200}'",
      "            ))",
      "            .build());",
      "",
      "        // 3. Response de la methode OPTIONS",
      "        apiGw.putMethodResponse(PutMethodResponseRequest.builder()",
      "            .restApiId(apiId)",
      "            .resourceId(resourceId)",
      "            .httpMethod('OPTIONS')",
      "            .statusCode('200')",
      "            .responseParameters(java.util.Map.of(",
      "                'method.response.header.Access-Control-Allow-Headers', false,",
      "                'method.response.header.Access-Control-Allow-Methods', false,",
      "                'method.response.header.Access-Control-Allow-Origin', false",
      "            ))",
      "            .build());",
      "",
      "        // 4. Response de l'integration avec les headers CORS",
      "        apiGw.putIntegrationResponse(PutIntegrationResponseRequest.builder()",
      "            .restApiId(apiId)",
      "            .resourceId(resourceId)",
      "            .httpMethod('OPTIONS')",
      "            .statusCode('200')",
      "            .responseParameters(java.util.Map.of(",
      "                'method.response.header.Access-Control-Allow-Headers',",
      "                    \"'Content-Type,X-Amz-Date,Authorization,X-Api-Key'\",",
      "                'method.response.header.Access-Control-Allow-Methods',",
      "                    \"'GET,POST,PUT,DELETE,OPTIONS'\",",
      "                'method.response.header.Access-Control-Allow-Origin',",
      "                    \"'https://monapp.com'\"",
      "            ))",
      "            .build());",
      "    }",
      "}",
    ]),
    spacer(),

    h2("9.6 Authentification avec API Gateway"),
    h3("9.6.1 Authorisateurs Disponibles"),
    twoColTable(
      ["Type d'Authorisateur", "Description"],
      [
        ["IAM Authorization", "Signature SigV4. Pour les clients AWS internes (EC2, Lambda, services). Requete signee avec credentials IAM."],
        ["Cognito User Pool", "Valide un JWT Cognito. Facile a configurer. Retourne les claims du token au backend."],
        ["Lambda Authorizer (Token)", "Lambda custom qui valide un token Bearer. Flexible : JWT, OAuth2, API key custom."],
        ["Lambda Authorizer (Request)", "Lambda custom qui valide n'importe quel element de la requete (headers, query params, body)."],
        ["API Keys + Usage Plans", "Authentification simple par cle API. Avec rate limiting et quotas. Pour les APIs tiers."],
      ]
    ),
    spacer(),
    h3("9.6.2 Lambda Authorizer - Implementation Java"),
    codeBlock([
      "package com.monapp.authorizer;",
      "",
      "import com.amazonaws.services.lambda.runtime.Context;",
      "import com.amazonaws.services.lambda.runtime.RequestHandler;",
      "import com.amazonaws.services.lambda.runtime.events.APIGatewayCustomAuthorizerEvent;",
      "import com.amazonaws.services.lambda.runtime.events.IamPolicyResponse;",
      "import io.jsonwebtoken.*;",
      "import io.jsonwebtoken.security.Keys;",
      "",
      "// Lambda Authorizer qui valide un JWT Bearer token",
      "public class JWTAuthorizer",
      "        implements RequestHandler<APIGatewayCustomAuthorizerEvent, IamPolicyResponse> {",
      "",
      "    private static final String JWT_SECRET = System.getenv('JWT_SECRET');",
      "",
      "    @Override",
      "    public IamPolicyResponse handleRequest(",
      "            APIGatewayCustomAuthorizerEvent event, Context context) {",
      "",
      "        String token = event.getAuthorizationToken();",
      "",
      "        // Retirer le prefixe 'Bearer '",
      "        if (token != null && token.startsWith('Bearer ')) {",
      "            token = token.substring(7);",
      "        }",
      "",
      "        try {",
      "            // Valider et decoder le JWT",
      "            Claims claims = Jwts.parserBuilder()",
      "                .setSigningKey(Keys.hmacShaKeyFor(JWT_SECRET.getBytes()))",
      "                .build()",
      "                .parseClaimsJws(token)",
      "                .getBody();",
      "",
      "            String userId = claims.getSubject();",
      "            String role = (String) claims.get('role');",
      "",
      "            context.getLogger().log('Token valide pour utilisateur: ' + userId);",
      "",
      "            // Generer une politique IAM autorisant l'acces",
      "            return IamPolicyResponse.builder()",
      "                .withPrincipalId(userId)",
      "                .withPolicyDocument(IamPolicyResponse.PolicyDocument.builder()",
      "                    .withVersion('2012-10-17')",
      "                    .withStatement(java.util.List.of(",
      "                        IamPolicyResponse.Statement.builder()",
      "                            .withEffect('Allow')",
      "                            .withAction('execute-api:Invoke')",
      "                            .withResource(event.getMethodArn())",
      "                            .build()",
      "                    ))",
      "                    .build())",
      "                .withContext(java.util.Map.of(",
      "                    'userId', userId,",
      "                    'role', role",
      "                ))",
      "                .build();",
      "",
      "        } catch (JwtException e) {",
      "            context.getLogger().log('Token invalide: ' + e.getMessage());",
      "            // Retourner 'Deny' pour rejeter la requete",
      "            throw new RuntimeException('Unauthorized');",
      "        }",
      "    }",
      "}",
    ]),
    spacer(),

    h2("9.7 Cache API Gateway"),
    p("API Gateway peut mettre en cache les reponses pour reduire le nombre d'appels aux backends et ameliorer les performances."),
    spacer(),
    codeBlock([
      "# Configurer le cache sur un stage API Gateway",
      "aws apigateway update-stage \\",
      "  --rest-api-id $API_ID \\",
      "  --stage-name prod \\",
      "  --patch-operations \\",
      "    op=replace,path=/cacheClusterEnabled,value=true \\",
      "    op=replace,path=/cacheClusterSize,value=0.5 \\",
      "    op=replace,path='/*/*/caching/enabled',value=true \\",
      "    op=replace,path='/*/*/caching/ttlInSeconds',value=300",
      "",
      "# Dans le code Lambda, invalider le cache si necessaire",
      "# Utiliser le header 'Cache-Control: max-age=0' dans la requete du client",
      "",
      "// Java : desactiver le cache pour une methode specifique",
      "// Dans la reponse Lambda, ajouter le header :",
      "Map<String, String> headers = new HashMap<>();",
      "headers.put('Cache-Control', 'no-cache, no-store, must-revalidate');",
      "return new APIGatewayProxyResponseEvent()",
      "    .withStatusCode(200)",
      "    .withHeaders(headers)",
      "    .withBody(responseBody);",
    ]),
    spacer(),

    h2("9.8 Stages et Variables de Stage"),
    p("Les stages API Gateway permettent de deployer differentes versions de l'API (dev, staging, prod) avec des configurations independantes."),
    spacer(),
    codeBlock([
      "# Creer un stage avec des variables de stage",
      "aws apigateway create-stage \\",
      "  --rest-api-id $API_ID \\",
      "  --stage-name dev \\",
      "  --deployment-id $DEPLOYMENT_ID \\",
      "  --variables '{",
      "    \"lambdaAlias\": \"dev\",",
      "    \"tableName\": \"dev-reservations\"",
      "  }'",
      "",
      "# Dans l'integration Lambda, utiliser la variable de stage :",
      "# URI: arn:aws:lambda:eu-west-1:123456789012:function:ReservationService:${stageVariables.lambdaAlias}",
      "",
      "# Cela permet d'invoquer l'alias 'dev' de Lambda depuis le stage dev",
      "# et l'alias 'prod' depuis le stage prod",
      "",
      "# Lire les variables de stage dans Lambda :",
      "public String handleRequest(APIGatewayProxyRequestEvent event, Context context) {",
      "    // Les variables de stage sont dans les stageVariables",
      "    String tableName = event.getStageVariables().get('tableName');",
      "    // ...",
      "}",
    ]),
    spacer(),

    h2("9.9 Questions de Revision - Module 9"),
    infoBox("Question 1",
      "Votre API REST Gateway retourne des erreurs 429 (Too Many Requests) sous forte charge. Vous avez configure 1000 req/sec de throttle par defaut mais les utilisateurs specifiques depassent 100 req/sec. Quelle solution implementez-vous ?\nA) Augmenter le throttle global a 10000 req/sec\nB) Configurer des Usage Plans et API Keys avec des limites par client\nC) Ajouter plus d'instances Lambda\nD) Configurer ElastiCache devant l'API Gateway\nReponse correcte : B - Les Usage Plans dans API Gateway permettent de definir des limites de taux (rate) et des quotas (quota) par client en utilisant des API Keys. Chaque client reoit sa propre cle API associee a un Usage Plan specifique.",
      LIGHT_ORANGE, ORANGE),
    spacer(),

    h2("9.10 Resume du Module 9"),
    bullet("API Gateway : 3 types - REST API (complet), HTTP API (simple/economique), WebSocket (temps reel)"),
    bullet("Integrations : Lambda Proxy (AWS_PROXY), HTTP, Mock, Service AWS direct"),
    bullet("CORS : doit etre configure sur les methodes et dans les reponses Lambda"),
    bullet("Authentification : IAM, Cognito, Lambda Authorizer, API Keys + Usage Plans"),
    bullet("Cache : reduit les appels backend, configurable par methode avec TTL"),
    bullet("Stages : permettent de separer dev/staging/prod avec variables independantes"),
    spacer(),
  ];
}

// MODULE 10: Microservices & Step Functions
function module10() {
  return [
    pageBreak(),
    h1("MODULE 10 : Creer une Application Moderne avec les Microservices"),
    spacer(),
    p("Ce module explore les architectures de microservices sur AWS, comment decouple les applications monolithiques, et comment orchestrer des workflows complexes avec AWS Step Functions.", { size: 22 }),
    spacer(),

    h2("10.1 Objectifs d'Apprentissage"),
    bullet("Comprendre les avantages et defis des architectures microservices"),
    bullet("Identifier les patterns de communication entre microservices (sync vs async)"),
    bullet("Utiliser SQS et SNS pour le decouplage asynchrone"),
    bullet("Orchestrer des workflows avec AWS Step Functions"),
    bullet("Implementer le pattern Saga pour les transactions distribuees"),
    spacer(),

    h2("10.2 Architectures Monolithiques vs Microservices"),
    twoColTable(
      ["Critere", "Comparaison Monolithe vs Microservices"],
      [
        ["Deploiement", "Monolithe: Un seul deploiement de toute l'application. Microservices: Deploiement independant de chaque service."],
        ["Scalabilite", "Monolithe: Scale l'application entiere. Microservices: Scale uniquement le service qui en a besoin."],
        ["Technologies", "Monolithe: Une seule technologie pour tout. Microservices: Chaque service choisit sa tech optimale."],
        ["Complexite operationnelle", "Monolithe: Simple a operer. Microservices: Orchestration complexe, service discovery, observabilite distribuee."],
        ["Independance des equipes", "Monolithe: Equipes couplee, risque de conflits. Microservices: Equipes autonomes, developpement en parallele."],
        ["Base de donnees", "Monolithe: Base partagee. Microservices: Une base par service (database per service pattern)."],
      ]
    ),
    spacer(),

    h2("10.3 Patterns de Communication"),
    h3("10.3.1 Communication Synchrone vs Asynchrone"),
    codeBlock([
      "Patterns de communication entre microservices :",
      "",
      "SYNCHRONE (request-response) :",
      "  Service A ---HTTP/REST---> Service B",
      "  Service A attend la reponse de Service B",
      "  Probleme: couplage temporel, si B est down A echoue",
      "  Cas d'usage: quand la reponse est necessaire immediatement",
      "",
      "ASYNCHRONE (message-based) :",
      "  Service A ---message---> SQS Queue ---poll---> Service B",
      "  Service A n'attend pas Service B",
      "  Avantage: decouplage total, resilience aux pannes",
      "  Cas d'usage: traitement de commandes, notifications, emails",
      "",
      "EVENEMENTIEL (event-driven) :",
      "  Service A ---event---> SNS Topic ---> Service B",
      "                                   ---> Service C",
      "                                   ---> Service D",
      "  Un evenement peut avoir plusieurs consommateurs",
      "  Pattern Pub/Sub (Publish-Subscribe)",
    ]),
    spacer(),

    h2("10.4 Amazon SQS - Simple Queue Service"),
    p("SQS est le service de file d'attente de messages d'AWS. Il permet le decouplage asynchrone entre les composants d'une application."),
    spacer(),
    multiColTable(
      ["Caracteristique", "Standard Queue", "FIFO Queue"],
      [2800, 3280, 3280],
      [
        ["Ordre des messages", "Meilleur effort (non garanti)", "Strict First-In First-Out garanti"],
        ["Livraison", "Au moins une fois (possibilite de doublons)", "Exactement une fois (deduplication)"],
        ["Throughput", "Illimite (quasi illimite)", "300 msg/sec ou 3000 avec batching"],
        ["Cas d'usage", "Traitement de jobs, declencher Lambda, notification", "Commandes financieres, inventaire, transactions"],
      ]
    ),
    spacer(),
    codeBlock([
      "package com.monapp.messaging;",
      "",
      "import software.amazon.awssdk.services.sqs.SqsClient;",
      "import software.amazon.awssdk.services.sqs.model.*;",
      "import com.fasterxml.jackson.databind.ObjectMapper;",
      "import java.util.*;",
      "",
      "public class SQSService {",
      "",
      "    private static final SqsClient sqsClient = SqsClient.create();",
      "    private static final ObjectMapper mapper = new ObjectMapper();",
      "    private final String queueUrl;",
      "",
      "    public SQSService(String queueUrl) {",
      "        this.queueUrl = queueUrl;",
      "    }",
      "",
      "    // Envoyer un message",
      "    public String sendMessage(Object messageBody) throws Exception {",
      "        String messageJson = mapper.writeValueAsString(messageBody);",
      "",
      "        SendMessageResponse response = sqsClient.sendMessage(",
      "            SendMessageRequest.builder()",
      "                .queueUrl(queueUrl)",
      "                .messageBody(messageJson)",
      "                .messageAttributes(Map.of(",
      "                    'ContentType', MessageAttributeValue.builder()",
      "                        .dataType('String')",
      "                        .stringValue('application/json')",
      "                        .build(),",
      "                    'Source', MessageAttributeValue.builder()",
      "                        .dataType('String')",
      "                        .stringValue('reservation-service')",
      "                        .build()",
      "                ))",
      "                .delaySeconds(0) // Delay avant que le message soit visible",
      "                .build()",
      "        );",
      "",
      "        System.out.println('Message envoye. ID: ' + response.messageId());",
      "        return response.messageId();",
      "    }",
      "",
      "    // Recevoir et traiter les messages",
      "    public void processMessages() {",
      "        while (true) {",
      "            ReceiveMessageResponse response = sqsClient.receiveMessage(",
      "                ReceiveMessageRequest.builder()",
      "                    .queueUrl(queueUrl)",
      "                    .maxNumberOfMessages(10) // Max 10 messages par appel",
      "                    .waitTimeSeconds(20)     // Long polling (econome en API calls)",
      "                    .visibilityTimeout(30)   // 30s pour traiter le message",
      "                    .messageAttributeNames('All')",
      "                    .build()",
      "            );",
      "",
      "            for (Message message : response.messages()) {",
      "                try {",
      "                    // Traiter le message",
      "                    processMessage(message.body());",
      "",
      "                    // Supprimer le message apres traitement reussi",
      "                    sqsClient.deleteMessage(",
      "                        DeleteMessageRequest.builder()",
      "                            .queueUrl(queueUrl)",
      "                            .receiptHandle(message.receiptHandle())",
      "                            .build()",
      "                    );",
      "                } catch (Exception e) {",
      "                    // Ne pas supprimer : le message redeviendra visible apres visibilityTimeout",
      "                    // et sera retraite (ou envoye en DLQ apres maxReceiveCount tentatives)",
      "                    System.err.println('Erreur traitement: ' + e.getMessage());",
      "                }",
      "            }",
      "        }",
      "    }",
      "",
      "    private void processMessage(String body) {",
      "        System.out.println('Traitement: ' + body);",
      "        // Logique metier...",
      "    }",
      "}",
    ]),
    spacer(),
    infoBox("Dead Letter Queue (DLQ)",
      "La DLQ (Dead Letter Queue) est une queue SQS ou sont envoyes automatiquement les messages qui echouent au traitement apres un nombre maximum de tentatives (maxReceiveCount). Configurez toujours une DLQ en production pour capturer les messages problematiques et les analyser. Sans DLQ, les messages en echec sont supprimes apres retention (max 14 jours).",
      LIGHT_RED, "C62828"),
    spacer(),

    h2("10.5 Amazon SNS - Simple Notification Service"),
    p("SNS est le service de notification et de messagerie pub/sub d'AWS. Un message publie dans un topic SNS peut etre delivre simultanement a plusieurs abonnes."),
    spacer(),
    codeBlock([
      "package com.monapp.messaging;",
      "",
      "import software.amazon.awssdk.services.sns.SnsClient;",
      "import software.amazon.awssdk.services.sns.model.*;",
      "",
      "public class SNSService {",
      "",
      "    private static final SnsClient snsClient = SnsClient.create();",
      "",
      "    // Publier un evenement dans un topic SNS",
      "    public void publishReservationEvent(String topicArn, String eventType,",
      "                                          String reservationId, String userId) {",
      "        String message = String.format(",
      "            '{\"eventType\":\"%s\",\"reservationId\":\"%s\",\"userId\":\"%s\"}',",
      "            eventType, reservationId, userId);",
      "",
      "        PublishResponse response = snsClient.publish(",
      "            PublishRequest.builder()",
      "                .topicArn(topicArn)",
      "                .subject('Reservation Event: ' + eventType)",
      "                .message(message)",
      "                // Attributs pour le filtrage des messages (filter policy)",
      "                .messageAttributes(Map.of(",
      "                    'eventType', MessageAttributeValue.builder()",
      "                        .dataType('String')",
      "                        .stringValue(eventType) // RESERVATION_CREATED, CANCELLED, etc.",
      "                        .build()",
      "                ))",
      "                .build()",
      "        );",
      "",
      "        System.out.println('Evenement publie. MessageId: ' + response.messageId());",
      "    }",
      "",
      "    // Architecture Fan-Out SNS -> SQS (pattern courant)",
      "    // Topic SNS 'reservation-events'",
      "    //   |",
      "    //   |-> SQS 'email-notifications' (abonné au type RESERVATION_CREATED)",
      "    //   |-> SQS 'sms-notifications' (abonné au type PAYMENT_FAILED)",
      "    //   |-> SQS 'analytics-processing' (abonné a tous les types)",
      "    //   |-> Lambda 'audit-logger' (abonné a tous les types)",
      "    // Chaque consommateur traite independamment le meme evenement",
      "}",
    ]),
    spacer(),

    h2("10.6 AWS Step Functions"),
    p("AWS Step Functions permet d'orchestrer des workflows complexes composant des fonctions Lambda et services AWS. Chaque etape du workflow est definie dans un langage appele Amazon States Language (ASL)."),
    spacer(),
    h3("10.6.1 Cas d'Usage Step Functions"),
    bullet("Orchestration de microservices avec gestion des erreurs et retry"),
    bullet("Workflows de commandes e-commerce (validation, paiement, expedition)"),
    bullet("ETL pipeline : extraction -> transformation -> chargement"),
    bullet("Workflows d'approbation humaine (Human in the loop)"),
    bullet("Machine learning pipelines"),
    spacer(),
    h3("10.6.2 Definition d'un Workflow ASL"),
    codeBlock([
      "{",
      "  \"Comment\": \"Workflow de reservation de voyage\",",
      "  \"StartAt\": \"ValidateReservation\",",
      "  \"States\": {",
      "    \"ValidateReservation\": {",
      "      \"Type\": \"Task\",",
      "      \"Resource\": \"arn:aws:lambda:eu-west-1:123456789012:function:ValidateReservation\",",
      "      \"Retry\": [{",
      "        \"ErrorEquals\": [\"Lambda.ServiceException\", \"Lambda.SdkClientException\"],",
      "        \"IntervalSeconds\": 2,",
      "        \"MaxAttempts\": 3,",
      "        \"BackoffRate\": 2.0",
      "      }],",
      "      \"Catch\": [{",
      "        \"ErrorEquals\": [\"ValidationError\"],",
      "        \"Next\": \"NotifyValidationFailure\"",
      "      }],",
      "      \"Next\": \"ProcessPayment\"",
      "    },",
      "    \"ProcessPayment\": {",
      "      \"Type\": \"Task\",",
      "      \"Resource\": \"arn:aws:lambda:eu-west-1:123456789012:function:ProcessPayment\",",
      "      \"Catch\": [{",
      "        \"ErrorEquals\": [\"PaymentDeclinedError\"],",
      "        \"Next\": \"NotifyPaymentFailure\"",
      "      }],",
      "      \"Next\": \"ParallelNotifications\"",
      "    },",
      "    \"ParallelNotifications\": {",
      "      \"Type\": \"Parallel\",",
      "      \"Branches\": [",
      "        {",
      "          \"StartAt\": \"SendConfirmationEmail\",",
      "          \"States\": {",
      "            \"SendConfirmationEmail\": {",
      "              \"Type\": \"Task\",",
      "              \"Resource\": \"arn:aws:lambda:eu-west-1:123456789012:function:SendEmail\",",
      "              \"End\": true",
      "            }",
      "          }",
      "        },",
      "        {",
      "          \"StartAt\": \"UpdateDashboard\",",
      "          \"States\": {",
      "            \"UpdateDashboard\": {",
      "              \"Type\": \"Task\",",
      "              \"Resource\": \"arn:aws:states:::dynamodb:putItem\",",
      "              \"Parameters\": {",
      "                \"TableName\": \"reservations-dashboard\",",
      "                \"Item\": {",
      "                  \"reservationId\": {\"S.$\": \"$.reservationId\"},",
      "                  \"status\": {\"S\": \"CONFIRMED\"}",
      "                }",
      "              },",
      "              \"End\": true",
      "            }",
      "          }",
      "        }",
      "      ],",
      "      \"Next\": \"WaitForDeparture\"",
      "    },",
      "    \"WaitForDeparture\": {",
      "      \"Type\": \"Wait\",",
      "      \"SecondsPath\": \"$.secondsUntilDeparture\",",
      "      \"Next\": \"SendDepartureReminder\"",
      "    },",
      "    \"SendDepartureReminder\": {",
      "      \"Type\": \"Task\",",
      "      \"Resource\": \"arn:aws:lambda:eu-west-1:123456789012:function:SendReminder\",",
      "      \"End\": true",
      "    },",
      "    \"NotifyValidationFailure\": {",
      "      \"Type\": \"Task\",",
      "      \"Resource\": \"arn:aws:lambda:eu-west-1:123456789012:function:SendFailureNotif\",",
      "      \"End\": true",
      "    },",
      "    \"NotifyPaymentFailure\": {",
      "      \"Type\": \"Task\",",
      "      \"Resource\": \"arn:aws:lambda:eu-west-1:123456789012:function:SendPaymentFailure\",",
      "      \"End\": true",
      "    }",
      "  }",
      "}",
    ]),
    spacer(),
    h3("10.6.3 Demarrer un Workflow Step Functions en Java"),
    codeBlock([
      "package com.monapp.stepfunctions;",
      "",
      "import software.amazon.awssdk.services.sfn.SfnClient;",
      "import software.amazon.awssdk.services.sfn.model.*;",
      "import com.fasterxml.jackson.databind.ObjectMapper;",
      "import java.util.*;",
      "",
      "public class StepFunctionsService {",
      "",
      "    private static final SfnClient sfnClient = SfnClient.create();",
      "    private static final ObjectMapper mapper = new ObjectMapper();",
      "    private final String stateMachineArn;",
      "",
      "    public StepFunctionsService(String stateMachineArn) {",
      "        this.stateMachineArn = stateMachineArn;",
      "    }",
      "",
      "    // Demarrer une execution du workflow",
      "    public String startReservationWorkflow(String reservationId, String userId,",
      "                                             String destination, double price) throws Exception {",
      "        Map<String, Object> input = new HashMap<>();",
      "        input.put('reservationId', reservationId);",
      "        input.put('userId', userId);",
      "        input.put('destination', destination);",
      "        input.put('price', price);",
      "        input.put('timestamp', java.time.Instant.now().toString());",
      "",
      "        StartExecutionResponse response = sfnClient.startExecution(",
      "            StartExecutionRequest.builder()",
      "                .stateMachineArn(stateMachineArn)",
      "                .name('reservation-' + reservationId + '-' + System.currentTimeMillis())",
      "                .input(mapper.writeValueAsString(input))",
      "                .build()",
      "        );",
      "",
      "        System.out.println('Workflow demarre: ' + response.executionArn());",
      "        return response.executionArn();",
      "    }",
      "",
      "    // Verifier l'etat d'une execution",
      "    public String getExecutionStatus(String executionArn) {",
      "        DescribeExecutionResponse response = sfnClient.describeExecution(",
      "            DescribeExecutionRequest.builder()",
      "                .executionArn(executionArn)",
      "                .build()",
      "        );",
      "",
      "        System.out.println('Status: ' + response.status());",
      "        System.out.println('Start: ' + response.startDate());",
      "        if (response.stopDate() != null) {",
      "            System.out.println('Stop: ' + response.stopDate());",
      "        }",
      "        return response.statusAsString();",
      "    }",
      "}",
    ]),
    spacer(),

    h2("10.7 Questions de Revision - Module 10"),
    infoBox("Question 1",
      "Votre application de reservation utilise SQS. Un message de paiement continue d'echouer apres 5 tentatives car le service de paiement est down. Que se passe-t-il avec ce message si une DLQ est configuree avec maxReceiveCount=5 ?\nA) Le message est supprime automatiquement\nB) Le message reste indefiniment dans la queue principale\nC) Le message est deplace automatiquement vers la DLQ apres 5 echecs\nD) Le message est envoye au producteur original\nReponse correcte : C - Apres maxReceiveCount (5) tentatives, SQS deplace automatiquement le message vers la Dead Letter Queue. La DLQ permet d'analyser les messages problematiques sans les perdre.",
      LIGHT_ORANGE, ORANGE),
    spacer(),

    h2("10.8 Resume du Module 10"),
    bullet("Microservices : services independants deployes et scales separement"),
    bullet("SQS : queue de messages pour le decouplage asynchrone. Standard (meilleur effort) ou FIFO (ordre strict)"),
    bullet("SNS : pub/sub pour diffuser des evenements a plusieurs abonnes simultanement"),
    bullet("Pattern Fan-Out : SNS Topic -> multiples SQS Queues pour traitement parallele"),
    bullet("Step Functions : orchestration de workflows complexes avec retry, parallel, wait, catch"),
    bullet("DLQ : capture les messages/invocations en echec pour analyse"),
    spacer(),
  ];
}

// MODULE 11: Amazon Cognito
function module11() {
  return [
    pageBreak(),
    h1("MODULE 11 : Accorder l'Acces aux Utilisateurs avec Amazon Cognito"),
    spacer(),
    p("Amazon Cognito est le service d'authentification et d'autorisation d'AWS pour les applications web et mobiles. Il gere l'inscription, la connexion, la verification d'email, le MFA et s'integre avec les fournisseurs d'identite tiers.", { size: 22 }),
    spacer(),

    h2("11.1 Objectifs d'Apprentissage"),
    bullet("Comprendre les deux composants principaux de Cognito : User Pools et Identity Pools"),
    bullet("Configurer un User Pool pour l'authentification"),
    bullet("Implementer le flux OAuth2/OIDC avec Cognito"),
    bullet("Integrer Cognito avec API Gateway comme authorisateur"),
    bullet("Valider et decoder les tokens JWT Cognito en Java"),
    spacer(),

    h2("11.2 User Pools vs Identity Pools"),
    twoColTable(
      ["Composant", "Description et Usage"],
      [
        ["User Pool", "Annuaire d'utilisateurs avec authentification. Gere les comptes (username/password), email verification, MFA. Emet des tokens JWT (ID token, Access token, Refresh token). Pour: authentification de vos utilisateurs."],
        ["Identity Pool (Federated Identities)", "Fournit des credentials AWS temporaires (STS) aux utilisateurs authentifies. Permet aux utilisateurs authentifies via User Pool ou Google/Facebook d'acceder directement aux services AWS (S3, DynamoDB) sans passer par votre API."],
      ]
    ),
    spacer(),
    codeBlock([
      "Flux d'authentification Cognito + API Gateway :",
      "",
      "   Client Mobile/Web",
      "       |",
      "       | 1. POST /login (username + password)",
      "       v",
      "   Cognito User Pool",
      "       |",
      "       | 2. Retourne JWT tokens :",
      "       |    - idToken (info utilisateur, valable 1h)",
      "       |    - accessToken (permissions, valable 1h)",
      "       |    - refreshToken (renouvellement, valable 30j)",
      "       v",
      "   Client stocke les tokens (LocalStorage ou cookies HTTPOnly)",
      "       |",
      "       | 3. GET /api/reservations",
      "       |    Header: Authorization: Bearer <idToken>",
      "       v",
      "   API Gateway",
      "       |",
      "       | 4. Cognito Authorizer valide le JWT",
      "       |    - Verifie la signature avec les cles publiques Cognito",
      "       |    - Verifie l'expiration, le scope, l'audience",
      "       v",
      "   Lambda Handler (avec userId extrait du JWT)",
      "       |",
      "       v",
      "   DynamoDB / Services AWS",
    ]),
    spacer(),

    h2("11.3 Configurer un User Pool Cognito"),
    codeBlock([
      "# Creer un User Pool",
      "aws cognito-idp create-user-pool \\",
      "  --pool-name MonAppUsers \\",
      "  --policies 'PasswordPolicy={MinimumLength=8,RequireUppercase=true,RequireLowercase=true,RequireNumbers=true,RequireSymbols=false}' \\",
      "  --auto-verified-attributes email \\",
      "  --username-attributes email \\",
      "  --mfa-configuration OPTIONAL \\",
      "  --account-recovery-setting 'RecoveryMechanisms=[{Priority=1,Name=verified_email}]' \\",
      "  --region eu-west-1",
      "",
      "# Creer un App Client (pour votre application)",
      "aws cognito-idp create-user-pool-client \\",
      "  --user-pool-id eu-west-1_XXXXXXXXX \\",
      "  --client-name MonAppClient \\",
      "  --generate-secret \\",
      "  --explicit-auth-flows ALLOW_USER_PASSWORD_AUTH ALLOW_REFRESH_TOKEN_AUTH \\",
      "  --access-token-validity 60 \\",
      "  --id-token-validity 60 \\",
      "  --refresh-token-validity 30 \\",
      "  --token-validity-units AccessToken=minutes,IdToken=minutes,RefreshToken=days",
      "",
      "# Ajouter un utilisateur manuellement",
      "aws cognito-idp admin-create-user \\",
      "  --user-pool-id eu-west-1_XXXXXXXXX \\",
      "  --username alice@example.com \\",
      "  --user-attributes Name=email,Value=alice@example.com Name=email_verified,Value=true \\",
      "  --temporary-password 'TempPass123!'",
      "",
      "# S'authentifier (obtenir les tokens)",
      "aws cognito-idp initiate-auth \\",
      "  --auth-flow USER_PASSWORD_AUTH \\",
      "  --client-id XXXXXXXXXX \\",
      "  --auth-parameters USERNAME=alice@example.com,PASSWORD=MonPassword123!",
    ]),
    spacer(),

    h2("11.4 Implementation Java - Authentification Cognito"),
    codeBlock([
      "package com.monapp.auth;",
      "",
      "import software.amazon.awssdk.services.cognitoidentityprovider.CognitoIdentityProviderClient;",
      "import software.amazon.awssdk.services.cognitoidentityprovider.model.*;",
      "import javax.crypto.Mac;",
      "import javax.crypto.spec.SecretKeySpec;",
      "import java.util.*;",
      "",
      "public class CognitoAuthService {",
      "",
      "    private static final CognitoIdentityProviderClient cognitoClient =",
      "        CognitoIdentityProviderClient.create();",
      "",
      "    private final String userPoolId;",
      "    private final String clientId;",
      "    private final String clientSecret;",
      "",
      "    public CognitoAuthService(String userPoolId, String clientId, String clientSecret) {",
      "        this.userPoolId = userPoolId;",
      "        this.clientId = clientId;",
      "        this.clientSecret = clientSecret;",
      "    }",
      "",
      "    // Authentifier un utilisateur et obtenir les tokens JWT",
      "    public AuthenticationResultType login(String email, String password) {",
      "        // Calcul du secret hash (requis si client secret est configure)",
      "        String secretHash = calculateSecretHash(email);",
      "",
      "        try {",
      "            InitiateAuthResponse response = cognitoClient.initiateAuth(",
      "                InitiateAuthRequest.builder()",
      "                    .authFlow(AuthFlowType.USER_PASSWORD_AUTH)",
      "                    .clientId(clientId)",
      "                    .authParameters(Map.of(",
      "                        'USERNAME', email,",
      "                        'PASSWORD', password,",
      "                        'SECRET_HASH', secretHash",
      "                    ))",
      "                    .build()",
      "            );",
      "",
      "            AuthenticationResultType result = response.authenticationResult();",
      "            System.out.println('Connexion reussie!');",
      "            System.out.println('ID Token: ' + result.idToken().substring(0, 50) + '...');",
      "            System.out.println('Expire dans: ' + result.expiresIn() + ' secondes');",
      "            return result;",
      "",
      "        } catch (NotAuthorizedException e) {",
      "            throw new RuntimeException('Email ou mot de passe incorrect');",
      "        } catch (UserNotConfirmedException e) {",
      "            throw new RuntimeException('Email non verifie');",
      "        } catch (UserNotFoundException e) {",
      "            throw new RuntimeException('Utilisateur non trouve');",
      "        }",
      "    }",
      "",
      "    // Inscrire un nouvel utilisateur",
      "    public String register(String email, String password, String firstName) {",
      "        SignUpResponse response = cognitoClient.signUp(",
      "            SignUpRequest.builder()",
      "                .clientId(clientId)",
      "                .secretHash(calculateSecretHash(email))",
      "                .username(email)",
      "                .password(password)",
      "                .userAttributes(",
      "                    AttributeType.builder().name('email').value(email).build(),",
      "                    AttributeType.builder().name('given_name').value(firstName).build()",
      "                )",
      "                .build()",
      "        );",
      "",
      "        if (!response.userConfirmed()) {",
      "            System.out.println('Email de verification envoye a: ' + email);",
      "        }",
      "        return response.userSub(); // UUID de l'utilisateur",
      "    }",
      "",
      "    // Confirmer l'email avec le code recu",
      "    public void confirmEmail(String email, String confirmationCode) {",
      "        cognitoClient.confirmSignUp(",
      "            ConfirmSignUpRequest.builder()",
      "                .clientId(clientId)",
      "                .secretHash(calculateSecretHash(email))",
      "                .username(email)",
      "                .confirmationCode(confirmationCode)",
      "                .build()",
      "        );",
      "        System.out.println('Email confirme pour: ' + email);",
      "    }",
      "",
      "    // Renouveler les tokens avec le refresh token",
      "    public AuthenticationResultType refreshTokens(String email, String refreshToken) {",
      "        InitiateAuthResponse response = cognitoClient.initiateAuth(",
      "            InitiateAuthRequest.builder()",
      "                .authFlow(AuthFlowType.REFRESH_TOKEN_AUTH)",
      "                .clientId(clientId)",
      "                .authParameters(Map.of(",
      "                    'REFRESH_TOKEN', refreshToken,",
      "                    'SECRET_HASH', calculateSecretHash(email)",
      "                ))",
      "                .build()",
      "        );",
      "        return response.authenticationResult();",
      "    }",
      "",
      "    // Calcul du SECRET_HASH (HMAC-SHA256)",
      "    private String calculateSecretHash(String username) {",
      "        try {",
      "            String message = username + clientId;",
      "            Mac mac = Mac.getInstance('HmacSHA256');",
      "            mac.init(new SecretKeySpec(clientSecret.getBytes(), 'HmacSHA256'));",
      "            byte[] hash = mac.doFinal(message.getBytes());",
      "            return Base64.getEncoder().encodeToString(hash);",
      "        } catch (Exception e) {",
      "            throw new RuntimeException('Erreur calcul secret hash', e);",
      "        }",
      "    }",
      "}",
    ]),
    spacer(),

    h2("11.5 Valider un JWT Cognito en Java"),
    codeBlock([
      "package com.monapp.auth;",
      "",
      "import com.auth0.jwk.*;",
      "import com.auth0.jwt.*;",
      "import com.auth0.jwt.algorithms.Algorithm;",
      "import com.auth0.jwt.interfaces.DecodedJWT;",
      "import java.security.interfaces.RSAPublicKey;",
      "",
      "// Validateur de tokens JWT emis par Cognito",
      "public class CognitoJWTValidator {",
      "",
      "    private final JwkProvider jwkProvider;",
      "    private final String issuer;",
      "    private final String clientId;",
      "",
      "    public CognitoJWTValidator(String region, String userPoolId, String clientId) {",
      "        this.issuer = String.format(",
      "            'https://cognito-idp.%s.amazonaws.com/%s', region, userPoolId);",
      "",
      "        // Charger les cles publiques depuis le JWKS endpoint de Cognito",
      "        // URL: https://cognito-idp.{region}.amazonaws.com/{userPoolId}/.well-known/jwks.json",
      "        this.jwkProvider = new JwkProviderBuilder(issuer)",
      "            .cached(10, 24, java.util.concurrent.TimeUnit.HOURS) // Cache les cles 24h",
      "            .build();",
      "        this.clientId = clientId;",
      "    }",
      "",
      "    public DecodedJWT validateToken(String token) throws Exception {",
      "        // 1. Decoder sans verification pour obtenir le kid (key ID)",
      "        DecodedJWT unverified = JWT.decode(token);",
      "",
      "        // 2. Recuperer la cle publique correspondante",
      "        Jwk jwk = jwkProvider.get(unverified.getKeyId());",
      "        RSAPublicKey publicKey = (RSAPublicKey) jwk.getPublicKey();",
      "",
      "        // 3. Verifier la signature et les claims",
      "        Algorithm algorithm = Algorithm.RSA256(publicKey, null);",
      "        JWTVerifier verifier = JWT.require(algorithm)",
      "            .withIssuer(issuer)         // Verifier l'issuer Cognito",
      "            .withAudience(clientId)      // Verifier l'audience (client_id)",
      "            .build();",
      "",
      "        DecodedJWT verified = verifier.verify(token);",
      "",
      "        // 4. Extraire les informations utiles",
      "        String userId = verified.getSubject();",
      "        String email = verified.getClaim('email').asString();",
      "        java.util.List<String> groups = verified.getClaim('cognito:groups').asList(String.class);",
      "",
      "        System.out.println('Token valide pour: ' + email + ' (ID: ' + userId + ')');",
      "        if (groups != null) {",
      "            System.out.println('Groupes: ' + groups);",
      "        }",
      "",
      "        return verified;",
      "    }",
      "}",
    ]),
    spacer(),

    h2("11.6 Integrer Cognito avec API Gateway"),
    codeBlock([
      "# Creer un Cognito Authorizer dans API Gateway",
      "aws apigateway create-authorizer \\",
      "  --rest-api-id $API_ID \\",
      "  --name CognitoAuthorizer \\",
      "  --type COGNITO_USER_POOLS \\",
      "  --identity-source 'method.request.header.Authorization' \\",
      "  --provider-arns 'arn:aws:cognito-idp:eu-west-1:123456789012:userpool/eu-west-1_XXXXXXXXX'",
      "",
      "# Associer l'authorizer a une methode",
      "aws apigateway update-method \\",
      "  --rest-api-id $API_ID \\",
      "  --resource-id $RESOURCE_ID \\",
      "  --http-method GET \\",
      "  --patch-operations \\",
      "    'op=replace,path=/authorizationType,value=COGNITO_USER_POOLS' \\",
      "    'op=replace,path=/authorizerId,value='$AUTHORIZER_ID",
      "",
      "# Dans la Lambda, acceder aux informations Cognito du token",
      "public APIGatewayProxyResponseEvent handleRequest(",
      "        APIGatewayProxyRequestEvent event, Context context) {",
      "    // Les claims du token sont disponibles dans requestContext",
      "    var claims = event.getRequestContext().getAuthorizer();",
      "    String userId = (String) claims.get('sub');       // UUID Cognito",
      "    String email = (String) claims.get('email');",
      "    String username = (String) claims.get('cognito:username');",
      "    // ...",
      "}",
    ]),
    spacer(),

    h2("11.7 Questions de Revision - Module 11"),
    infoBox("Question 1",
      "Un client mobile s'authentifie avec Cognito et recoit un ID token, access token et refresh token. L'ID token expire apres 1 heure. Que doit faire l'application pour maintenir la session sans redemander les credentials ?\nA) Redemander username/password apres 1 heure\nB) Utiliser le refresh token pour obtenir de nouveaux access et ID tokens\nC) Augmenter la duree du token dans la configuration Cognito\nD) Cacher l'ID token indefiniment dans localStorage\nReponse correcte : B - Le refresh token (valable 30 jours par defaut, configurable jusqu'a 10 ans) permet d'obtenir de nouveaux ID token et access token via le flux REFRESH_TOKEN_AUTH sans redemander les credentials. C'est le flux standard OAuth2.",
      LIGHT_ORANGE, ORANGE),
    spacer(),

    h2("11.8 Resume du Module 11"),
    bullet("Cognito User Pools : annuaire d'utilisateurs, authentification, JWT tokens"),
    bullet("Cognito Identity Pools : credentials AWS temporaires pour acces direct aux services"),
    bullet("JWT tokens Cognito : ID token (infos user), Access token (permissions), Refresh token (renouvellement)"),
    bullet("Valider les JWT avec les cles publiques JWKS de Cognito"),
    bullet("API Gateway Cognito Authorizer : validation automatique des JWT sans code custom"),
    bullet("SECRET_HASH requis pour les App Clients avec un client secret"),
    spacer(),
  ];
}

// GENERER PART 4
async function generatePart4() {
  console.log('Generation Part 4 (Modules 9-11)...');
  const content = [
    ...module9(),
    ...module10(),
    ...module11(),
  ];

  const doc = new Document({
    numbering: {
      config: [
        { reference: "bullets", levels: [{ level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } }, run: { font: "Symbol" } } }] },
        { reference: "numbers", levels: [{ level: 0, format: LevelFormat.DECIMAL, text: "%1.", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },
      ]
    },
    styles: {
      default: { document: { run: { font: "Arial", size: 22 } } },
      paragraphStyles: [
        { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 40, bold: true, font: "Arial", color: BLUE }, paragraph: { spacing: { before: 480, after: 240 }, outlineLevel: 0, border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: ORANGE } } } },
        { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 32, bold: true, font: "Arial", color: BLUE }, paragraph: { spacing: { before: 320, after: 160 }, outlineLevel: 1 } },
        { id: "Heading3", name: "Heading 3", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 26, bold: true, font: "Arial", color: DARK_GRAY }, paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 2 } },
      ]
    },
    sections: [{
      properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
      headers: { default: new Header({ children: [new Paragraph({ border: { bottom: { style: BorderStyle.SINGLE, size: 2, color: BLUE } }, children: [new TextRun({ text: "Cours AWS pour Developpeurs Java - API Gateway | Microservices | Cognito", font: "Arial", size: 18, color: BLUE })] })] }) },
      footers: { default: new Footer({ children: [new Paragraph({ border: { top: { style: BorderStyle.SINGLE, size: 2, color: BLUE } }, children: [new TextRun({ text: "AWS SDK for Java v2 - 2025  Page ", font: "Arial", size: 18, color: "888888" }), new TextRun({ children: [PageNumber.CURRENT], font: "Arial", size: 18, color: BLUE })] })] }) },
      children: content
    }]
  });

  const buffer = await Packer.toBuffer(doc);
  const outputPath = '/Users/user/Desktop/travel-agency/backend/.claude/worktrees/naughty-jepsen-0d5f95/cours_aws_java_part4.docx';
  fs.writeFileSync(outputPath, buffer);
  console.log('Part 4 generee: ' + outputPath + ' - ' + Math.round(buffer.length/1024) + ' KB');
}

generatePart4().catch(console.error);
