const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
        HeadingLevel, AlignmentType, BorderStyle, WidthType, ShadingType,
        PageNumber, Header, Footer, PageBreak, LevelFormat } = require('docx');
const fs = require('fs');

const CONTENT_WIDTH = 9360;
const ORANGE = "E8630A";
const BLUE = "1B4F8A";
const LIGHT_BLUE = "D6E4F0";
const LIGHT_ORANGE = "FEF0E6";
const LIGHT_GREEN = "E8F8E8";
const LIGHT_RED = "FDECEA";
const LIGHT_GRAY = "F5F5F5";
const DARK_GRAY = "333333";

const border = { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" };
const borders = { top: border, bottom: border, left: border, right: border };
const noBorders = { top: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" }, bottom: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" }, left: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" }, right: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" } };

function h1(t) { return new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: t, bold: true, color: BLUE })] }); }
function h2(t) { return new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text: t, bold: true, color: BLUE })] }); }
function h3(t) { return new Paragraph({ heading: HeadingLevel.HEADING_3, children: [new TextRun({ text: t, bold: true })] }); }
function p(t, opts = {}) { return new Paragraph({ spacing: { after: 160 }, children: [new TextRun({ text: t, ...opts })] }); }
function pageBreak() { return new Paragraph({ children: [new PageBreak()] }); }
function spacer() { return new Paragraph({ spacing: { after: 200 }, children: [new TextRun("")] }); }
function bullet(t, bold = false) { return new Paragraph({ numbering: { reference: "bullets", level: 0 }, spacing: { after: 80 }, children: [new TextRun({ text: t, bold })] }); }
function numbered(t) { return new Paragraph({ numbering: { reference: "numbers", level: 0 }, spacing: { after: 80 }, children: [new TextRun({ text: t })] }); }
function codeBlock(lines) {
  return new Table({ width: { size: CONTENT_WIDTH - 240, type: WidthType.DXA }, columnWidths: [CONTENT_WIDTH - 240], borders: { top: { style: BorderStyle.SINGLE, size: 2, color: "555555" }, bottom: { style: BorderStyle.SINGLE, size: 2, color: "555555" }, left: { style: BorderStyle.SINGLE, size: 2, color: "555555" }, right: { style: BorderStyle.SINGLE, size: 2, color: "555555" } }, rows: lines.map(line => new TableRow({ children: [new TableCell({ borders: noBorders, width: { size: CONTENT_WIDTH - 240, type: WidthType.DXA }, shading: { fill: "1E1E1E", type: ShadingType.CLEAR }, margins: { top: 0, bottom: 0, left: 200, right: 200 }, children: [new Paragraph({ spacing: { after: 0, before: 0, line: 276 }, children: [new TextRun({ text: line || " ", font: "Courier New", size: 18, color: "D4D4D4" })] })] })] })) });
}
function infoBox(title, text, fill = LIGHT_BLUE, titleColor = BLUE) {
  return new Table({ width: { size: CONTENT_WIDTH, type: WidthType.DXA }, columnWidths: [CONTENT_WIDTH], rows: [new TableRow({ children: [new TableCell({ borders, width: { size: CONTENT_WIDTH, type: WidthType.DXA }, shading: { fill, type: ShadingType.CLEAR }, margins: { top: 120, bottom: 120, left: 200, right: 200 }, children: [new Paragraph({ spacing: { after: 60 }, children: [new TextRun({ text: title, bold: true, color: titleColor, size: 22 })] }), new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text, size: 20 })] })] })] })] });
}
function twoColTable(headers, rows) {
  const w0 = 3000, w1 = CONTENT_WIDTH - 3000;
  return new Table({ width: { size: CONTENT_WIDTH, type: WidthType.DXA }, columnWidths: [w0, w1], rows: [new TableRow({ children: headers.map((h, i) => new TableCell({ borders, width: { size: i === 0 ? w0 : w1, type: WidthType.DXA }, shading: { fill: BLUE, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text: h, bold: true, color: "FFFFFF", size: 20 })] })] })) }), ...rows.map((row, ri) => new TableRow({ children: row.map((cell, ci) => new TableCell({ borders, width: { size: ci === 0 ? w0 : w1, type: WidthType.DXA }, shading: { fill: ri % 2 === 0 ? "FFFFFF" : LIGHT_GRAY, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text: cell, size: 20 })] })] })) }))] });
}
function multiColTable(headers, colWidths, rows) {
  return new Table({ width: { size: colWidths.reduce((a, b) => a + b, 0), type: WidthType.DXA }, columnWidths: colWidths, rows: [new TableRow({ children: headers.map((h, i) => new TableCell({ borders, width: { size: colWidths[i], type: WidthType.DXA }, shading: { fill: BLUE, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text: h, bold: true, color: "FFFFFF", size: 20 })] })] })) }), ...rows.map((row, ri) => new TableRow({ children: row.map((cell, ci) => new TableCell({ borders, width: { size: colWidths[ci], type: WidthType.DXA }, shading: { fill: ri % 2 === 0 ? "FFFFFF" : LIGHT_GRAY, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text: cell, size: 20 })] })] })) }))] });
}

// MODULE 12: AWS SAM & DevOps
function module12() {
  return [
    pageBreak(),
    h1("MODULE 12 : Deploiement avec AWS SAM et DevOps"),
    spacer(),
    p("AWS Serverless Application Model (SAM) est un framework open-source pour construire des applications serverless sur AWS. Il etend CloudFormation avec des types de ressources simplifies pour Lambda, API Gateway, DynamoDB et d'autres services serverless.", { size: 22 }),
    spacer(),

    h2("12.1 Objectifs d'Apprentissage"),
    bullet("Comprendre la methodologie DevOps et ses pratiques CI/CD"),
    bullet("Installer et configurer AWS SAM CLI"),
    bullet("Ecrire des templates SAM pour deployer des applications serverless"),
    bullet("Implanter les strategies de deploiement : all-at-once, canary, linear"),
    bullet("Configurer une pipeline CI/CD avec AWS CodePipeline"),
    spacer(),

    h2("12.2 DevOps et CI/CD sur AWS"),
    p("DevOps est une methodologie qui rapproche les equipes de developpement et d'operations pour accelerer la livraison de logiciels de qualite."),
    spacer(),
    twoColTable(
      ["Service AWS DevOps", "Role dans la Pipeline CI/CD"],
      [
        ["AWS CodeCommit", "Repository Git manage. Alternative a GitHub/GitLab hebergee sur AWS. Integre avec IAM."],
        ["AWS CodeBuild", "Service de build gere. Execute les tests, compile le code, cree les artefacts. Docker-based."],
        ["AWS CodeDeploy", "Automatise le deploiement sur EC2, ECS, Lambda. Supporte les strategies de deploiement avancees."],
        ["AWS CodePipeline", "Orchestration de la pipeline CI/CD complete. Integre CodeCommit, CodeBuild, CodeDeploy."],
        ["AWS SAM CLI", "Outil CLI pour developper, tester localement et deployer des apps serverless."],
        ["AWS CDK", "Infrastructure as Code en TypeScript, Python, Java. Genere CloudFormation."],
      ]
    ),
    spacer(),
    codeBlock([
      "Pipeline CI/CD typique pour une application serverless Java :",
      "",
      "Code Change (push to main)",
      "        |",
      "        v",
      "AWS CodeCommit / GitHub",
      "        |",
      "        | Webhook / Event",
      "        v",
      "AWS CodePipeline (orchestration)",
      "        |",
      "        v",
      "Stage 1: Source",
      "  - Recuperer le code source",
      "        |",
      "        v",
      "Stage 2: Build (CodeBuild)",
      "  - mvn clean package -DskipTests",
      "  - Creer le JAR shaded",
      "  - sam build",
      "        |",
      "        v",
      "Stage 3: Test (CodeBuild)",
      "  - mvn test (tests unitaires)",
      "  - sam local invoke (tests locaux)",
      "  - Tests d'integration",
      "        |",
      "        v",
      "Stage 4: Deploy Staging (SAM/CodeDeploy)",
      "  - sam deploy --stack-name staging",
      "  - Tests de smoke",
      "        |",
      "        v",
      "Stage 5: Approval (manuel optionnel)",
      "  - Review du deploiement staging",
      "        |",
      "        v",
      "Stage 6: Deploy Production (SAM/CodeDeploy)",
      "  - sam deploy --stack-name production",
      "  - Strategie Canary 10% -> 100%",
    ]),
    spacer(),

    h2("12.3 AWS SAM - Installation et Configuration"),
    codeBlock([
      "# Installation de SAM CLI",
      "# macOS",
      "brew tap aws/tap",
      "brew install aws-sam-cli",
      "",
      "# Verification",
      "sam --version",
      "# SAM CLI, version 1.x.x",
      "",
      "# Linux",
      "pip install aws-sam-cli",
      "",
      "# Initialiser un nouveau projet SAM Java",
      "sam init \\",
      "  --runtime java17 \\",
      "  --dependency-manager maven \\",
      "  --app-template hello-world \\",
      "  --name mon-app-serverless",
      "",
      "# Structure generee :",
      "mon-app-serverless/",
      "├── template.yaml          # Template SAM principal",
      "├── events/                # Exemples d'evenements pour les tests",
      "│   └── event.json",
      "├── HelloWorldFunction/    # Code de la fonction Lambda",
      "│   ├── src/",
      "│   │   └── main/java/helloworld/",
      "│   │       └── App.java",
      "│   └── pom.xml",
      "└── samconfig.toml         # Configuration du deploiement",
    ]),
    spacer(),

    h2("12.4 Template SAM - Syntaxe Complete"),
    codeBlock([
      "# template.yaml - Template SAM complet pour une app de reservation",
      "AWSTemplateFormatVersion: '2010-09-09'",
      "Transform: AWS::Serverless-2016-10-31",
      "",
      "Description: Application serverless de gestion des reservations",
      "",
      "# Parametres configurables au deploiement",
      "Parameters:",
      "  Environment:",
      "    Type: String",
      "    Default: dev",
      "    AllowedValues: [dev, staging, prod]",
      "  TableName:",
      "    Type: String",
      "    Default: reservations",
      "",
      "# Variables globales partagees entre toutes les fonctions",
      "Globals:",
      "  Function:",
      "    Runtime: java17",
      "    MemorySize: 512",
      "    Timeout: 30",
      "    Environment:",
      "      Variables:",
      "        RESERVATIONS_TABLE: !Sub '${Environment}-${TableName}'",
      "        POWERTOOLS_SERVICE_NAME: reservation-service",
      "    Tracing: Active  # Active X-Ray tracing",
      "    Layers:",
      "      - !Sub 'arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsJava:3'",
      "",
      "Resources:",
      "",
      "  # === TABLE DYNAMODB ===",
      "  ReservationsTable:",
      "    Type: AWS::DynamoDB::Table",
      "    DeletionPolicy: Retain  # Ne pas supprimer lors de sam delete",
      "    Properties:",
      "      TableName: !Sub '${Environment}-${TableName}'",
      "      BillingMode: PAY_PER_REQUEST",
      "      AttributeDefinitions:",
      "        - AttributeName: userId",
      "          AttributeType: S",
      "        - AttributeName: createdAt",
      "          AttributeType: S",
      "      KeySchema:",
      "        - AttributeName: userId",
      "          KeyType: HASH",
      "        - AttributeName: createdAt",
      "          KeyType: RANGE",
      "      PointInTimeRecoverySpecification:",
      "        PointInTimeRecoveryEnabled: true",
      "",
      "  # === API GATEWAY ===",
      "  ReservationApi:",
      "    Type: AWS::Serverless::Api",
      "    Properties:",
      "      StageName: !Ref Environment",
      "      Cors:",
      "        AllowMethods: \"'GET,POST,PUT,DELETE,OPTIONS'\"",
      "        AllowHeaders: \"'Content-Type,Authorization'\"",
      "        AllowOrigin: \"'*'\"",
      "      Auth:",
      "        DefaultAuthorizer: CognitoAuthorizer",
      "        Authorizers:",
      "          CognitoAuthorizer:",
      "            UserPoolArn: !GetAtt UserPool.Arn",
      "",
      "  # === FONCTIONS LAMBDA ===",
      "  GetReservationsFunction:",
      "    Type: AWS::Serverless::Function",
      "    Properties:",
      "      FunctionName: !Sub '${Environment}-get-reservations'",
      "      CodeUri: ReservationService/",
      "      Handler: com.monapp.handler.GetReservationsHandler::handleRequest",
      "      Policies:",
      "        - DynamoDBReadPolicy:",
      "            TableName: !Ref ReservationsTable",
      "      Events:",
      "        GetReservations:",
      "          Type: Api",
      "          Properties:",
      "            RestApiId: !Ref ReservationApi",
      "            Path: /reservations/{userId}",
      "            Method: get",
      "      # Configuration du deploiement avec CodeDeploy",
      "      DeploymentPreference:",
      "        Type: Canary10Percent10Minutes  # 10% du trafic, puis 100% apres 10 min",
      "        Alarms:",
      "          - !Ref GetReservationsErrorAlarm",
      "",
      "  CreateReservationFunction:",
      "    Type: AWS::Serverless::Function",
      "    Properties:",
      "      FunctionName: !Sub '${Environment}-create-reservation'",
      "      CodeUri: ReservationService/",
      "      Handler: com.monapp.handler.CreateReservationHandler::handleRequest",
      "      Policies:",
      "        - DynamoDBWritePolicy:",
      "            TableName: !Ref ReservationsTable",
      "        - SNSPublishMessagePolicy:",
      "            TopicName: !GetAtt ReservationEventsTopic.TopicName",
      "      Events:",
      "        CreateReservation:",
      "          Type: Api",
      "          Properties:",
      "            RestApiId: !Ref ReservationApi",
      "            Path: /reservations",
      "            Method: post",
      "",
      "  # === SNS TOPIC ===",
      "  ReservationEventsTopic:",
      "    Type: AWS::SNS::Topic",
      "    Properties:",
      "      TopicName: !Sub '${Environment}-reservation-events'",
      "",
      "  # === COGNITO USER POOL ===",
      "  UserPool:",
      "    Type: AWS::Cognito::UserPool",
      "    Properties:",
      "      UserPoolName: !Sub '${Environment}-users'",
      "      AutoVerifiedAttributes: [email]",
      "      UsernameAttributes: [email]",
      "      Policies:",
      "        PasswordPolicy:",
      "          MinimumLength: 8",
      "          RequireUppercase: true",
      "          RequireLowercase: true",
      "          RequireNumbers: true",
      "",
      "  # === CLOUDWATCH ALARM ===",
      "  GetReservationsErrorAlarm:",
      "    Type: AWS::CloudWatch::Alarm",
      "    Properties:",
      "      AlarmName: !Sub '${Environment}-get-reservations-errors'",
      "      MetricName: Errors",
      "      Namespace: AWS/Lambda",
      "      Dimensions:",
      "        - Name: FunctionName",
      "          Value: !Ref GetReservationsFunction",
      "      Statistic: Sum",
      "      Period: 60",
      "      EvaluationPeriods: 1",
      "      Threshold: 5",
      "      ComparisonOperator: GreaterThanThreshold",
      "      TreatMissingData: notBreaching",
      "",
      "# === OUTPUTS ===",
      "Outputs:",
      "  ApiEndpoint:",
      "    Description: URL de l'API Gateway",
      "    Value: !Sub 'https://${ReservationApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'",
      "    Export:",
      "      Name: !Sub '${Environment}-api-endpoint'",
      "  TableArn:",
      "    Description: ARN de la table DynamoDB",
      "    Value: !GetAtt ReservationsTable.Arn",
    ]),
    spacer(),

    h2("12.5 Commandes SAM CLI Essentielles"),
    codeBlock([
      "# === BUILD ===",
      "# Compile le code Java et prepare le package de deploiement",
      "sam build",
      "# Equivalent a : mvn clean package + organisation pour Lambda",
      "",
      "# Build avec un conteneur Docker (reproduit l'environnement Lambda exactement)",
      "sam build --use-container",
      "",
      "# === TEST LOCAL ===",
      "# Invoquer une fonction localement",
      "sam local invoke GetReservationsFunction \\",
      "  --event events/get-reservation.json",
      "",
      "# Lancer l'API localement (necessite Docker)",
      "sam local start-api --port 3000",
      "# Tester : curl http://localhost:3000/reservations/alice",
      "",
      "# Generer un evenement de test",
      "sam local generate-event apigateway aws-proxy \\",
      "  --method GET \\",
      "  --path /reservations/alice \\",
      "  > events/get-reservation.json",
      "",
      "# === DEPLOIEMENT ===",
      "# Premier deploiement interactif (cree samconfig.toml)",
      "sam deploy --guided",
      "",
      "# Deploiement avec les parametres sauvegardes",
      "sam deploy",
      "",
      "# Deploiement avec override de parametres",
      "sam deploy \\",
      "  --stack-name prod-reservation-app \\",
      "  --parameter-overrides Environment=prod TableName=reservations \\",
      "  --no-confirm-changeset \\",
      "  --region eu-west-1",
      "",
      "# Voir les changements avant deploiement (changeset)",
      "sam deploy --no-execute-changeset",
      "",
      "# === MONITORING ===",
      "# Suivre les logs Lambda en temps reel",
      "sam logs -n GetReservationsFunction --stack-name prod-reservation-app --tail",
      "",
      "# === SUPPRESSION ===",
      "sam delete --stack-name dev-reservation-app",
    ]),
    spacer(),

    h2("12.6 samconfig.toml - Configuration du Deploiement"),
    codeBlock([
      "# samconfig.toml - Configuration persistante du deploiement",
      "version = 0.1",
      "",
      "[default]",
      "[default.global.parameters]",
      "stack_name = 'dev-reservation-app'",
      "",
      "[default.build.parameters]",
      "cached = true",
      "parallel = true",
      "",
      "[default.validate.parameters]",
      "lint = true",
      "",
      "[default.deploy.parameters]",
      "capabilities = 'CAPABILITY_IAM CAPABILITY_AUTO_EXPAND'",
      "confirm_changeset = true",
      "resolve_s3 = true",
      "s3_prefix = 'dev-reservation-app'",
      "region = 'eu-west-1'",
      "parameter_overrides = 'Environment=dev TableName=reservations'",
      "",
      "[prod]",
      "[prod.deploy.parameters]",
      "stack_name = 'prod-reservation-app'",
      "capabilities = 'CAPABILITY_IAM CAPABILITY_AUTO_EXPAND'",
      "confirm_changeset = false",
      "region = 'eu-west-1'",
      "parameter_overrides = 'Environment=prod TableName=reservations'",
      "",
      "# Deploiement en production : sam deploy --config-env prod",
    ]),
    spacer(),

    h2("12.7 Strategies de Deploiement Lambda"),
    p("CodeDeploy et SAM supportent plusieurs strategies de deploiement pour minimiser le risque lors des mises en production :"),
    spacer(),
    twoColTable(
      ["Strategie", "Description"],
      [
        ["AllAtOnce", "Tout le trafic bascule immediatement vers la nouvelle version. Risque maximum, rollback manuel."],
        ["Canary10Percent5Minutes", "10% du trafic vers la nouvelle version pendant 5 minutes, puis 100%. Permet la detection precoce."],
        ["Canary10Percent30Minutes", "10% du trafic pendant 30 minutes. Plus conservateur, plus de temps pour detecter les problemes."],
        ["Linear10PercentEvery1Minute", "Augmentation lineaire de 10% toutes les minutes (10%, 20%, 30%... 100%). Tres progressif."],
        ["Linear10PercentEvery10Minutes", "Augmentation lineaire de 10% toutes les 10 minutes. Pour les deploiements critiques."],
      ]
    ),
    spacer(),
    codeBlock([
      "# Configuration du deploiement Canary avec alarmes de rollback",
      "# Dans template.yaml :",
      "GetReservationsFunction:",
      "  Type: AWS::Serverless::Function",
      "  Properties:",
      "    AutoPublishAlias: live  # Cree automatiquement un alias 'live'",
      "    DeploymentPreference:",
      "      Type: Canary10Percent10Minutes",
      "      # Si l'alarme se declenche -> rollback automatique",
      "      Alarms:",
      "        - !Ref ErrorRateAlarm",
      "        - !Ref LatencyAlarm",
      "      # Hooks Lambda optionnels",
      "      Hooks:",
      "        PreTraffic: !Ref PreTrafficHook   # Avant le basculement du trafic",
      "        PostTraffic: !Ref PostTrafficHook  # Apres le basculement complet",
      "",
      "# Alarme qui declenchera le rollback si le taux d'erreur > 5%",
      "ErrorRateAlarm:",
      "  Type: AWS::CloudWatch::Alarm",
      "  Properties:",
      "    MetricName: Errors",
      "    Namespace: AWS/Lambda",
      "    Dimensions:",
      "      - Name: FunctionName",
      "        Value: !Ref GetReservationsFunction",
      "    Statistic: Sum",
      "    Period: 60",
      "    EvaluationPeriods: 1",
      "    Threshold: 5",
      "    ComparisonOperator: GreaterThanThreshold",
    ]),
    spacer(),

    h2("12.8 Questions de Revision - Module 12"),
    infoBox("Question 1",
      "Vous deployez une nouvelle version d'une fonction Lambda en production. Pour minimiser les risques, vous voulez d'abord exposer la nouvelle version a 10% des utilisateurs pendant 5 minutes et basculer automatiquement si aucune alarme ne se declenche. Quelle strategie de deploiement choisissez-vous ?\nA) AllAtOnce\nB) Linear10PercentEvery1Minute\nC) Canary10Percent5Minutes\nD) BlueGreen\nReponse correcte : C - Canary10Percent5Minutes envoie exactement 10% du trafic vers la nouvelle version pendant 5 minutes. Si les alarmes CloudWatch configurees ne se declenchent pas, CodeDeploy bascule automatiquement 100% du trafic. Rollback automatique si une alarme se declenche.",
      LIGHT_ORANGE, ORANGE),
    spacer(),

    h2("12.9 Resume du Module 12"),
    bullet("SAM etend CloudFormation avec des types serverless simplifies (Function, Api, Table)"),
    bullet("sam build compile le code Java et prepare le package Lambda"),
    bullet("sam local invoke permet de tester les fonctions sans deploiement"),
    bullet("sam deploy deploie sur AWS avec gestion des changesets CloudFormation"),
    bullet("Strategies de deploiement : AllAtOnce, Canary (10%/5min, etc.), Linear"),
    bullet("CodeDeploy gere le basculement de trafic avec rollback automatique sur alarme"),
    spacer(),
  ];
}

// MODULE 13: Observabilite CloudWatch & X-Ray
function module13() {
  return [
    pageBreak(),
    h1("MODULE 13 : Observer votre Application - CloudWatch et X-Ray"),
    spacer(),
    p("L'observabilite est la capacite a comprendre l'etat interne d'un systeme a partir de ses sorties externes. Elle repose sur trois piliers : les metriques (CloudWatch), les logs (CloudWatch Logs) et les traces distribuees (AWS X-Ray).", { size: 22 }),
    spacer(),

    h2("13.1 Objectifs d'Apprentissage"),
    bullet("Differentier surveillance (monitoring) et observabilite"),
    bullet("Configurer CloudWatch pour les metriques et les alarmes"),
    bullet("Analyser les logs avec CloudWatch Logs Insights"),
    bullet("Instrumenter le code Java avec AWS X-Ray"),
    bullet("Creer des cartes de service X-Ray pour visualiser les architectures distribuees"),
    spacer(),

    h2("13.2 Monitoring vs Observabilite"),
    twoColTable(
      ["Concept", "Description"],
      [
        ["Monitoring (Surveillance)", "Surveiller des metriques predefinies connues. Repond a 'Est-ce que le systeme fonctionne ?' Alertes sur des seuils fixes. Approche reactive."],
        ["Observabilite", "Comprendre l'etat interne d'un systeme complexe a partir de ses sorties. Repond a 'POURQUOI le systeme ne fonctionne pas ?' Approche investigative. Metriques + Logs + Traces."],
        ["Metriques (CloudWatch)", "Mesures numeriques dans le temps : CPU, latence, nombre d'erreurs, throughput. Ideal pour les alertes."],
        ["Logs (CloudWatch Logs)", "Enregistrements textuels d'evenements. Contexte detaille. Utile pour le debugging."],
        ["Traces (X-Ray)", "Suivi d'une requete a travers tous les services distribues. Visualise les goulots d'etranglement."],
      ]
    ),
    spacer(),

    h2("13.3 Amazon CloudWatch"),
    h3("13.3.1 Metriques CloudWatch"),
    p("CloudWatch collecte automatiquement des metriques pour tous les services AWS. Vous pouvez aussi creer des metriques personnalisees."),
    spacer(),
    codeBlock([
      "package com.monapp.monitoring;",
      "",
      "import software.amazon.awssdk.services.cloudwatch.CloudWatchClient;",
      "import software.amazon.awssdk.services.cloudwatch.model.*;",
      "import java.time.Instant;",
      "",
      "public class CloudWatchMetrics {",
      "",
      "    private static final CloudWatchClient cloudWatch = CloudWatchClient.create();",
      "",
      "    // Publier une metrique personnalisee",
      "    public void recordReservationCreated(String destination, double price) {",
      "        cloudWatch.putMetricData(PutMetricDataRequest.builder()",
      "            .namespace('MonApp/Reservations')",
      "            .metricData(",
      "                // Metrique 1: Nombre de reservations",
      "                MetricDatum.builder()",
      "                    .metricName('ReservationsCreated')",
      "                    .value(1.0)",
      "                    .unit(StandardUnit.COUNT)",
      "                    .timestamp(Instant.now())",
      "                    .dimensions(",
      "                        Dimension.builder()",
      "                            .name('Destination')",
      "                            .value(destination)",
      "                            .build()",
      "                    )",
      "                    .build(),",
      "",
      "                // Metrique 2: Valeur de la reservation",
      "                MetricDatum.builder()",
      "                    .metricName('ReservationValue')",
      "                    .value(price)",
      "                    .unit(StandardUnit.NONE) // ou 'Bytes', 'Milliseconds', etc.",
      "                    .timestamp(Instant.now())",
      "                    .dimensions(",
      "                        Dimension.builder()",
      "                            .name('Destination')",
      "                            .value(destination)",
      "                            .build()",
      "                    )",
      "                    .build()",
      "            )",
      "            .build()",
      "        );",
      "    }",
      "",
      "    // Enregistrer une latence",
      "    public void recordLatency(String operation, long latencyMs) {",
      "        cloudWatch.putMetricData(PutMetricDataRequest.builder()",
      "            .namespace('MonApp/Performance')",
      "            .metricData(",
      "                MetricDatum.builder()",
      "                    .metricName('OperationLatency')",
      "                    .value((double) latencyMs)",
      "                    .unit(StandardUnit.MILLISECONDS)",
      "                    .dimensions(",
      "                        Dimension.builder()",
      "                            .name('Operation')",
      "                            .value(operation)",
      "                            .build()",
      "                    )",
      "                    .build()",
      "            )",
      "            .build()",
      "        );",
      "    }",
      "}",
    ]),
    spacer(),
    h3("13.3.2 Alarmes CloudWatch"),
    codeBlock([
      "// Creer une alarme CloudWatch via SDK Java",
      "import software.amazon.awssdk.services.cloudwatch.model.*;",
      "",
      "public void createErrorRateAlarm(CloudWatchClient cloudWatch,",
      "                                   String functionName, String snsTopicArn) {",
      "    cloudWatch.putMetricAlarm(PutMetricAlarmRequest.builder()",
      "        .alarmName('Lambda-' + functionName + '-ErrorRate')",
      "        .alarmDescription('Alarme si le taux d erreur Lambda depasse 5%')",
      "",
      "        // Metrique Lambda Errors (nombre d'erreurs)",
      "        .metricName('Errors')",
      "        .namespace('AWS/Lambda')",
      "        .dimensions(",
      "            Dimension.builder()",
      "                .name('FunctionName')",
      "                .value(functionName)",
      "                .build()",
      "        )",
      "",
      "        // Configuration de l'alarme",
      "        .statistic(Statistic.SUM)",
      "        .period(60)                 // Periode d'evaluation: 60 secondes",
      "        .evaluationPeriods(3)        // Evaluer sur 3 periodes consecutives",
      "        .threshold(5.0)             // Seuil: 5 erreurs",
      "        .comparisonOperator(ComparisonOperator.GREATER_THAN_THRESHOLD)",
      "        .treatMissingData(TreatMissingData.NOT_BREACHING)",
      "",
      "        // Actions : envoyer une notification SNS",
      "        .alarmActions(snsTopicArn)  // Quand l'alarme se declenche",
      "        .okActions(snsTopicArn)     // Quand l'alarme revient a OK",
      "",
      "        .build()",
      "    );",
      "    System.out.println('Alarme creee: Lambda-' + functionName + '-ErrorRate');",
      "}",
    ]),
    spacer(),

    h2("13.4 CloudWatch Logs Insights"),
    p("CloudWatch Logs Insights permet d'analyser les logs avec un langage de requete SQL-like pour trouver rapidement les problemes."),
    spacer(),
    codeBlock([
      "# Requetes CloudWatch Logs Insights utiles",
      "",
      "# 1. Trouver les erreurs Lambda des 24 dernieres heures",
      "fields @timestamp, @message",
      "| filter @message like /ERROR/",
      "| sort @timestamp desc",
      "| limit 50",
      "",
      "# 2. Analyser les latences des invocations Lambda",
      "filter @type = 'REPORT'",
      "| stats avg(@duration), max(@duration), min(@duration),",
      "        percentile(@duration, 95) as p95,",
      "        percentile(@duration, 99) as p99",
      "| sort p99 desc",
      "",
      "# 3. Trouver les cold starts Lambda (Init Duration present)",
      "filter @type = 'REPORT' and @initDuration > 0",
      "| stats count() as coldStarts, avg(@initDuration) as avgInitMs",
      "| sort coldStarts desc",
      "",
      "# 4. Compter les erreurs par type dans votre code",
      "fields @timestamp, @message",
      "| parse @message '[ERROR] *' as errorType",
      "| stats count() as errorCount by errorType",
      "| sort errorCount desc",
      "",
      "# 5. Identifier les utilisateurs ayant le plus d'erreurs",
      "filter @message like /userId/",
      "| parse @message '\"userId\":\"*\"' as userId",
      "| filter @message like /ERROR/",
      "| stats count() as errors by userId",
      "| sort errors desc",
      "| limit 10",
    ]),
    spacer(),

    h2("13.5 AWS X-Ray - Tracing Distribue"),
    p("AWS X-Ray permet de tracer le parcours d'une requete a travers tous les services de votre architecture distribuee, identifiant les goulots d'etranglement et les erreurs."),
    spacer(),
    h3("13.5.1 Concepts X-Ray"),
    twoColTable(
      ["Concept X-Ray", "Description"],
      [
        ["Trace", "Enregistrement complet du parcours d'une requete end-to-end. Identifie par un Trace ID unique."],
        ["Segment", "Unites de travail represantant un service. Chaque service cree un segment avec les timing, erreurs, etc."],
        ["Sous-segment (Subsegment)", "Parties d'un segment : appel HTTP externe, requete DynamoDB, appel Lambda. Details fins."],
        ["Annotations", "Paires cle-valeur indexees. Permettent de filtrer les traces dans la console X-Ray."],
        ["Metadata", "Paires cle-valeur non indexees. Informations additionnelles pour le debugging."],
        ["Sampling", "X-Ray n'enregistre pas 100% des requetes (cout). Par defaut : premiere requete/sec + 5%."],
        ["Service Map", "Carte visuelle automatique de tous les services et leurs dependances avec metriques."],
      ]
    ),
    spacer(),
    h3("13.5.2 Instrumenter une Fonction Lambda Java avec X-Ray"),
    codeBlock([
      "<!-- Ajouter X-Ray au pom.xml -->",
      "<dependency>",
      "  <groupId>com.amazonaws</groupId>",
      "  <artifactId>aws-xray-recorder-sdk-core</artifactId>",
      "  <version>2.15.0</version>",
      "</dependency>",
      "<dependency>",
      "  <groupId>com.amazonaws</groupId>",
      "  <artifactId>aws-xray-recorder-sdk-aws-sdk-v2</artifactId>",
      "  <version>2.15.0</version>",
      "</dependency>",
    ]),
    spacer(),
    codeBlock([
      "package com.monapp.lambda;",
      "",
      "import com.amazonaws.services.lambda.runtime.Context;",
      "import com.amazonaws.services.lambda.runtime.RequestHandler;",
      "import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent;",
      "import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent;",
      "import com.amazonaws.xray.AWSXRay;",
      "import com.amazonaws.xray.entities.Subsegment;",
      "import software.amazon.awssdk.services.dynamodb.DynamoDbClient;",
      "import software.amazon.awssdk.core.interceptor.TracingInterceptor;",
      "import software.amazon.awssdk.services.dynamodb.model.*;",
      "",
      "public class TracedReservationHandler",
      "        implements RequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> {",
      "",
      "    // Client DynamoDB avec intercepteur X-Ray (trace automatiquement les appels DDB)",
      "    private static final DynamoDbClient dynamoDB = DynamoDbClient.builder()",
      "        .overrideConfiguration(c -> c.addExecutionInterceptor(new TracingInterceptor()))",
      "        .build();",
      "",
      "    @Override",
      "    public APIGatewayProxyResponseEvent handleRequest(",
      "            APIGatewayProxyRequestEvent event, Context context) {",
      "",
      "        String userId = event.getPathParameters().get('userId');",
      "",
      "        // Ajouter des annotations indexables a la trace",
      "        AWSXRay.getCurrentSegment().putAnnotation('userId', userId);",
      "        AWSXRay.getCurrentSegment().putAnnotation('environment',",
      "            System.getenv().getOrDefault('ENVIRONMENT', 'dev'));",
      "",
      "        // Ajouter des metadonnees (non indexees, pour le debugging)",
      "        AWSXRay.getCurrentSegment().putMetadata('requestPath', event.getPath());",
      "",
      "        // Creer un sous-segment personnalise pour tracer une operation",
      "        Subsegment validationSegment = AWSXRay.beginSubsegment('validateUser');",
      "        try {",
      "            boolean valid = validateUser(userId);",
      "            validationSegment.putAnnotation('userValid', String.valueOf(valid));",
      "            if (!valid) {",
      "                return new APIGatewayProxyResponseEvent()",
      "                    .withStatusCode(403)",
      "                    .withBody('{\"error\":\"Forbidden\"}');",
      "            }",
      "        } catch (Exception e) {",
      "            validationSegment.addException(e); // Marque le segment comme erreur dans X-Ray",
      "            throw e;",
      "        } finally {",
      "            AWSXRay.endSubsegment();",
      "        }",
      "",
      "        // Requete DynamoDB - automatiquement tracee par TracingInterceptor",
      "        Subsegment ddbSegment = AWSXRay.beginSubsegment('getReservations');",
      "        try {",
      "            QueryResponse response = dynamoDB.query(QueryRequest.builder()",
      "                .tableName(System.getenv('RESERVATIONS_TABLE'))",
      "                .keyConditionExpression('userId = :uid')",
      "                .expressionAttributeValues(java.util.Map.of(",
      "                    ':uid', AttributeValue.fromS(userId)))",
      "                .build());",
      "",
      "            ddbSegment.putMetadata('itemCount', response.count());",
      "            return new APIGatewayProxyResponseEvent()",
      "                .withStatusCode(200)",
      "                .withBody('{\"count\":' + response.count() + '}');",
      "        } catch (Exception e) {",
      "            ddbSegment.addException(e);",
      "            throw e;",
      "        } finally {",
      "            AWSXRay.endSubsegment();",
      "        }",
      "    }",
      "",
      "    private boolean validateUser(String userId) {",
      "        return userId != null && !userId.isEmpty();",
      "    }",
      "}",
    ]),
    spacer(),

    h2("13.6 CloudWatch Application Insights"),
    p("CloudWatch Application Insights detecte automatiquement les problemes dans vos applications en analysant les metriques et logs des ressources associees."),
    spacer(),
    codeBlock([
      "# Configurer Application Insights pour une stack CloudFormation",
      "aws application-insights create-application \\",
      "  --resource-group-name MonApp-ResourceGroup \\",
      "  --auto-config-enabled \\",
      "  --cwe-monitor-enabled \\",
      "  --ops-center-enabled",
      "",
      "# Application Insights surveille automatiquement :",
      "# - Lambda : taux d'erreur, latence, throttles, cold starts",
      "# - DynamoDB : latence des operations, throttles, capacite",
      "# - API Gateway : latence, taux d'erreur 4xx et 5xx",
      "# - EC2/ECS : CPU, memoire, disque, reseau",
    ]),
    spacer(),

    h2("13.7 Dashboard CloudWatch"),
    codeBlock([
      "// Creer un dashboard CloudWatch programmatiquement",
      "import software.amazon.awssdk.services.cloudwatch.model.*;",
      "import com.fasterxml.jackson.databind.ObjectMapper;",
      "import java.util.*;",
      "",
      "public void createDashboard(CloudWatchClient cloudWatch) throws Exception {",
      "    // Definition du dashboard en JSON",
      "    Map<String, Object> dashboard = new HashMap<>();",
      "    List<Map<String, Object>> widgets = new ArrayList<>();",
      "",
      "    // Widget 1: Graphique des erreurs Lambda",
      "    Map<String, Object> errorsWidget = new HashMap<>();",
      "    errorsWidget.put('type', 'metric');",
      "    errorsWidget.put('x', 0); errorsWidget.put('y', 0);",
      "    errorsWidget.put('width', 12); errorsWidget.put('height', 6);",
      "    errorsWidget.put('properties', Map.of(",
      "        'title', 'Lambda Errors',",
      "        'metrics', List.of(List.of('AWS/Lambda', 'Errors',",
      "            'FunctionName', 'GetReservationsFunction')),",
      "        'period', 60,",
      "        'stat', 'Sum',",
      "        'view', 'timeSeries'",
      "    ));",
      "    widgets.add(errorsWidget);",
      "",
      "    // Widget 2: Latence P99 DynamoDB",
      "    Map<String, Object> latencyWidget = new HashMap<>();",
      "    latencyWidget.put('type', 'metric');",
      "    latencyWidget.put('x', 12); latencyWidget.put('y', 0);",
      "    latencyWidget.put('width', 12); latencyWidget.put('height', 6);",
      "    latencyWidget.put('properties', Map.of(",
      "        'title', 'DynamoDB Latency P99',",
      "        'metrics', List.of(List.of('AWS/DynamoDB', 'SuccessfulRequestLatency',",
      "            'TableName', 'reservations', 'Operation', 'GetItem')),",
      "        'period', 60,",
      "        'stat', 'p99'",
      "    ));",
      "    widgets.add(latencyWidget);",
      "",
      "    dashboard.put('widgets', widgets);",
      "",
      "    cloudWatch.putDashboard(PutDashboardRequest.builder()",
      "        .dashboardName('MonApp-Production')",
      "        .dashboardBody(new ObjectMapper().writeValueAsString(dashboard))",
      "        .build());",
      "}",
    ]),
    spacer(),

    h2("13.8 Bonnes Pratiques d'Observabilite"),
    infoBox("Les 3 Piliers de l'Observabilite",
      "1. METRIQUES (CloudWatch Custom Metrics) : Publiez des metriques metier (reservations/heure, revenus, taux de conversion) en plus des metriques techniques. Utilisez des dimensions pour filtrer (par region, par produit).\n2. LOGS STRUCTURES (JSON) : Ecrivez des logs JSON structures plutot que du texte libre. Facilitez l'analyse avec Logs Insights. Incluez toujours : requestId, userId, operation, latenceMs, statusCode.\n3. TRACES (X-Ray) : Annotez avec les donnees metier (userId, reservationId). Utilisez les traces pour identifier les goulots d'etranglement inter-services.",
      LIGHT_BLUE, BLUE),
    spacer(),
    codeBlock([
      "// Logging structure en JSON pour CloudWatch Logs Insights",
      "package com.monapp.logging;",
      "",
      "import com.fasterxml.jackson.databind.ObjectMapper;",
      "import com.amazonaws.services.lambda.runtime.LambdaLogger;",
      "import java.util.*;",
      "",
      "public class StructuredLogger {",
      "",
      "    private static final ObjectMapper mapper = new ObjectMapper();",
      "    private final LambdaLogger logger;",
      "    private final String requestId;",
      "    private final String userId;",
      "",
      "    public StructuredLogger(LambdaLogger logger, String requestId, String userId) {",
      "        this.logger = logger;",
      "        this.requestId = requestId;",
      "        this.userId = userId;",
      "    }",
      "",
      "    public void info(String message, Map<String, Object> extra) {",
      "        log('INFO', message, extra, null);",
      "    }",
      "",
      "    public void error(String message, Exception e) {",
      "        log('ERROR', message, null, e);",
      "    }",
      "",
      "    private void log(String level, String message,",
      "                     Map<String, Object> extra, Exception e) {",
      "        Map<String, Object> entry = new LinkedHashMap<>();",
      "        entry.put('level', level);",
      "        entry.put('message', message);",
      "        entry.put('requestId', requestId);",
      "        entry.put('userId', userId);",
      "        entry.put('timestamp', java.time.Instant.now().toString());",
      "        entry.put('service', 'reservation-service');",
      "        if (extra != null) entry.putAll(extra);",
      "        if (e != null) {",
      "            entry.put('error', e.getClass().getSimpleName());",
      "            entry.put('errorMessage', e.getMessage());",
      "        }",
      "        try {",
      "            logger.log(mapper.writeValueAsString(entry));",
      "        } catch (Exception ex) {",
      "            logger.log(level + ': ' + message);",
      "        }",
      "    }",
      "",
      "    // Usage dans le handler Lambda :",
      "    // StructuredLogger log = new StructuredLogger(context.getLogger(),",
      "    //     context.getAwsRequestId(), userId);",
      "    // log.info('Reservation creee', Map.of('reservationId', id, 'price', 500));",
      "    // Genere: {\"level\":\"INFO\",\"message\":\"Reservation creee\",",
      "    //          \"requestId\":\"...\",\"userId\":\"alice\",\"reservationId\":\"RES-001\",\"price\":500}",
      "}",
    ]),
    spacer(),

    h2("13.9 Questions de Revision - Module 13"),
    infoBox("Question 1",
      "Votre equipe reporte des latences elevees sporadiques dans votre API serverless (Lambda + DynamoDB + API Gateway). Quel service AWS vous aide le mieux a identifier le service responsable et les timestamps exacts des ralentissements ?\nA) CloudWatch Metrics\nB) CloudWatch Logs\nC) AWS X-Ray\nD) AWS CloudTrail\nReponse correcte : C - AWS X-Ray fournit des traces distribuees montrant le temps passe dans chaque service (API Gateway, Lambda, DynamoDB). La Service Map et les traces individuelles identifient exactement quel service prend le plus de temps et quand les latences se produisent.",
      LIGHT_ORANGE, ORANGE),
    spacer(),
    infoBox("Question 2",
      "Vous souhaitez etre alerte si le taux d'erreur de votre fonction Lambda depasse 5% sur une periode de 5 minutes. Quel service configurez-vous ?\nA) AWS X-Ray avec une regle de sampling\nB) CloudWatch Alarm avec une metrique d'Errors Lambda et un seuil\nC) CloudWatch Logs Insights avec une requete schedulee\nD) AWS CloudTrail avec un filtre d'evenements\nReponse correcte : B - CloudWatch Alarms sont le mecanisme standard pour les alertes basees sur des seuils de metriques. Configurez une alarme sur la metrique 'Errors' de Lambda avec threshold=5, period=60, evaluationPeriods=5 et une action SNS pour la notification.",
      LIGHT_ORANGE, ORANGE),
    spacer(),

    h2("13.10 Resume du Module 13"),
    bullet("Observabilite = Metriques (CloudWatch) + Logs (CloudWatch Logs) + Traces (X-Ray)"),
    bullet("CloudWatch Metrics : metriques AWS natives + metriques personnalisees avec dimensions"),
    bullet("CloudWatch Alarms : alertes sur seuils avec actions SNS, Auto Scaling, EC2"),
    bullet("CloudWatch Logs Insights : requetes SQL-like sur les logs pour le debugging"),
    bullet("X-Ray Tracing : traces distribuees pour identifier les goulots d'etranglement"),
    bullet("X-Ray Annotations : indexables pour filtrer les traces (userId, environnement)"),
    bullet("X-Ray ServiceMap : visualisation graphique des dependances inter-services"),
    spacer(),
  ];
}

// ANNEXES ET GLOSSAIRE
function annexes() {
  return [
    pageBreak(),
    h1("ANNEXE A : Glossaire des Termes AWS"),
    spacer(),

    h2("A.1 Termes Fondamentaux"),
    codeBlock([
      "ACL (Access Control List)     : Liste de controle d'acces pour S3 (deconseille au profit des politiques)",
      "AZ (Availability Zone)        : Zone de disponibilite - datacenter physiquement isole dans une region",
      "ARN (Amazon Resource Name)    : Identifiant unique global d'une ressource AWS",
      "CIDR                          : Notation pour definir des plages d'adresses IP (ex: 10.0.0.0/16)",
      "CLI (Command Line Interface)  : AWS CLI - outil ligne de commande pour interagir avec AWS",
      "CDN (Content Delivery Network): Reseau de distribution de contenu (CloudFront)",
      "DAX (DynamoDB Accelerator)    : Cache en memoire pour DynamoDB (microseconds)",
      "EC2 (Elastic Compute Cloud)   : Service de machines virtuelles AWS",
      "ECS (Elastic Container Service): Orchestration de conteneurs Docker sur AWS",
      "EKS (Elastic Kubernetes Service): Kubernetes manage sur AWS",
      "ELB (Elastic Load Balancer)   : Load balancers AWS (ALB, NLB, CLB)",
      "GSI (Global Secondary Index)  : Index DynamoDB avec nouvelle cle de partition",
      "IAM (Identity Access Management): Service de controle d'acces AWS",
      "JMESPath                      : Langage de requete pour filtrer les sorties JSON de l'AWS CLI",
      "JWT (JSON Web Token)          : Token d'authentification signe et chiffre",
      "KMS (Key Management Service)  : Service de gestion des cles de chiffrement",
      "LSI (Local Secondary Index)   : Index DynamoDB avec meme partition key",
      "MFA (Multi-Factor Authentication): Authentification a plusieurs facteurs",
      "NACL (Network ACL)            : Controle d'acces au niveau du sous-reseau VPC",
      "NAT Gateway                   : Permet aux ressources privees VPC d'acceder a Internet",
      "PoP (Point of Presence)       : Point de presence CloudFront dans le monde",
      "RCU (Read Capacity Unit)      : Unite de capacite de lecture DynamoDB",
      "SDK (Software Development Kit): Bibliotheques pour interagir avec AWS depuis votre code",
      "SG (Security Group)           : Pare-feu virtuel pour les instances EC2/RDS",
      "SNS (Simple Notification Service): Service de notification pub/sub",
      "SQS (Simple Queue Service)    : Service de file d'attente de messages",
      "STS (Security Token Service)  : Credentials temporaires AWS",
      "VPC (Virtual Private Cloud)   : Reseau virtuel prive isole dans AWS",
      "WAF (Web Application Firewall): Pare-feu applicatif pour protection contre les attaques web",
      "WCU (Write Capacity Unit)     : Unite de capacite d'ecriture DynamoDB",
    ]),
    spacer(),

    h2("A.2 Limites et Quotas Importants pour la Certification"),
    multiColTable(
      ["Service", "Limite", "Valeur"],
      [2500, 3500, 3360],
      [
        ["S3", "Taille max objet (simple PUT)", "5 GB"],
        ["S3", "Taille max objet (Multipart)", "5 TB"],
        ["S3", "Parties multipart min", "5 MB (sauf derniere)"],
        ["S3", "Nbre max parties multipart", "10 000"],
        ["DynamoDB", "Taille max d'un item", "400 KB"],
        ["DynamoDB", "Taille max de donnees par transaction", "4 MB"],
        ["DynamoDB", "Items max par transaction", "100"],
        ["Lambda", "Timeout max", "900 secondes (15 minutes)"],
        ["Lambda", "Memoire max", "10 240 MB (10 GB)"],
        ["Lambda", "Taille max du package (ZIP)", "50 MB (250 MB decompresse)"],
        ["Lambda", "Taille max package via S3", "250 MB decompresse"],
        ["Lambda", "Stockage /tmp", "512 MB a 10 GB"],
        ["Lambda", "Concurrence par defaut", "1000 par region"],
        ["Lambda", "Payload max (sync)", "6 MB"],
        ["Lambda", "Payload max (async)", "256 KB"],
        ["API Gateway", "Timeout max integration", "29 secondes"],
        ["API Gateway", "Payload max", "10 MB"],
        ["SQS Standard", "Taille max message", "256 KB"],
        ["SQS", "Retention max", "14 jours"],
        ["SQS", "Visibility timeout max", "12 heures"],
        ["Cognito User Pool", "Utilisateurs max (soft)", "Illimite (augmentable)"],
        ["Step Functions", "Items max par transaction", "N/A (par execution)"],
        ["Step Functions", "Max payload entre etats", "256 KB"],
      ]
    ),
    spacer(),

    pageBreak(),
    h1("ANNEXE B : Questions de Pratique DVA-C02 - Set Complet"),
    spacer(),
    p("Voici un ensemble de 30 questions de pratique couvrant tous les domaines de l'examen AWS Certified Developer Associate (DVA-C02)."),
    spacer(),

    h2("B.1 Domaine 1 : Developpement avec les Services AWS (32%)"),
    infoBox("Question 1",
      "Une fonction Lambda Java traite des fichiers CSV uploades dans S3. Les fichiers peuvent atteindre 500 MB. La fonction timeout apres 15 minutes. Quelle solution evite le timeout ?\nA) Augmenter la memoire Lambda a 10 GB\nB) Utiliser S3 Select pour filtrer les donnees avant traitement\nC) Diviser le traitement en plusieurs fonctions Lambda enchainee via SQS\nD) Utiliser AWS Batch pour le traitement de gros fichiers\nReponse: D - AWS Batch est concu pour les jobs de calcul de longue duree sur des fichiers volumineux. Les etapes B et C peuvent aussi fonctionner selon le cas. Lambda max 15 minutes n'est pas adapte pour les tres gros fichiers. AWS Batch peut traiter sans limite de temps.",
      LIGHT_ORANGE, ORANGE),
    spacer(),
    infoBox("Question 2",
      "Votre application DynamoDB effectue 500 ecritures par seconde d'items de 2 KB. Combien de WCU (Write Capacity Units) faut-il provisionner ?\nA) 500 WCU\nB) 1000 WCU\nC) 250 WCU\nD) 2000 WCU\nReponse: B - 1 WCU = 1 ecriture/sec pour items <= 1 KB. Un item de 2 KB = 2 WCU par ecriture. 500 ecritures/sec x 2 WCU = 1000 WCU. Pour les transactions, multipliez par 2 (2000 WCU).",
      LIGHT_ORANGE, ORANGE),
    spacer(),
    infoBox("Question 3",
      "Un developpeur doit stocker des secrets de base de donnees dans une application Lambda. Quelle est la MEILLEURE pratique ?\nA) Variables d'environnement Lambda (en clair)\nB) Variables d'environnement Lambda chiffrees avec KMS + reference a AWS Secrets Manager\nC) Hardcoder dans le code Java\nD) Fichier de configuration dans le package JAR\nReponse: B - AWS Secrets Manager est le service prevu pour les secrets (rotation automatique, audit CloudTrail, chiffrement KMS). Les variables d'environnement peuvent referencer le nom du secret, et le code recupere la valeur depuis Secrets Manager au demarrage (cached).",
      LIGHT_ORANGE, ORANGE),
    spacer(),
    infoBox("Question 4",
      "Une API REST Gateway recoit 1000 requetes par seconde. Vous devez limiter chaque client a 100 req/sec maximum. Quelle solution implementez-vous ?\nA) Throttling au niveau du stage (Account-level throttling)\nB) Usage Plans avec API Keys et limit par client\nC) Lambda Reserved Concurrency a 100\nD) CloudFront rate limiting\nReponse: B - Les Usage Plans API Gateway permettent de definir des limites (rate en req/sec, burst, quota mensuel) par client identifie par une API Key. C'est la solution native pour le rate limiting par client dans API Gateway.",
      LIGHT_ORANGE, ORANGE),
    spacer(),
    infoBox("Question 5",
      "Vous developpez une application qui doit acceder a DynamoDB depuis une instance EC2. Quelle methode d'authentification utilisez-vous ?\nA) Stocker les Access Keys dans /etc/environment\nB) Configurer aws configure sur l'instance\nC) Attacher un role IAM a l'instance EC2\nD) Passer les credentials en parametre de la requete HTTP\nReponse: C - Attacher un role IAM EC2 est la methode recommandee. L'instance obtient automatiquement des credentials temporaires via le service de metadata EC2 (http://169.254.169.254). Aucune gestion manuelle de credentials.",
      LIGHT_ORANGE, ORANGE),
    spacer(),

    h2("B.2 Domaine 2 : Securite (26%)"),
    infoBox("Question 6",
      "Une politique IAM accorde s3:GetObject sur tous les buckets. Une politique de bucket refuse l'acces pour un utilisateur specifique. Quelle est la reponse effective ?\nA) L'acces est accorde car la politique IAM est plus specifique\nB) L'acces est refuse car Deny explicite l'emporte toujours sur Allow\nC) L'acces depend de l'ordre d'evaluation\nD) Les deux politiques s'annulent, acces refuse par defaut\nReponse: B - La regle fondamentale : Deny explicite > Allow explicite > Deny implicite. Meme si la politique IAM autorise, le Deny explicite dans la politique de bucket refuse l'acces.",
      LIGHT_ORANGE, ORANGE),
    spacer(),
    infoBox("Question 7",
      "Un utilisateur A dans le compte AWS 111 veut acceder a un bucket S3 dans le compte AWS 222. Quelle configuration est NECESSAIRE ?\nA) Seulement une politique IAM dans le compte 111 autorisant l'acces S3\nB) Seulement une politique de bucket dans le compte 222 autorisant l'utilisateur A\nC) Les DEUX : politique IAM dans 111 ET politique de bucket dans 222 autorisant l'acces cross-account\nD) Un role STS dans le compte 111\nReponse: C - Pour le cross-account S3, les DEUX politiques sont necessaires. La politique IAM autorise l'utilisateur A a faire des requetes S3. La politique de bucket dans le compte 222 autorise l'utilisateur du compte 111 a acceder.",
      LIGHT_ORANGE, ORANGE),
    spacer(),

    h2("B.3 Domaine 3 : Deploiement (24%)"),
    infoBox("Question 8",
      "Vous deployez une nouvelle version de Lambda et souhaitez que 10% du trafic de l'alias 'live' soit redirige vers la nouvelle version, avec rollback automatique si les erreurs augmentent. Comment configurez-vous cela ?\nA) Creer deux alias distincts et utiliser Route 53 pour le routage\nB) Utiliser le traffic shifting d'alias Lambda avec CodeDeploy et des alarmes CloudWatch\nC) Deployer deux fonctions differentes et configurer API Gateway pour router\nD) Utiliser Lambda Layers pour la gestion des versions\nReponse: B - Lambda supporte le traffic shifting via les alias. Avec CodeDeploy (SAM DeploymentPreference), vous configurez un alias pour envoyer X% vers version:N et (100-X)% vers version:N-1, avec rollback automatique si les alarmes CloudWatch se declenchent.",
      LIGHT_ORANGE, ORANGE),
    spacer(),

    h2("B.4 Domaine 4 : Troubleshooting et Optimisation (18%)"),
    infoBox("Question 9",
      "Vos requetes DynamoDB retournent une erreur 'ProvisionedThroughputExceededException'. Quelle est la cause et la solution ?\nA) La table est pleine. Solution: supprimer des items.\nB) Vous avez depasse les RCU/WCU provisiones. Solution: exponential backoff + augmenter la capacite ou passer en On-Demand.\nC) La region DynamoDB est down. Solution: attendre la resolution.\nD) Le token IAM a expire. Solution: renouveler les credentials.\nReponse: B - ProvisionedThroughputExceededException signifie que vous avez depasse la capacite provisonnee. Solution immediate: implementer l'exponential backoff avec jitter dans vos retry. Solution long terme: augmenter les RCU/WCU ou passer en mode On-Demand.",
      LIGHT_ORANGE, ORANGE),
    spacer(),
    infoBox("Question 10",
      "Une application Lambda envoie des messages SQS en batch de 10. Lors du traitement par une autre Lambda, certains messages echouent. Comment garantir que seuls les messages en echec sont reiteres, pas les messages reussis ?\nA) Reenvoyez tous les messages dans un nouveau batch\nB) Retournez batchItemFailures dans la reponse Lambda avec les messageIds des messages echoues\nC) Configurez une DLQ sur SQS avec maxReceiveCount=1\nD) Augmentez le visibility timeout\nReponse: B - La fonctionnalite 'Report Batch Item Failures' de Lambda+SQS permet de specifier les messageIds des items echoues dans la reponse. Seuls ces items retourneront dans la queue pour retraitement. Sans cette configuration, tout le batch est retraite.",
      LIGHT_ORANGE, ORANGE),
    spacer(),

    pageBreak(),
    h1("ANNEXE C : Architectures de Reference"),
    spacer(),
    h2("C.1 Architecture Serverless Complete"),
    codeBlock([
      "Application de Reservation de Voyages - Architecture Complete",
      "",
      "                    ┌─────────────────────────────────────────────┐",
      "                    │  Utilisateurs (Web & Mobile)                │",
      "                    └─────────────────┬───────────────────────────┘",
      "                                      │ HTTPS",
      "                    ┌─────────────────▼───────────────────────────┐",
      "                    │  Route 53 - DNS avec Health Checks          │",
      "                    └─────────────────┬───────────────────────────┘",
      "                                      │",
      "                    ┌─────────────────▼───────────────────────────┐",
      "                    │  CloudFront - CDN Global (450+ PoPs)        │",
      "                    │  Cache HTML/JS/CSS/Images                   │",
      "                    └──────┬──────────────────────┬───────────────┘",
      "                           │ /api/*                │ /*",
      "           ┌───────────────▼──────┐  ┌────────────▼──────────────┐",
      "           │  API Gateway REST    │  │  S3 - Site Statique        │",
      "           │  - Cognito Auth      │  │  React SPA                 │",
      "           │  - Rate Limiting     │  └───────────────────────────┘",
      "           │  - Cache 5 min       │",
      "           └──┬───────┬───────┬───┘",
      "              │       │       │",
      "    ┌─────────▼──┐ ┌──▼────┐ ┌▼────────────┐",
      "    │ Lambda     │ │Lambda │ │ Lambda       │",
      "    │ GET /res   │ │ POST  │ │ DELETE /res  │",
      "    │ Java 17    │ │ /res  │ │ Java 17      │",
      "    │ SnapStart  │ │       │ │              │",
      "    └─────┬──────┘ └──┬────┘ └──────┬───────┘",
      "          │            │              │",
      "    ┌─────▼────────────▼──────────────▼──────┐",
      "    │         DynamoDB (Tables)               │",
      "    │  Reservations | Users | Products        │",
      "    │  On-Demand | DAX Cache | Streams        │",
      "    └─────────────────┬────────────────────────┘",
      "                      │ DynamoDB Streams",
      "              ┌───────▼──────────┐",
      "              │ Lambda - Events   │",
      "              │ Processor         │",
      "              └──────┬────────────┘",
      "                     │",
      "            ┌────────▼─────────┐",
      "            │  SNS Topic       │",
      "            │  reservation-    │",
      "            │  events          │",
      "            └──┬─────────┬─────┘",
      "               │         │",
      "    ┌──────────▼─┐ ┌────▼────────────┐",
      "    │ SQS Queue  │ │ Lambda          │",
      "    │ Emails     │ │ Analytics       │",
      "    └──────┬─────┘ └─────────────────┘",
      "           │",
      "    ┌──────▼─────┐",
      "    │ Lambda SES │",
      "    │ Email Send │",
      "    └────────────┘",
      "",
      "Monitoring: CloudWatch + X-Ray + CloudWatch Logs",
      "Auth: Cognito User Pool + JWT Tokens",
      "Secrets: AWS Secrets Manager + KMS",
      "Deploy: SAM + CodePipeline + CodeDeploy (Canary)",
    ]),
    spacer(),

    h2("C.2 Commandes AWS CLI de Reference"),
    codeBlock([
      "# === S3 ===",
      "aws s3 ls                                    # Lister les buckets",
      "aws s3 ls s3://bucket/ --recursive           # Lister recursivement",
      "aws s3 cp file.txt s3://bucket/key           # Upload",
      "aws s3 cp s3://bucket/key file.txt           # Download",
      "aws s3 sync ./dist s3://bucket/              # Synchroniser",
      "aws s3 presign s3://bucket/key --expires-in 3600  # URL presignee",
      "aws s3api put-bucket-versioning --bucket b --versioning-configuration Status=Enabled",
      "",
      "# === DYNAMODB ===",
      "aws dynamodb list-tables",
      "aws dynamodb describe-table --table-name TABLE",
      "aws dynamodb put-item --table-name TABLE --item file://item.json",
      "aws dynamodb get-item --table-name TABLE --key '{\"id\":{\"S\":\"123\"}}'",
      "aws dynamodb query --table-name TABLE --key-condition-expression 'id = :v' --expression-attribute-values '{\":v\":{\"S\":\"123\"}}'",
      "aws dynamodb scan --table-name TABLE --limit 10",
      "",
      "# === LAMBDA ===",
      "aws lambda list-functions --region eu-west-1",
      "aws lambda invoke --function-name FN --payload '{}' --cli-binary-format raw-in-base64-out out.json",
      "aws lambda update-function-code --function-name FN --zip-file fileb://fn.jar",
      "aws lambda get-function --function-name FN",
      "aws lambda publish-version --function-name FN",
      "",
      "# === API GATEWAY ===",
      "aws apigateway get-rest-apis",
      "aws apigateway get-resources --rest-api-id API_ID",
      "aws apigateway create-deployment --rest-api-id API_ID --stage-name prod",
      "",
      "# === COGNITO ===",
      "aws cognito-idp list-user-pools --max-results 10",
      "aws cognito-idp initiate-auth --auth-flow USER_PASSWORD_AUTH --client-id CLIENT --auth-parameters USERNAME=user@mail.com,PASSWORD=Pass123!",
      "aws cognito-idp admin-create-user --user-pool-id POOL_ID --username user@mail.com",
      "",
      "# === CLOUDWATCH ===",
      "aws cloudwatch list-metrics --namespace AWS/Lambda",
      "aws cloudwatch get-metric-statistics --namespace AWS/Lambda --metric-name Errors --dimensions Name=FunctionName,Value=MyFn --start-time 2024-01-01T00:00:00Z --end-time 2024-01-02T00:00:00Z --period 3600 --statistics Sum",
      "",
      "# === X-RAY ===",
      "aws xray get-service-graph --start-time 1700000000 --end-time 1700003600",
      "aws xray get-trace-summaries --start-time 1700000000 --end-time 1700003600",
    ]),
    spacer(),

    h2("C.3 Liens Utiles pour la Preparation"),
    twoColTable(
      ["Ressource", "Description"],
      [
        ["AWS Documentation officielle", "docs.aws.amazon.com - Reference complete de tous les services"],
        ["AWS Skill Builder", "skillbuilder.aws - Cours officiels gratuits et payants AWS"],
        ["AWS Exam Guide DVA-C02", "Guide officiel de l'examen avec les domaines et les poids"],
        ["AWS Well-Architected Framework", "aws.amazon.com/architecture/well-architected - Les 6 piliers"],
        ["AWS SDK for Java v2 Javadoc", "sdk.amazonaws.com/java/api/latest - Documentation API complète"],
        ["AWS Sample Code (GitHub)", "github.com/awsdocs/aws-doc-sdk-examples - Exemples de code"],
        ["AWS re:Invent YouTube", "Presentations techniques des ingénieurs AWS"],
        ["A Cloud Guru / Udemy", "Cours de preparation certifications avec labs pratiques"],
      ]
    ),
    spacer(),
  ];
}

// GENERER PART 5 (Modules 12-13 + Annexes)
async function generatePart5() {
  console.log('Generation Part 5 (Modules 12-13 + Annexes)...');
  const content = [
    ...module12(),
    ...module13(),
    ...annexes(),
  ];

  const doc = new Document({
    numbering: {
      config: [
        { reference: "bullets", levels: [{ level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } }, run: { font: "Symbol" } } }] },
        { reference: "numbers", levels: [{ level: 0, format: LevelFormat.DECIMAL, text: "%1.", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },
      ]
    },
    styles: {
      default: { document: { run: { font: "Arial", size: 22 } } },
      paragraphStyles: [
        { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 40, bold: true, font: "Arial", color: BLUE }, paragraph: { spacing: { before: 480, after: 240 }, outlineLevel: 0, border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: ORANGE } } } },
        { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 32, bold: true, font: "Arial", color: BLUE }, paragraph: { spacing: { before: 320, after: 160 }, outlineLevel: 1 } },
        { id: "Heading3", name: "Heading 3", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 26, bold: true, font: "Arial", color: DARK_GRAY }, paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 2 } },
      ]
    },
    sections: [{
      properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
      headers: { default: new Header({ children: [new Paragraph({ border: { bottom: { style: BorderStyle.SINGLE, size: 2, color: BLUE } }, children: [new TextRun({ text: "Cours AWS pour Developpeurs Java - SAM | CloudWatch | X-Ray | Annexes", font: "Arial", size: 18, color: BLUE })] })] }) },
      footers: { default: new Footer({ children: [new Paragraph({ border: { top: { style: BorderStyle.SINGLE, size: 2, color: BLUE } }, children: [new TextRun({ text: "AWS SDK for Java v2 - 2025  Page ", font: "Arial", size: 18, color: "888888" }), new TextRun({ children: [PageNumber.CURRENT], font: "Arial", size: 18, color: BLUE })] })] }) },
      children: content
    }]
  });

  const buffer = await Packer.toBuffer(doc);
  const outputPath = '/Users/user/Desktop/travel-agency/backend/.claude/worktrees/naughty-jepsen-0d5f95/cours_aws_java_part5.docx';
  fs.writeFileSync(outputPath, buffer);
  console.log('Part 5 generee: ' + outputPath + ' - ' + Math.round(buffer.length/1024) + ' KB');
}

generatePart5().catch(console.error);
