const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
        HeadingLevel, AlignmentType, BorderStyle, WidthType, ShadingType,
        PageNumber, Header, Footer, PageBreak, LevelFormat } = require('docx');
const fs = require('fs');

const CONTENT_WIDTH = 9360;
const ORANGE = "E8630A";
const BLUE = "1B4F8A";
const LIGHT_BLUE = "D6E4F0";
const LIGHT_ORANGE = "FEF0E6";
const LIGHT_GREEN = "E8F8E8";
const LIGHT_RED = "FDECEA";
const LIGHT_GRAY = "F5F5F5";
const DARK_GRAY = "333333";

const border = { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" };
const borders = { top: border, bottom: border, left: border, right: border };
const noBorders = {
  top: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
  bottom: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
  left: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
  right: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" }
};

function h1(text) {
  return new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text, bold: true, color: BLUE })] });
}
function h2(text) {
  return new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text, bold: true, color: BLUE })] });
}
function h3(text) {
  return new Paragraph({ heading: HeadingLevel.HEADING_3, children: [new TextRun({ text, bold: true })] });
}
function p(text, opts = {}) {
  return new Paragraph({ spacing: { after: 160 }, children: [new TextRun({ text, ...opts })] });
}
function pageBreak() { return new Paragraph({ children: [new PageBreak()] }); }
function spacer() { return new Paragraph({ spacing: { after: 200 }, children: [new TextRun("")] }); }
function bullet(text, bold = false) {
  return new Paragraph({
    numbering: { reference: "bullets", level: 0 },
    spacing: { after: 80 },
    children: [new TextRun({ text, bold })]
  });
}
function numbered(text) {
  return new Paragraph({
    numbering: { reference: "numbers", level: 0 },
    spacing: { after: 80 },
    children: [new TextRun({ text })]
  });
}
function codeBlock(lines) {
  return new Table({
    width: { size: CONTENT_WIDTH - 240, type: WidthType.DXA },
    columnWidths: [CONTENT_WIDTH - 240],
    borders: { top: { style: BorderStyle.SINGLE, size: 2, color: "555555" }, bottom: { style: BorderStyle.SINGLE, size: 2, color: "555555" }, left: { style: BorderStyle.SINGLE, size: 2, color: "555555" }, right: { style: BorderStyle.SINGLE, size: 2, color: "555555" } },
    rows: lines.map(line => new TableRow({ children: [new TableCell({
      borders: noBorders,
      width: { size: CONTENT_WIDTH - 240, type: WidthType.DXA },
      shading: { fill: "1E1E1E", type: ShadingType.CLEAR },
      margins: { top: 0, bottom: 0, left: 200, right: 200 },
      children: [new Paragraph({ spacing: { after: 0, before: 0, line: 276 }, children: [new TextRun({ text: line || " ", font: "Courier New", size: 18, color: "D4D4D4" })] })]
    })] }))
  });
}
function infoBox(title, text, fill = LIGHT_BLUE, titleColor = BLUE) {
  return new Table({
    width: { size: CONTENT_WIDTH, type: WidthType.DXA },
    columnWidths: [CONTENT_WIDTH],
    rows: [new TableRow({ children: [new TableCell({
      borders,
      width: { size: CONTENT_WIDTH, type: WidthType.DXA },
      shading: { fill, type: ShadingType.CLEAR },
      margins: { top: 120, bottom: 120, left: 200, right: 200 },
      children: [
        new Paragraph({ spacing: { after: 60 }, children: [new TextRun({ text: title, bold: true, color: titleColor, size: 22 })] }),
        new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text, size: 20 })] })
      ]
    })] })]
  });
}
function twoColTable(headers, rows) {
  const w0 = 3000, w1 = CONTENT_WIDTH - 3000;
  return new Table({
    width: { size: CONTENT_WIDTH, type: WidthType.DXA },
    columnWidths: [w0, w1],
    rows: [
      new TableRow({ children: headers.map((h, i) => new TableCell({ borders, width: { size: i === 0 ? w0 : w1, type: WidthType.DXA }, shading: { fill: BLUE, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text: h, bold: true, color: "FFFFFF", size: 20 })] })] })) }),
      ...rows.map((row, ri) => new TableRow({ children: row.map((cell, ci) => new TableCell({ borders, width: { size: ci === 0 ? w0 : w1, type: WidthType.DXA }, shading: { fill: ri % 2 === 0 ? "FFFFFF" : LIGHT_GRAY, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text: cell, size: 20 })] })] })) }))
    ]
  });
}
function multiColTable(headers, colWidths, rows) {
  return new Table({
    width: { size: colWidths.reduce((a, b) => a + b, 0), type: WidthType.DXA },
    columnWidths: colWidths,
    rows: [
      new TableRow({ children: headers.map((h, i) => new TableCell({ borders, width: { size: colWidths[i], type: WidthType.DXA }, shading: { fill: BLUE, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text: h, bold: true, color: "FFFFFF", size: 20 })] })] })) }),
      ...rows.map((row, ri) => new TableRow({ children: row.map((cell, ci) => new TableCell({ borders, width: { size: colWidths[ci], type: WidthType.DXA }, shading: { fill: ri % 2 === 0 ? "FFFFFF" : LIGHT_GRAY, type: ShadingType.CLEAR }, margins: { top: 80, bottom: 80, left: 120, right: 120 }, children: [new Paragraph({ spacing: { after: 0 }, children: [new TextRun({ text: cell, size: 20 })] })] })) }))
    ]
  });
}

// ============================================================
// MODULE 3: IAM - Autorisations et Securite
// ============================================================
function module3() {
  return [
    pageBreak(),
    h1("MODULE 3 : Premiers Pas avec les Autorisations IAM"),
    spacer(),
    p("AWS Identity and Access Management (IAM) est le service central de controle d'acces d'AWS. Il permet de definir qui peut faire quoi sur quelles ressources AWS. Une mauvaise configuration IAM est l'une des principales causes de failles de securite dans le cloud.", { size: 22 }),
    spacer(),

    h2("3.1 Objectifs d'Apprentissage"),
    bullet("Comprendre les composants fondamentaux d'IAM : utilisateurs, groupes, roles, politiques"),
    bullet("Distinguer les politiques basees sur les identites et les ressources"),
    bullet("Appliquer le principe du moindre privilege"),
    bullet("Tester et valider les permissions IAM"),
    bullet("Configurer l'IDE et le SDK pour le developpement avec IAM"),
    spacer(),

    h2("3.2 Composants Fondamentaux d'IAM"),
    p("IAM s'articule autour de quatre composants principaux :"),
    spacer(),
    multiColTable(
      ["Composant", "Description", "Cas d'Usage"],
      [2000, 4000, 3360],
      [
        ["Utilisateur IAM", "Identite permanente representant une personne ou application", "Developpeurs, administrateurs, applications externes"],
        ["Groupe IAM", "Collection d'utilisateurs partageant les memes permissions", "Equipe Dev, Equipe Ops, Equipe Finance"],
        ["Role IAM", "Identite temporaire assumable par services/utilisateurs/comptes", "Instances EC2, fonctions Lambda, cross-account access"],
        ["Politique IAM", "Document JSON definissant les permissions", "Autoriser/refuser des actions sur des ressources specifiques"],
      ]
    ),
    spacer(),

    h2("3.3 Structure d'une Politique IAM"),
    p("Une politique IAM est un document JSON qui contient des enonces (Statements) definissant les permissions. Comprendre la structure est essentiel pour la certification."),
    spacer(),
    codeBlock([
      "{",
      "  \"Version\": \"2012-10-17\",",
      "  \"Statement\": [",
      "    {",
      "      \"Sid\": \"AllowS3ReadOnly\",",
      "      \"Effect\": \"Allow\",",
      "      \"Action\": [",
      "        \"s3:GetObject\",",
      "        \"s3:ListBucket\"",
      "      ],",
      "      \"Resource\": [",
      "        \"arn:aws:s3:::mon-bucket\",",
      "        \"arn:aws:s3:::mon-bucket/*\"",
      "      ],",
      "      \"Condition\": {",
      "        \"StringEquals\": {",
      "          \"s3:prefix\": [\"uploads/\", \"public/\"]",
      "        },",
      "        \"IpAddress\": {",
      "          \"aws:SourceIp\": [\"192.168.1.0/24\"]",
      "        }",
      "      }",
      "    },",
      "    {",
      "      \"Sid\": \"DenyDeleteBucket\",",
      "      \"Effect\": \"Deny\",",
      "      \"Action\": \"s3:DeleteBucket\",",
      "      \"Resource\": \"*\"",
      "    }",
      "  ]",
      "}",
      "",
      "// Elements de la politique :",
      "// Version    : Toujours '2012-10-17' (version de la syntaxe IAM)",
      "// Sid        : Statement ID, identifiant lisible de l'enonce",
      "// Effect     : 'Allow' ou 'Deny'. DENY l'emporte toujours sur ALLOW",
      "// Action     : Quelles actions AWS (s3:GetObject, ec2:StartInstances, etc.)",
      "// Resource   : Sur quelles ressources (ARN specifique ou * pour tout)",
      "// Condition  : Conditions optionnelles (IP source, MFA, tags, heure, etc.)",
    ]),
    spacer(),
    infoBox("Regle d'or IAM",
      "En cas de conflit entre Allow et Deny : DENY l'emporte TOUJOURS.\nOrdre d'evaluation : 1) Deny explicite -> REFUSE, 2) Allow explicite -> AUTORISE, 3) Aucune regle -> REFUSE (deny implicite par defaut).\nIl n'existe pas de 'Allow par defaut' dans AWS. Tout ce qui n'est pas explicitement autorise est refuse.",
      LIGHT_RED, "C62828"),
    spacer(),

    h2("3.4 Types de Politiques IAM"),
    p("AWS distingue plusieurs types de politiques avec des comportements differents :"),
    spacer(),
    twoColTable(
      ["Type de Politique", "Description"],
      [
        ["Politiques gerees par AWS", "Politiques predefinies par AWS (ex: AmazonS3ReadOnlyAccess, AdministratorAccess). Mises a jour automatiquement par AWS."],
        ["Politiques gerees par le client", "Politiques que vous creez et gerez. Reutilisables sur plusieurs identites. Version history disponible."],
        ["Politiques en ligne (Inline)", "Politiques directement integrees dans une identite. Supprimees avec l'identite. A eviter : difficile a gerer."],
        ["Politiques basees sur les ressources", "Attachees directement a une ressource (bucket S3, fonction Lambda). Permettent le cross-account access."],
        ["Limites de permissions (Permissions Boundaries)", "Definissent le maximum de permissions qu'une identite peut avoir. Utile pour deleguer la creation de roles."],
        ["Politiques de controle des services (SCP)", "Applicable dans AWS Organizations. Limitent les permissions dans tous les comptes d'une organisation."],
      ]
    ),
    spacer(),

    h2("3.5 Les Roles IAM - Concept Cle"),
    p("Les roles IAM sont l'un des concepts les plus importants pour la certification. Contrairement aux utilisateurs, les roles ne sont pas associes a une personne specifique. N'importe quelle entite autorisee peut 'assumer' un role temporairement."),
    spacer(),
    codeBlock([
      "// Structure d'un Role IAM :",
      "//",
      "// 1. POLITIQUE DE CONFIANCE (Trust Policy) - QUI peut assumer ce role",
      "{",
      "  \"Version\": \"2012-10-17\",",
      "  \"Statement\": [{",
      "    \"Effect\": \"Allow\",",
      "    \"Principal\": {",
      "      \"Service\": \"lambda.amazonaws.com\",",
      "      \"AWS\": \"arn:aws:iam::123456789012:root\"",
      "    },",
      "    \"Action\": \"sts:AssumeRole\",",
      "    \"Condition\": {",
      "      \"StringEquals\": {",
      "        \"sts:ExternalId\": \"mon-external-id-secret\"",
      "      }",
      "    }",
      "  }]",
      "}",
      "",
      "// 2. POLITIQUE DE PERMISSIONS - CE QUE le role peut faire",
      "{",
      "  \"Version\": \"2012-10-17\",",
      "  \"Statement\": [{",
      "    \"Effect\": \"Allow\",",
      "    \"Action\": [",
      "      \"s3:GetObject\",",
      "      \"dynamodb:PutItem\",",
      "      \"logs:CreateLogGroup\",",
      "      \"logs:CreateLogStream\",",
      "      \"logs:PutLogEvents\"",
      "    ],",
      "    \"Resource\": \"*\"",
      "  }]",
      "}",
    ]),
    spacer(),
    h3("3.5.1 Cas d'Usage des Roles IAM"),
    twoColTable(
      ["Scenario", "Role IAM"],
      [
        ["Instance EC2 doit acceder a S3", "Attacher un role EC2 avec politique s3:GetObject. Les credentials sont injectes automatiquement via metadata."],
        ["Fonction Lambda doit ecrire dans DynamoDB", "Role d'execution Lambda avec politique dynamodb:PutItem attachee."],
        ["Cross-Account Access (compte A vers compte B)", "Role dans compte B avec Trust Policy autorisant le compte A. Compte A assume le role via STS."],
        ["Developpeur doit acces temporaire en prod", "Role de deploiement assume via MFA. Session de 1 heure max."],
        ["Application on-premise vers AWS", "Role assume via AWS STS avec ExternalId pour securite supplementaire."],
      ]
    ),
    spacer(),

    h2("3.6 ARN - Amazon Resource Name"),
    p("Chaque ressource AWS est identifiee de facon unique par un ARN (Amazon Resource Name). Comprendre la structure des ARN est essentiel pour ecrire des politiques IAM precises."),
    spacer(),
    codeBlock([
      "// Format general d'un ARN :",
      "arn:partition:service:region:account-id:resource-type/resource-id",
      "",
      "// Exemples d'ARN :",
      "arn:aws:s3:::mon-bucket                              // Bucket S3 (pas de region ni compte)",
      "arn:aws:s3:::mon-bucket/images/photo.jpg             // Objet dans un bucket S3",
      "arn:aws:iam::123456789012:user/alice                 // Utilisateur IAM",
      "arn:aws:iam::123456789012:role/lambda-execution-role // Role IAM",
      "arn:aws:lambda:eu-west-1:123456789012:function:ma-fn // Fonction Lambda",
      "arn:aws:dynamodb:eu-west-1:123456789012:table/users  // Table DynamoDB",
      "arn:aws:ec2:eu-west-1:123456789012:instance/i-abc123 // Instance EC2",
      "arn:aws:sqs:eu-west-1:123456789012:ma-queue          // Queue SQS",
      "",
      "// Wildcards dans les ARN de politique :",
      "arn:aws:s3:::mon-bucket/*                            // Tous les objets du bucket",
      "arn:aws:lambda:eu-west-1:*:function:*               // Toutes les lambdas de tous comptes",
      "arn:aws:iam::*:role/developers-*                    // Roles commencant par 'developers-'",
    ]),
    spacer(),

    h2("3.7 Politique de Moindre Privilege"),
    p("Le principe du moindre privilege (Least Privilege) est une bonne pratique fondamentale en securite : n'accorder que les permissions strictement necessaires pour effectuer une tache."),
    spacer(),
    infoBox("Bonne Pratique - Principe du Moindre Privilege",
      "Commencez par refuser tout (*:*), puis ajoutez uniquement les permissions necessaires. Utilisez des ressources specifiques dans l'ARN plutot que '*'. Ajoutez des conditions (IP source, MFA requis, tags) pour limiter l'usage. Revuez regulierement les permissions avec IAM Access Analyzer.",
      LIGHT_GREEN, "2E7D32"),
    spacer(),
    codeBlock([
      "// MAUVAISE pratique : trop permissive",
      "{",
      "  \"Effect\": \"Allow\",",
      "  \"Action\": \"*\",",
      "  \"Resource\": \"*\"",
      "}",
      "",
      "// BONNE pratique : permissions minimales avec ressources specifiques",
      "{",
      "  \"Version\": \"2012-10-17\",",
      "  \"Statement\": [",
      "    {",
      "      \"Sid\": \"AllowSpecificS3Operations\",",
      "      \"Effect\": \"Allow\",",
      "      \"Action\": [",
      "        \"s3:GetObject\",",
      "        \"s3:PutObject\"",
      "      ],",
      "      \"Resource\": \"arn:aws:s3:::mon-app-bucket/uploads/*\",",
      "      \"Condition\": {",
      "        \"Bool\": {",
      "          \"aws:MultiFactorAuthPresent\": \"true\"",
      "        },",
      "        \"StringEquals\": {",
      "          \"aws:RequestedRegion\": \"eu-west-1\"",
      "        }",
      "      }",
      "    },",
      "    {",
      "      \"Sid\": \"AllowDynamoDBItemOperations\",",
      "      \"Effect\": \"Allow\",",
      "      \"Action\": [",
      "        \"dynamodb:GetItem\",",
      "        \"dynamodb:PutItem\",",
      "        \"dynamodb:UpdateItem\"",
      "      ],",
      "      \"Resource\": \"arn:aws:dynamodb:eu-west-1:123456789012:table/reservations\",",
      "      \"Condition\": {",
      "        \"ForAllValues:StringEquals\": {",
      "          \"dynamodb:LeadingKeys\": [\"${aws:username}\"]",
      "        }",
      "      }",
      "    }",
      "  ]",
      "}",
    ]),
    spacer(),

    h2("3.8 Tester les Permissions IAM"),
    h3("3.8.1 Simulateur de Politiques IAM"),
    p("AWS fournit le simulateur de politiques IAM (Policy Simulator) accessible via la console AWS ou l'API. Il permet de tester des politiques sans les appliquer reellement."),
    spacer(),
    codeBlock([
      "# Tester une permission via AWS CLI (IAM Policy Simulator API)",
      "aws iam simulate-principal-policy \\",
      "  --policy-source-arn 'arn:aws:iam::123456789012:user/alice' \\",
      "  --action-names 's3:GetObject' 's3:PutObject' 's3:DeleteObject' \\",
      "  --resource-arns 'arn:aws:s3:::mon-bucket/uploads/test.pdf'",
      "",
      "# Resultat :",
      "# {",
      "#   'EvaluationResults': [",
      "#     {",
      "#       'EvalActionName': 's3:GetObject',",
      "#       'EvalDecision': 'allowed',",
      "#       'MatchedStatements': [...]",
      "#     },",
      "#     {",
      "#       'EvalActionName': 's3:DeleteObject',",
      "#       'EvalDecision': 'implicitDeny',",
      "#       'MatchedStatements': []",
      "#     }",
      "#   ]",
      "# }",
      "",
      "# Verifier l'identite actuelle",
      "aws sts get-caller-identity",
      "",
      "# Lister les politiques attachees a un utilisateur",
      "aws iam list-attached-user-policies --user-name alice",
      "",
      "# Voir le detail d'une politique",
      "aws iam get-policy --policy-arn 'arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess'",
    ]),
    spacer(),
    h3("3.8.2 IAM Access Analyzer"),
    p("IAM Access Analyzer est un outil qui identifie les ressources partagees avec des entites externes a votre organisation (risque potentiel de securite)."),
    spacer(),
    codeBlock([
      "# Creer un analyseur IAM Access Analyzer",
      "aws accessanalyzer create-analyzer \\",
      "  --analyzer-name mon-analyseur \\",
      "  --type ACCOUNT",
      "",
      "# Lister les acces potentiellement problematiques detectes",
      "aws accessanalyzer list-findings \\",
      "  --analyzer-arn 'arn:aws:access-analyzer:eu-west-1:123456789012:analyzer/mon-analyseur'",
      "",
      "# Exemple de resultat problematique :",
      "# Bucket S3 'mon-bucket' est accessible depuis n'importe quel compte AWS",
      "# Role IAM 'mon-role' peut etre assume par un compte externe non reconnu",
    ]),
    spacer(),

    h2("3.9 MFA - Authentification Multi-Facteurs"),
    p("L'activation du MFA (Multi-Factor Authentication) ajoute une couche de securite supplementaire. AWS supporte les MFA materiels et logiciels."),
    spacer(),
    codeBlock([
      "# Exiger le MFA pour des operations sensibles dans une politique",
      "{",
      "  \"Version\": \"2012-10-17\",",
      "  \"Statement\": [",
      "    {",
      "      \"Sid\": \"DenyWithoutMFA\",",
      "      \"Effect\": \"Deny\",",
      "      \"Action\": [",
      "        \"s3:DeleteBucket\",",
      "        \"s3:DeleteObject\",",
      "        \"iam:CreateUser\",",
      "        \"iam:AttachUserPolicy\"",
      "      ],",
      "      \"Resource\": \"*\",",
      "      \"Condition\": {",
      "        \"BoolIfExists\": {",
      "          \"aws:MultiFactorAuthPresent\": \"false\"",
      "        }",
      "      }",
      "    }",
      "  ]",
      "}",
      "",
      "# Configurer MFA via CLI",
      "# 1. Creer un device MFA virtuel",
      "aws iam create-virtual-mfa-device \\",
      "  --virtual-mfa-device-name MonDevice \\",
      "  --outfile QRCode.png \\",
      "  --bootstrap-method QRCodePNG",
      "",
      "# 2. Scanner le QR code avec Google Authenticator ou Authy",
      "# 3. Activer le device avec deux codes consecutifs",
      "aws iam enable-mfa-device \\",
      "  --user-name alice \\",
      "  --serial-number arn:aws:iam::123456789012:mfa/MonDevice \\",
      "  --authentication-code1 123456 \\",
      "  --authentication-code2 789012",
    ]),
    spacer(),

    h2("3.10 Configurations des Roles pour le Developpement Java"),
    p("Voici comment configurer les roles IAM pour les scenarios de developpement les plus courants avec Java :"),
    spacer(),
    h3("3.10.1 Role pour Fonction Lambda"),
    codeBlock([
      "// Politique pour un role de fonction Lambda - Acces S3 + DynamoDB + Logs",
      "// Nom suggere : lambda-reservation-service-role",
      "",
      "{",
      "  \"Version\": \"2012-10-17\",",
      "  \"Statement\": [",
      "    {",
      "      \"Sid\": \"CloudWatchLogs\",",
      "      \"Effect\": \"Allow\",",
      "      \"Action\": [",
      "        \"logs:CreateLogGroup\",",
      "        \"logs:CreateLogStream\",",
      "        \"logs:PutLogEvents\"",
      "      ],",
      "      \"Resource\": \"arn:aws:logs:*:*:*\"",
      "    },",
      "    {",
      "      \"Sid\": \"DynamoDBOperations\",",
      "      \"Effect\": \"Allow\",",
      "      \"Action\": [",
      "        \"dynamodb:GetItem\",",
      "        \"dynamodb:PutItem\",",
      "        \"dynamodb:UpdateItem\",",
      "        \"dynamodb:DeleteItem\",",
      "        \"dynamodb:Query\",",
      "        \"dynamodb:Scan\"",
      "      ],",
      "      \"Resource\": [",
      "        \"arn:aws:dynamodb:eu-west-1:123456789012:table/reservations\",",
      "        \"arn:aws:dynamodb:eu-west-1:123456789012:table/reservations/index/*\"",
      "      ]",
      "    },",
      "    {",
      "      \"Sid\": \"S3Operations\",",
      "      \"Effect\": \"Allow\",",
      "      \"Action\": [",
      "        \"s3:GetObject\",",
      "        \"s3:PutObject\"",
      "      ],",
      "      \"Resource\": \"arn:aws:s3:::mon-app-bucket/*\"",
      "    },",
      "    {",
      "      \"Sid\": \"XRayTracing\",",
      "      \"Effect\": \"Allow\",",
      "      \"Action\": [",
      "        \"xray:PutTraceSegments\",",
      "        \"xray:PutTelemetryRecords\"",
      "      ],",
      "      \"Resource\": \"*\"",
      "    }",
      "  ]",
      "}",
    ]),
    spacer(),
    h3("3.10.2 Attacher un Role a une Fonction Lambda en Java"),
    codeBlock([
      "package com.monapp.iam;",
      "",
      "import software.amazon.awssdk.services.iam.IamClient;",
      "import software.amazon.awssdk.services.iam.model.*;",
      "import software.amazon.awssdk.services.lambda.LambdaClient;",
      "import software.amazon.awssdk.services.lambda.model.*;",
      "import software.amazon.awssdk.regions.Region;",
      "",
      "public class IAMRoleManager {",
      "",
      "    private final IamClient iamClient;",
      "",
      "    public IAMRoleManager() {",
      "        // IAM est un service global - utiliser US_EAST_1",
      "        this.iamClient = IamClient.builder()",
      "            .region(Region.AWS_GLOBAL)",
      "            .build();",
      "    }",
      "",
      "    // Creer un role d'execution Lambda",
      "    public String createLambdaExecutionRole(String roleName) {",
      "        String trustPolicy = '{' +",
      "            '\"Version\": \"2012-10-17\",' +",
      "            '\"Statement\": [{' +",
      "            '  \"Effect\": \"Allow\",' +",
      "            '  \"Principal\": {\"Service\": \"lambda.amazonaws.com\"},' +",
      "            '  \"Action\": \"sts:AssumeRole\"' +",
      "            '}]' +",
      "        '}';" ,
      "",
      "        CreateRoleResponse createRoleResponse = iamClient.createRole(",
      "            CreateRoleRequest.builder()",
      "                .roleName(roleName)",
      "                .assumeRolePolicyDocument(trustPolicy)",
      "                .description('Role d execution pour Lambda - Service Reservations')",
      "                .maxSessionDuration(3600) // 1 heure max",
      "                .build()",
      "        );",
      "",
      "        // Attacher la politique geree AWSLambdaBasicExecutionRole",
      "        iamClient.attachRolePolicy(AttachRolePolicyRequest.builder()",
      "            .roleName(roleName)",
      "            .policyArn('arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole')",
      "            .build());",
      "",
      "        System.out.println('Role cree: ' + createRoleResponse.role().arn());",
      "        return createRoleResponse.role().arn();",
      "    }",
      "",
      "    // Attendre que le role soit propagé (AWS IAM a une latence de propagation)",
      "    public void waitForRolePropagation() throws InterruptedException {",
      "        Thread.sleep(10000); // Attendre 10 secondes (eventual consistency IAM)",
      "    }",
      "}",
    ]),
    spacer(),

    h2("3.11 Lab : Configurer les Permissions IAM"),
    infoBox("Objectif du Lab",
      "Creer une structure IAM complete pour une application de reservation : groupe d'utilisateurs developpeurs, role Lambda, politique S3 restrictive, et valider les permissions avec le Policy Simulator.",
      LIGHT_BLUE, BLUE),
    spacer(),
    h3("Etape 1 : Creer un Groupe et des Utilisateurs"),
    codeBlock([
      "# Creer le groupe 'developers'",
      "aws iam create-group --group-name developers",
      "",
      "# Attacher une politique geree au groupe",
      "aws iam attach-group-policy \\",
      "  --group-name developers \\",
      "  --policy-arn arn:aws:iam::aws:policy/AWSCloud9User",
      "",
      "# Creer un utilisateur et l'ajouter au groupe",
      "aws iam create-user --user-name dev-java-01",
      "aws iam add-user-to-group --user-name dev-java-01 --group-name developers",
      "",
      "# Creer des Access Keys pour cet utilisateur",
      "aws iam create-access-key --user-name dev-java-01",
    ]),
    spacer(),
    h3("Etape 2 : Creer une Politique Personnalisee"),
    codeBlock([
      "# Creer la politique dans un fichier JSON",
      "cat > politique-dev.json << 'EOF'",
      "{",
      "  \"Version\": \"2012-10-17\",",
      "  \"Statement\": [",
      "    {",
      "      \"Effect\": \"Allow\",",
      "      \"Action\": [\"s3:*\"],",
      "      \"Resource\": \"arn:aws:s3:::dev-bucket-*\"",
      "    },",
      "    {",
      "      \"Effect\": \"Allow\",",
      "      \"Action\": [\"dynamodb:*\"],",
      "      \"Resource\": \"arn:aws:dynamodb:eu-west-1:*:table/dev-*\"",
      "    },",
      "    {",
      "      \"Effect\": \"Allow\",",
      "      \"Action\": [\"lambda:*\"],",
      "      \"Resource\": \"arn:aws:lambda:eu-west-1:*:function:dev-*\"",
      "    }",
      "  ]",
      "}",
      "EOF",
      "",
      "# Creer la politique dans AWS",
      "aws iam create-policy \\",
      "  --policy-name DeveloperAppPolicy \\",
      "  --policy-document file://politique-dev.json",
    ]),
    spacer(),

    h2("3.12 Questions de Revision - Module 3"),
    infoBox("Question 1",
      "Un role IAM a une politique Allow pour s3:DeleteObject. Une politique SCP au niveau Organisation a une politique Deny pour s3:DeleteObject. Quelle est l'action resultante ?\nA) L'action est autorisee car Allow est explicite\nB) L'action est refusee car Deny l'emporte toujours sur Allow\nC) Le comportement depend de l'ordre d'evaluation\nD) La SCP n'affecte pas les roles IAM\nReponse correcte : B - Le Deny explicite (que ce soit dans une SCP, politique de ressource, ou politique d'identite) l'emporte toujours sur tout Allow. Les SCP limitent le maximum de permissions meme si le role IAM les autorise.",
      LIGHT_ORANGE, ORANGE),
    spacer(),
    infoBox("Question 2",
      "Quelle est la difference entre une politique geree par AWS (AWS Managed Policy) et une politique geree par le client (Customer Managed Policy) ?\nA) Les politiques gerees par AWS peuvent etre modifiees, pas celles du client\nB) Les politiques gerees par le client offrent plus de controle et de versions, AWS Managed sont predefinies et mises a jour par AWS\nC) Il n'y a pas de difference fonctionnelle\nD) Les politiques du client ne peuvent pas etre attachees aux roles\nReponse correcte : B - Les Customer Managed Policies vous donnent un controle total (modification, versioning, suppression). Les AWS Managed Policies sont predefinies pour les cas d'usage courants et mises a jour automatiquement par AWS quand de nouvelles API sont ajoutees.",
      LIGHT_ORANGE, ORANGE),
    spacer(),

    h2("3.13 Resume du Module"),
    bullet("IAM est compose de : utilisateurs, groupes, roles et politiques JSON"),
    bullet("La structure d'une politique : Version, Statement, Effect, Action, Resource, Condition"),
    bullet("Deny explicite l'emporte TOUJOURS sur Allow - pas d'exception"),
    bullet("Les roles IAM sont preferes aux utilisateurs pour les services AWS (EC2, Lambda)"),
    bullet("Le principe du moindre privilege : n'accordez que le strict necessaire"),
    bullet("IAM Access Analyzer detecte les acces externes non intentionnels"),
    bullet("Le MFA doit etre active pour tous les utilisateurs, surtout les administrateurs"),
    spacer(),
  ];
}

// ============================================================
// MODULE 4: Amazon S3 - Stockage
// ============================================================
function module4() {
  return [
    pageBreak(),
    h1("MODULE 4 : Premiers Pas avec le Stockage Amazon S3"),
    spacer(),
    p("Amazon Simple Storage Service (S3) est le service de stockage d'objets d'AWS. Avec une durabilite de 99.999999999% (11 nines), S3 est concu pour stocker des volumes illimites de donnees de n'importe quel type. C'est l'un des premiers services AWS et le plus utilise.", { size: 22 }),
    spacer(),

    h2("4.1 Objectifs d'Apprentissage"),
    bullet("Comprendre les concepts fondamentaux de S3 : buckets, objets, cles"),
    bullet("Identifier et configurer les options de stockage et de securite S3"),
    bullet("Utiliser le SDK Java v2 pour interagir avec S3"),
    bullet("Comprendre les classes de stockage et leur impact sur les couts"),
    bullet("Implementer les patterns de requete/reponse S3 en Java"),
    spacer(),

    h2("4.2 Concepts Fondamentaux S3"),
    h3("4.2.1 Buckets"),
    p("Un bucket S3 est un conteneur de stockage identifie par un nom unique global. Les buckets sont crees dans une region specifique mais accessibles globalement."),
    spacer(),
    multiColTable(
      ["Caracteristique", "Valeur", "Notes"],
      [2800, 2000, 4560],
      [
        ["Nom unique", "Global AWS", "Aucun autre bucket dans le monde ne peut avoir le meme nom"],
        ["Taille max", "Illimitee", "Aucune limite de taille pour un bucket"],
        ["Objets par bucket", "Illimite", "Aucune limite du nombre d'objets"],
        ["Buckets par compte", "100 par defaut", "Augmentable via Service Quotas (max 1000)"],
        ["Regions", "Bucket fixe dans une region", "Les donnees ne quittent pas la region sans replication"],
        ["Durabili  te", "99.999999999%", "11 nines, equivalent a perdre 1 objet / 10 milliards / an"],
      ]
    ),
    spacer(),
    h3("4.2.2 Objets"),
    p("Un objet est la donnee stockee dans S3. Il est compose d'une cle (nom), d'une valeur (donnee binaire), de metadonnees et eventuellement d'un tag."),
    spacer(),
    twoColTable(
      ["Composant", "Description"],
      [
        ["Cle (Key)", "Nom unique de l'objet dans le bucket. Peut simuler une hierarchie de dossiers avec '/' (ex: 'images/2024/photo.jpg')."],
        ["Valeur (Value)", "Contenu binaire de l'objet. De 0 byte a 5 TB. Les objets > 5 GB doivent utiliser Multipart Upload."],
        ["Version ID", "Identifiant unique d'une version si le versioning est active sur le bucket."],
        ["Metadonnees systeme", "Content-Type, Content-Length, ETag (hash MD5), Last-Modified. Definies par S3."],
        ["Metadonnees utilisateur", "Paires cle-valeur personnalisees (max 2 KB). Prefixees par 'x-amz-meta-'."],
        ["Tags", "Jusqu'a 10 paires cle-valeur. Utiles pour la facturation et les politiques IAM."],
        ["ACL", "Liste de controle d'acces. Deconseille au profit des politiques de bucket."],
      ]
    ),
    spacer(),
    infoBox("Astuce Certification DVA-C02",
      "S3 n'est pas un systeme de fichiers traditionnel ! Il n'y a pas de vrais 'dossiers'. La cle 'images/2024/photo.jpg' est juste une chaine de caracteres. Le '/' est utilise par la console AWS pour afficher une hierarchie visuelle, mais sous le capot c'est un espace de noms plat. Cette distinction est importante pour les questions sur les performances S3.",
      LIGHT_ORANGE, ORANGE),
    spacer(),

    h2("4.3 Classes de Stockage S3"),
    p("S3 offre plusieurs classes de stockage avec differents rapports disponibilite/cout. Choisir la bonne classe est important pour optimiser les couts."),
    spacer(),
    multiColTable(
      ["Classe de Stockage", "Disponibilite", "Duree Min", "Cas d'Usage"],
      [2400, 1800, 1500, 3660],
      [
        ["S3 Standard", "99.99%", "Aucune", "Donnees frequemment accedees. Latence ms. Cout stockage: $/GB/mois le plus eleve."],
        ["S3 Intelligent-Tiering", "99.9%", "30 jours", "Acces impredictible. Deplace automatiquement entre tiers selon l'usage."],
        ["S3 Standard-IA", "99.9%", "30 jours", "Acces peu frequent mais recuperation rapide. 40% moins cher que Standard."],
        ["S3 One Zone-IA", "99.5%", "30 jours", "Acces peu frequent, donnees recreables. Stocke dans 1 AZ uniquement."],
        ["S3 Glacier Instant", "99.9%", "90 jours", "Archives avec recuperation en millisecondes. Moins cher que Standard-IA."],
        ["S3 Glacier Flexible", "99.99%", "90 jours", "Archives. Recuperation en 1-12 heures. Tres economique."],
        ["S3 Glacier Deep Archive", "99.99%", "180 jours", "Archivage long terme. Recuperation en 12-48h. Le moins cher de S3."],
      ]
    ),
    spacer(),
    h3("4.3.1 Regles de Cycle de Vie (Lifecycle Rules)"),
    p("Les regles de cycle de vie permettent de transitionner automatiquement les objets entre classes de stockage ou de les supprimer apres une certaine duree."),
    spacer(),
    codeBlock([
      "// Configurer une regle de cycle de vie via SDK Java",
      "import software.amazon.awssdk.services.s3.model.*;",
      "",
      "public class S3LifecycleExample {",
      "",
      "    public void configureLifecycle(S3Client s3, String bucket) {",
      "        // Regle : transition Standard -> Standard-IA apres 30j -> Glacier apres 90j -> Supprime apres 365j",
      "        LifecycleRule rule = LifecycleRule.builder()",
      "            .id('archive-old-uploads')",
      "            .status(ExpirationStatus.ENABLED)",
      "            .filter(LifecycleRuleFilter.builder()",
      "                .prefix('uploads/')  // S'applique seulement aux objets sous 'uploads/'",
      "                .build()",
      "            )",
      "            .transitions(",
      "                // Transition vers Standard-IA apres 30 jours",
      "                Transition.builder()",
      "                    .days(30)",
      "                    .storageClass(TransitionStorageClass.STANDARD_IA)",
      "                    .build(),",
      "                // Transition vers Glacier Flexible apres 90 jours",
      "                Transition.builder()",
      "                    .days(90)",
      "                    .storageClass(TransitionStorageClass.GLACIER)",
      "                    .build()",
      "            )",
      "            // Suppression definitive apres 365 jours",
      "            .expiration(LifecycleExpiration.builder()",
      "                .days(365)",
      "                .build()",
      "            )",
      "            .build();",
      "",
      "        s3.putBucketLifecycleConfiguration(",
      "            PutBucketLifecycleConfigurationRequest.builder()",
      "                .bucket(bucket)",
      "                .lifecycleConfiguration(",
      "                    BucketLifecycleConfiguration.builder()",
      "                        .rules(rule)",
      "                        .build()",
      "                )",
      "                .build()",
      "        );",
      "        System.out.println('Regles de cycle de vie configurees avec succes');",
      "    }",
      "}",
    ]),
    spacer(),

    h2("4.4 Securite S3"),
    h3("4.4.1 Blocage de l'Acces Public"),
    p("Par defaut, tous les nouveaux buckets S3 sont prives et l'acces public est bloque. C'est une protection importante introduite suite aux nombreuses fuites de donnees."),
    spacer(),
    codeBlock([
      "// Verifier et configurer le blocage de l'acces public",
      "import software.amazon.awssdk.services.s3.model.*;",
      "",
      "public class S3SecurityExample {",
      "",
      "    // Bloquer TOUT acces public (recommande pour les buckets de donnees sensibles)",
      "    public void blockAllPublicAccess(S3Client s3, String bucket) {",
      "        s3.putPublicAccessBlock(",
      "            PutPublicAccessBlockRequest.builder()",
      "                .bucket(bucket)",
      "                .publicAccessBlockConfiguration(",
      "                    PublicAccessBlockConfiguration.builder()",
      "                        .blockPublicAcls(true)      // Bloque les nouvelles ACLs publiques",
      "                        .ignorePublicAcls(true)    // Ignore les ACLs publiques existantes",
      "                        .blockPublicPolicy(true)   // Bloque les politiques rendant le bucket public",
      "                        .restrictPublicBuckets(true) // Restreint l'acces public meme si politique existe",
      "                        .build()",
      "                )",
      "                .build()",
      "        );",
      "    }",
      "",
      "    // Politique de bucket qui oblige le chiffrement en transit (HTTPS uniquement)",
      "    public void enforceHTTPS(S3Client s3, String bucket, String accountId) {",
      "        String policy = String.format(",
      "            '{\"Version\":\"2012-10-17\",\"Statement\":[{' +",
      "            '\"Sid\":\"DenyNonHTTPS\",' +",
      "            '\"Effect\":\"Deny\",' +",
      "            '\"Principal\":\"*\",' +",
      "            '\"Action\":\"s3:*\",' +",
      "            '\"Resource\":[\"arn:aws:s3:::%s\",\"arn:aws:s3:::%s/*\"],' +",
      "            '\"Condition\":{\"Bool\":{\"aws:SecureTransport\":\"false\"}}' +",
      "            '}]}', bucket, bucket);",
      "",
      "        s3.putBucketPolicy(",
      "            PutBucketPolicyRequest.builder()",
      "                .bucket(bucket)",
      "                .policy(policy)",
      "                .build()",
      "        );",
      "    }",
      "}",
    ]),
    spacer(),
    h3("4.4.2 Chiffrement S3"),
    p("S3 supporte plusieurs methodes de chiffrement des donnees au repos :"),
    spacer(),
    multiColTable(
      ["Methode", "Description", "Gestion des cles"],
      [2000, 4000, 3360],
      [
        ["SSE-S3", "Server-Side Encryption with S3-Managed Keys. Chiffrement AES-256 automatique.", "AWS gere tout automatiquement"],
        ["SSE-KMS", "Server-Side Encryption with AWS KMS Keys. Utilise AWS Key Management Service.", "AWS KMS, vous controlez les cles"],
        ["SSE-C", "Server-Side Encryption with Customer Keys. Vous fournissez la cle a chaque requete.", "Vous gerez et fournissez les cles"],
        ["CSE", "Client-Side Encryption. Chiffrement avant d'envoyer a S3.", "Vous chiffrez et dechiffrez tout"],
      ]
    ),
    spacer(),
    codeBlock([
      "// Uploader un objet avec chiffrement SSE-KMS",
      "import software.amazon.awssdk.core.sync.RequestBody;",
      "import software.amazon.awssdk.services.s3.model.*;",
      "",
      "public class S3EncryptionExample {",
      "",
      "    public void uploadWithKMSEncryption(S3Client s3, String bucket,",
      "                                         String key, byte[] data,",
      "                                         String kmsKeyId) {",
      "        PutObjectRequest request = PutObjectRequest.builder()",
      "            .bucket(bucket)",
      "            .key(key)",
      "            .serverSideEncryption(ServerSideEncryption.AWS_KMS)",
      "            .ssekmsKeyId(kmsKeyId) // ARN ou alias de la cle KMS",
      "            .contentType('application/pdf')",
      "            .build();",
      "",
      "        s3.putObject(request, RequestBody.fromBytes(data));",
      "        System.out.println('Objet uploade avec chiffrement KMS');",
      "    }",
      "",
      "    // Activer le chiffrement par defaut sur un bucket",
      "    public void enableDefaultEncryption(S3Client s3, String bucket, String kmsKeyArn) {",
      "        s3.putBucketEncryption(",
      "            PutBucketEncryptionRequest.builder()",
      "                .bucket(bucket)",
      "                .serverSideEncryptionConfiguration(",
      "                    ServerSideEncryptionConfiguration.builder()",
      "                        .rules(ServerSideEncryptionRule.builder()",
      "                            .applyServerSideEncryptionByDefault(",
      "                                ServerSideEncryptionByDefault.builder()",
      "                                    .sseAlgorithm(ServerSideEncryption.AWS_KMS)",
      "                                    .kmsMasterKeyId(kmsKeyArn)",
      "                                    .build()",
      "                            )",
      "                            .bucketKeyEnabled(true) // Reduit les couts KMS",
      "                            .build()",
      "                        )",
      "                        .build()",
      "                )",
      "                .build()",
      "        );",
      "    }",
      "}",
    ]),
    spacer(),

    h2("4.5 Operations de Base avec le SDK Java v2"),
    h3("4.5.1 CRUD Complet S3"),
    codeBlock([
      "package com.monapp.s3;",
      "",
      "import software.amazon.awssdk.core.ResponseBytes;",
      "import software.amazon.awssdk.core.sync.RequestBody;",
      "import software.amazon.awssdk.services.s3.S3Client;",
      "import software.amazon.awssdk.services.s3.model.*;",
      "import java.io.*;",
      "import java.nio.file.Path;",
      "import java.util.Map;",
      "",
      "public class S3CrudService {",
      "",
      "    private final S3Client s3;",
      "    private final String bucket;",
      "",
      "    public S3CrudService(S3Client s3, String bucket) {",
      "        this.s3 = s3;",
      "        this.bucket = bucket;",
      "    }",
      "",
      "    // CREATE - Uploader un objet depuis byte array",
      "    public void uploadBytes(String key, byte[] data, String contentType) {",
      "        PutObjectRequest request = PutObjectRequest.builder()",
      "            .bucket(bucket)",
      "            .key(key)",
      "            .contentType(contentType)",
      "            .contentLength((long) data.length)",
      "            .serverSideEncryption(ServerSideEncryption.AES256)", // SSE-S3",
      "            .metadata(Map.of(",
      "                'uploaded-by', 'java-app',",
      "                'version', '1.0'",
      "            ))",
      "            .build();",
      "",
      "        PutObjectResponse response = s3.putObject(request, RequestBody.fromBytes(data));",
      "        System.out.println('Uploade - ETag: ' + response.eTag());",
      "    }",
      "",
      "    // CREATE - Uploader depuis un fichier local (efficace pour gros fichiers)",
      "    public void uploadFile(String key, Path filePath) throws IOException {",
      "        PutObjectRequest request = PutObjectRequest.builder()",
      "            .bucket(bucket)",
      "            .key(key)",
      "            .build();",
      "",
      "        s3.putObject(request, RequestBody.fromFile(filePath));",
      "    }",
      "",
      "    // READ - Telecharger un objet en memoire",
      "    public byte[] downloadBytes(String key) {",
      "        GetObjectRequest request = GetObjectRequest.builder()",
      "            .bucket(bucket)",
      "            .key(key)",
      "            .build();",
      "",
      "        ResponseBytes<GetObjectResponse> responseBytes = s3.getObjectAsBytes(request);",
      "",
      "        // Afficher les metadonnees",
      "        GetObjectResponse response = responseBytes.response();",
      "        System.out.println('Content-Type: ' + response.contentType());",
      "        System.out.println('Taille: ' + response.contentLength() + ' bytes');",
      "        System.out.println('Modifie: ' + response.lastModified());",
      "        System.out.println('Metadonnees: ' + response.metadata());",
      "",
      "        return responseBytes.asByteArray();",
      "    }",
      "",
      "    // READ - Telecharger vers un fichier local",
      "    public void downloadToFile(String key, Path destination) {",
      "        GetObjectRequest request = GetObjectRequest.builder()",
      "            .bucket(bucket)",
      "            .key(key)",
      "            .build();",
      "",
      "        s3.getObject(request, destination);",
      "    }",
      "",
      "    // UPDATE - Copier un objet (peut changer la classe de stockage, metadonnees)",
      "    public void copyObject(String sourceKey, String destinationKey) {",
      "        CopyObjectRequest request = CopyObjectRequest.builder()",
      "            .sourceBucket(bucket)",
      "            .sourceKey(sourceKey)",
      "            .destinationBucket(bucket)",
      "            .destinationKey(destinationKey)",
      "            .storageClass(StorageClass.STANDARD_IA) // Changer la classe",
      "            .build();",
      "",
      "        s3.copyObject(request);",
      "    }",
      "",
      "    // DELETE - Supprimer un objet",
      "    public void deleteObject(String key) {",
      "        s3.deleteObject(DeleteObjectRequest.builder()",
      "            .bucket(bucket)",
      "            .key(key)",
      "            .build());",
      "    }",
      "",
      "    // DELETE - Supprimer plusieurs objets en une requete (max 1000)",
      "    public void deleteBatch(java.util.List<String> keys) {",
      "        java.util.List<ObjectIdentifier> objects = keys.stream()",
      "            .map(k -> ObjectIdentifier.builder().key(k).build())",
      "            .collect(java.util.stream.Collectors.toList());",
      "",
      "        DeleteObjectsRequest request = DeleteObjectsRequest.builder()",
      "            .bucket(bucket)",
      "            .delete(Delete.builder()",
      "                .objects(objects)",
      "                .quiet(false) // true = retourne seulement les erreurs",
      "                .build()",
      "            )",
      "            .build();",
      "",
      "        DeleteObjectsResponse response = s3.deleteObjects(request);",
      "        System.out.println('Supprimes: ' + response.deleted().size());",
      "        System.out.println('Erreurs: ' + response.errors().size());",
      "    }",
      "",
      "    // LIST - Lister les objets avec prefix",
      "    public void listObjects(String prefix) {",
      "        ListObjectsV2Request request = ListObjectsV2Request.builder()",
      "            .bucket(bucket)",
      "            .prefix(prefix)",
      "            .maxKeys(1000)",
      "            .build();",
      "",
      "        s3.listObjectsV2Paginator(request)",
      "            .contents()",
      "            .forEach(obj -> System.out.printf(\"%-60s %10d bytes%n\",",
      "                obj.key(), obj.size()));",
      "    }",
      "",
      "    // EXISTS - Verifier si un objet existe",
      "    public boolean objectExists(String key) {",
      "        try {",
      "            s3.headObject(HeadObjectRequest.builder()",
      "                .bucket(bucket)",
      "                .key(key)",
      "                .build());",
      "            return true;",
      "        } catch (NoSuchKeyException e) {",
      "            return false;",
      "        }",
      "    }",
      "}",
    ]),
    spacer(),

    h2("4.6 Versioning S3"),
    p("Le versioning S3 conserve toutes les versions d'un objet, permettant la recuperation en cas de suppression accidentelle."),
    spacer(),
    codeBlock([
      "// Activer le versioning sur un bucket",
      "s3.putBucketVersioning(PutBucketVersioningRequest.builder()",
      "    .bucket(bucket)",
      "    .versioningConfiguration(VersioningConfiguration.builder()",
      "        .status(BucketVersioningStatus.ENABLED)",
      "        .build())",
      "    .build());",
      "",
      "// Lister toutes les versions d'un objet",
      "ListObjectVersionsResponse versions = s3.listObjectVersions(",
      "    ListObjectVersionsRequest.builder()",
      "        .bucket(bucket)",
      "        .prefix('mon-fichier.pdf')",
      "        .build());",
      "",
      "versions.versions().forEach(v -> {",
      "    System.out.println('Version: ' + v.versionId());",
      "    System.out.println('Date: ' + v.lastModified());",
      "    System.out.println('Taille: ' + v.size());",
      "    System.out.println('Courante: ' + v.isLatest());",
      "});",
      "",
      "// Recuperer une version specifique",
      "GetObjectRequest request = GetObjectRequest.builder()",
      "    .bucket(bucket)",
      "    .key('mon-fichier.pdf')",
      "    .versionId('KLLkjhkjhkjhkjhkjhkjhkjh')",
      "    .build();",
    ]),
    spacer(),

    h2("4.7 Lab : Developper avec Amazon S3"),
    infoBox("Objectif du Lab",
      "Creer une application Java complete qui gere le stockage de fichiers dans S3 : creation de bucket, upload avec metadonnees, download, listing avec pagination, gestion des permissions et mise en place du versioning.",
      LIGHT_BLUE, BLUE),
    spacer(),
    h3("Etape 1 : Creer et Configurer le Bucket"),
    codeBlock([
      "package com.monapp.lab;",
      "",
      "import software.amazon.awssdk.regions.Region;",
      "import software.amazon.awssdk.services.s3.S3Client;",
      "import software.amazon.awssdk.services.s3.model.*;",
      "",
      "public class S3LabSetup {",
      "",
      "    public static void main(String[] args) {",
      "        S3Client s3 = S3Client.builder()",
      "            .region(Region.EU_WEST_1)",
      "            .build();",
      "",
      "        String bucket = 'mon-lab-bucket-' + System.currentTimeMillis();",
      "",
      "        // 1. Creer le bucket",
      "        s3.createBucket(CreateBucketRequest.builder()",
      "            .bucket(bucket)",
      "            .createBucketConfiguration(CreateBucketConfiguration.builder()",
      "                .locationConstraint(BucketLocationConstraint.EU_WEST_1)",
      "                .build())",
      "            .build());",
      "        System.out.println('Bucket cree: ' + bucket);",
      "",
      "        // 2. Activer le versioning",
      "        s3.putBucketVersioning(PutBucketVersioningRequest.builder()",
      "            .bucket(bucket)",
      "            .versioningConfiguration(VersioningConfiguration.builder()",
      "                .status(BucketVersioningStatus.ENABLED)",
      "                .build())",
      "            .build());",
      "",
      "        // 3. Configurer le chiffrement par defaut",
      "        s3.putBucketEncryption(PutBucketEncryptionRequest.builder()",
      "            .bucket(bucket)",
      "            .serverSideEncryptionConfiguration(",
      "                ServerSideEncryptionConfiguration.builder()",
      "                    .rules(ServerSideEncryptionRule.builder()",
      "                        .applyServerSideEncryptionByDefault(",
      "                            ServerSideEncryptionByDefault.builder()",
      "                                .sseAlgorithm(ServerSideEncryption.AES256)",
      "                                .build())",
      "                        .build())",
      "                    .build())",
      "            .build());",
      "",
      "        System.out.println('Configuration completee pour: ' + bucket);",
      "        s3.close();",
      "    }",
      "}",
    ]),
    spacer(),

    h2("4.8 Questions de Revision - Module 4"),
    infoBox("Question 1",
      "Une entreprise stocke des logs d'application dans S3. Les logs sont accedes frequemment pendant les 7 premiers jours, rarement entre 7 et 30 jours, et doivent etre archives pendant 7 ans. Quelle configuration S3 optimise les couts ?\nA) S3 Standard pour tous les logs\nB) S3 Standard 7 jours -> Standard-IA 30 jours -> Glacier Deep Archive avec regles de cycle de vie\nC) S3 One Zone-IA pour tous les logs\nD) S3 Intelligent-Tiering uniquement\nReponse correcte : B - Les regles de cycle de vie permettent de transitionner automatiquement. Standard pour l'acces frequent, Standard-IA pour l'acces occasionnel, Glacier Deep Archive pour l'archivage long terme au cout le plus bas.",
      LIGHT_ORANGE, ORANGE),
    spacer(),

    h2("4.9 Resume du Module"),
    bullet("S3 stocke des objets (jusqu'a 5TB) dans des buckets avec des noms globalement uniques"),
    bullet("7 classes de stockage disponibles selon la frequence d'acces et les couts acceptables"),
    bullet("Le versioning protege contre les suppressions accidentelles"),
    bullet("3 options de chiffrement : SSE-S3 (gere par AWS), SSE-KMS (cles KMS), SSE-C (vos cles)"),
    bullet("Le blocage de l'acces public est active par defaut depuis 2023"),
    bullet("Les regles de cycle de vie automatisent les transitions entre classes de stockage"),
    spacer(),
  ];
}

// GENERER LE DOCUMENT PART 2
async function generatePart2() {
  console.log('Generation Part 2 (Modules 3 & 4)...');
  const content = [
    ...module3(),
    ...module4(),
  ];

  const doc = new Document({
    numbering: {
      config: [
        { reference: "bullets", levels: [{ level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } }, run: { font: "Symbol" } } }] },
        { reference: "numbers", levels: [{ level: 0, format: LevelFormat.DECIMAL, text: "%1.", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } }] },
      ]
    },
    styles: {
      default: { document: { run: { font: "Arial", size: 22 } } },
      paragraphStyles: [
        { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 40, bold: true, font: "Arial", color: BLUE }, paragraph: { spacing: { before: 480, after: 240 }, outlineLevel: 0, border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: ORANGE } } } },
        { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 32, bold: true, font: "Arial", color: BLUE }, paragraph: { spacing: { before: 320, after: 160 }, outlineLevel: 1 } },
        { id: "Heading3", name: "Heading 3", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 26, bold: true, font: "Arial", color: DARK_GRAY }, paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 2 } },
      ]
    },
    sections: [{
      properties: { page: { size: { width: 12240, height: 15840 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
      headers: { default: new Header({ children: [new Paragraph({ border: { bottom: { style: BorderStyle.SINGLE, size: 2, color: BLUE } }, children: [new TextRun({ text: "Cours AWS pour Developpeurs Java - IAM & S3", font: "Arial", size: 18, color: BLUE })] })] }) },
      footers: { default: new Footer({ children: [new Paragraph({ border: { top: { style: BorderStyle.SINGLE, size: 2, color: BLUE } }, children: [new TextRun({ text: "AWS SDK for Java v2 - 2025  Page ", font: "Arial", size: 18, color: "888888" }), new TextRun({ children: [PageNumber.CURRENT], font: "Arial", size: 18, color: BLUE })] })] }) },
      children: content
    }]
  });

  const buffer = await Packer.toBuffer(doc);
  const outputPath = '/Users/user/Desktop/travel-agency/backend/.claude/worktrees/naughty-jepsen-0d5f95/cours_aws_java_part2.docx';
  fs.writeFileSync(outputPath, buffer);
  console.log('Part 2 generee: ' + outputPath + ' - ' + Math.round(buffer.length/1024) + ' KB');
}

generatePart2().catch(console.error);
